Koru Game Engine: engine/src/core/application.c File Reference
application.c File Reference
Implementation of the core application lifecycle functions.
#include "application.h"
#include "game_types.h"
#include "core/event.h"
#include "core/logger.h"
#include "core/kmemory.h"
#include "platform/platform.h"
#include "core/input.h"
#include "core/clock.h"
#include "memory/linear_allocator.h"
#include "renderer/renderer_frontend.h"
#include "core/kstring.h"
#include "systems/texture_system.h"
#include "systems/material_system.h"
#include "systems/geometry_system.h"
#include "math/kmath.h"
Data Structures
struct application_state
Internal state structure for the application.
Typedefs
typedef struct application_state application_state
Internal state structure for the application.
Functions
b8 application_on_event (u16 code, void *sender, void *listener_inst, event_context context)
Global event handler for application-level events.
b8 application_on_key (u16 code, void *sender, void *listener_inst, event_context context)
Handles keyboard input at the application level.
b8 application_on_resized (u16 code, void *sender, void *listener_inst, event_context context)
Handles window resize events.
b8 event_on_debug_event (u16 code, void *sender, void *listener_inst, event_context data)
Event handler for debug events to cycle through test textures.
b8 application_create (game *game_inst)
Initializes the application with the provided configuration.
b8 application_run ()
Starts the main application loop.
void application_get_framebuffer_size (u32 *width, u32 *height)
Retrieves the current window (framebuffer) size.
Variables
static application_state * app_state
Global instance of the application state.
Detailed Description
Implementation of the core application lifecycle functions.
This module implements the functions defined in application.h. It initializes the platform layer, starts the game loop, and manages clean shutdown procedures.
Responsibilities:
Initialize subsystems like memory and logging
Start and run the game loop
Gracefully shut down the engine
Definition in file application.c.
Typedef Documentation
application_state
typedef struct application_state application_state
Internal state structure for the application.
Tracks:
Application lifecycle (running/suspended)
Platform-specific data
Window dimensions
Timing information for frame updates
Function Documentation
application_create()
b8 application_create (game * game_inst)
Initializes the application with the provided configuration.
Creates and initializes the application instance.
This function must be called once before calling application_run(). It sets up internal systems such as logging, initializes the platform layer, and prepares the main application loop.
Parameters
config A pointer to an application_config struct containing initialization settings.
Returns
True if initialization was successful; False otherwise.
Definition at line 297 of file application.c.
References game::app_config, app_state, application_on_event(), application_on_key(), application_on_resized(), game::application_state, EVENT_CODE_APPLICATION_QUIT, EVENT_CODE_DEBUG0, EVENT_CODE_KEY_PRESSED, EVENT_CODE_KEY_RELEASED, EVENT_CODE_RESIZED, event_on_debug_event(), event_register(), event_system_initialize(), application_state::event_system_memory_requirement, application_state::event_system_state, False, application_state::game_inst, geometry_system_acquire_from_config(), geometry_system_generate_plane_config(), geometry_system_initialize(), application_state::geometry_system_memory_requirement, application_state::geometry_system_state, application_state::height, geometry_config::index_count, geometry_config::indices, game::initialize, initialize_logging(), initialize_memory(), input_system_initialize(), application_state::input_system_memory_requirement, application_state::input_system_state, application_state::is_running, application_state::is_suspended, kallocate(), KERROR, KFATAL, kfree(), linear_allocator_allocate(), linear_allocator_create(), application_state::logging_system_memory_requirement, application_state::logging_system_state, material_system_initialize(), application_state::material_system_memory_requirement, application_state::material_system_state, geometry_system_config::max_geometry_count, material_system_config::max_material_count, texture_system_config::max_texture_count, application_state::memory_system_memory_requirement, application_state::memory_system_state, MEMORY_TAG_APPLICATION, MEMORY_TAG_ARRAY, application_config::name, game::on_resize, application_state::platform_system_memory_requirement, platform_system_startup(), application_state::platform_system_state, renderer_system_initialize(), application_state::renderer_system_memory_requirement, application_state::renderer_system_state, application_config::start_height, application_config::start_pos_x, application_config::start_pos_y, application_config::start_width, application_state::systems_allocator, application_state::test_geometry, texture_system_initialize(), application_state::texture_system_memory_requirement, application_state::texture_system_state, True, geometry_config::vertex_count, geometry_config::vertices, and application_state::width.
Referenced by main().
application_get_framebuffer_size()
void application_get_framebuffer_size (u32 * width, u32 * height)
Retrieves the current window (framebuffer) size.
Used by the renderer to know what resolution to create/resize the swapchain to.
Parameters
width Output variable for the current width.
height Output variable for the current height.
Definition at line 557 of file application.c.
References app_state, application_state::height, and application_state::width.
Referenced by vulkan_renderer_backend_initialize().
application_on_event()
b8 application_on_event (u16 code, void * sender, void * listener_inst, event_context context)
Global event handler for application-level events.
This function listens for high-level system events like:
Application quit request (EVENT_CODE_APPLICATION_QUIT)
When such an event is received, it updates internal state to gracefully exit.
Parameters
code The event code that was fired.
sender A pointer to the object that sent the event (can be NULL).
listener_inst A pointer to the listener instance (unused here).
context Event-specific data (unused here).
Returns
True if the event was handled; False otherwise.
Definition at line 562 of file application.c.
References app_state, EVENT_CODE_APPLICATION_QUIT, False, application_state::is_running, KINFO, and True.
Referenced by application_create(), and application_run().
application_on_key()
b8 application_on_key (u16 code, void * sender, void * listener_inst, event_context context)
Handles keyboard input at the application level.
Responds to EVENT_CODE_KEY_PRESSED and EVENT_CODE_KEY_RELEASED events.
Special keys like Escape can trigger application-wide actions, while others are logged for debugging purposes.
Parameters
code The event code (e.g., key pressed/released).
sender A pointer to the object that triggered the event (unused here).
listener_inst A pointer to the listener instance (unused here).
context Event-specific data containing key information.
Returns
True if the event was handled; False otherwise.
Definition at line 574 of file application.c.
References context, EVENT_CODE_APPLICATION_QUIT, EVENT_CODE_KEY_PRESSED, EVENT_CODE_KEY_RELEASED, event_fire(), False, KDEBUG, and True.
Referenced by application_create(), and application_run().
application_on_resized()
b8 application_on_resized (u16 code, void * sender, void * listener_inst, event_context context)
Handles window resize events.
This function is registered as an event listener for 'EVENT_CODE_RESIZED' events. It updates internal state, suspends/resumes rendering, and forwards the resize event to the game and renderer modules.
On Linux/X11, minimized windows report size 0x0 — this function detects that and suspends rendering until the window is restored.
Parameters
code The event code (should be EVENT_CODE_RESIZED).
sender A pointer to the object that sent the event (unused here).
listener_inst A pointer to the listener instance (unused here).
context Event-specific data containing width and height.
Returns
True if handled; False otherwise (so other listeners can also receive the event).
Definition at line 602 of file application.c.
References app_state, context, EVENT_CODE_RESIZED, False, application_state::game_inst, application_state::height, application_state::is_suspended, KDEBUG, KINFO, game::on_resize, renderer_on_resized(), True, and application_state::width.
Referenced by application_create(), and application_run().
application_run()
b8 application_run ()
Starts the main application loop.
Begins running the game loop, which includes:
Processing events
Updating game logic
Rendering frames
This function blocks until the application exits.
Returns
True if the application exited cleanly; False if an error occurred or early exit.
Definition at line 425 of file application.c.
References app_state, application_on_event(), application_on_key(), application_on_resized(), application_state::clock, clock_start(), clock_update(), clock::elapsed, EVENT_CODE_APPLICATION_QUIT, EVENT_CODE_DEBUG0, EVENT_CODE_KEY_PRESSED, EVENT_CODE_KEY_RELEASED, EVENT_CODE_RESIZED, event_on_debug_event(), event_system_shutdown(), application_state::event_system_state, event_unregister(), False, application_state::game_inst, geometry_system_shutdown(), application_state::geometry_system_state, get_memory_usage_str(), input_system_shutdown(), application_state::input_system_state, input_update(), application_state::is_running, application_state::is_suspended, KFATAL, KINFO, application_state::last_time, mat4_identity(), material_system_shutdown(), application_state::material_system_state, application_state::memory_system_state, platform_get_absolute_time(), platform_pump_messages(), platform_sleep(), platform_system_shutdown(), application_state::platform_system_state, game::render, renderer_draw_frame(), renderer_system_shutdown(), application_state::renderer_system_state, shutdown_memory(), application_state::test_geometry, texture_system_shutdown(), application_state::texture_system_state, True, and game::update.
Referenced by main().
event_on_debug_event()
b8 event_on_debug_event (u16 code, void * sender, void * listener_inst, event_context data)
Event handler for debug events to cycle through test textures.
This function is a temporary event handler that listens for a specific debug event and cycles through a set of predefined textures for testing purposes.
Parameters
code The event code.
sender Pointer to the event sender.
listener_inst Pointer to the listener instance (should be the renderer state).
data Event context data (not used here).
Returns
True if the event was handled; otherwise False.
Definition at line 254 of file application.c.
References app_state, material::diffuse_map, KWARN, geometry::material, application_state::test_geometry, texture_map::texture, texture_system_acquire(), texture_system_get_default_texture(), texture_system_release(), and True.
Referenced by application_create(), and application_run().
Variable Documentation
app_state
application_state* app_state static
Global instance of the application state.
Definition at line 189 of file application.c.
Referenced by application_create(), application_get_framebuffer_size(), application_on_event(), application_on_resized(), application_run(), and event_on_debug_event().