Koru Game Engine: engine/src/core/application.h File Reference
application.h File Reference
Public interface for the core application system.
#include "defines.h"
Data Structures
struct application_config
Configuration settings for initializing the application.
Typedefs
typedef struct application_config application_config
Configuration settings for initializing the application.
Functions
KAPI b8 application_create (struct game *game_inst)
Creates and initializes the application instance.
b8 application_run ()
Starts the main application loop.
void application_get_framebuffer_size (u32 *width, u32 *height)
Retrieves the current window (framebuffer) size.
Detailed Description
Public interface for the core application system.
This module provides the main entry point and lifecycle management for the engine. It handles:
Application configuration (window size, position, name)
Initialization of core systems (memory, logging, platform layer)
The main game loop
Usage:
Define a create_game() function that populates a game struct
Call application_create() to initialize the engine
Call application_run() to start the game loop
Definition in file application.h.
Typedef Documentation
application_config
typedef struct application_config application_config
Configuration settings for initializing the application.
This structure contains window-related configuration such as position, size, and application name. It is passed to application_create() during startup.
Function Documentation
application_create()
KAPI b8 application_create (game * game_inst)
Creates and initializes the application instance.
Sets up internal systems like memory, logging, input, and prepares the game loop. Must be called before application_run().
Parameters
game_inst A pointer to the game instance containing setup parameters.
Returns
TRUE if initialization was successful; FALSE otherwise.
Creates and initializes the application instance.
This function must be called once before calling application_run(). It sets up internal systems such as logging, initializes the platform layer, and prepares the main application loop.
Parameters
config A pointer to an application_config struct containing initialization settings.
Returns
TRUE if initialization was successful; FALSE otherwise.
Definition at line 139 of file application.c.
References game::app_config, app_state, application_on_event(), application_on_key(), application_on_resized(), EVENT_CODE_APPLICATION_QUIT, EVENT_CODE_KEY_PRESSED, EVENT_CODE_KEY_RELEASED, EVENT_CODE_RESIZED, event_initialize(), event_register(), FALSE, application_state::game_inst, application_state::height, game::initialize, initialize_logging(), initialized, input_initialize(), application_state::is_running, application_state::is_suspended, KERROR, KFATAL, application_config::name, game::on_resize, application_state::platform, platform_startup(), renderer_initialize(), application_config::start_height, application_config::start_pos_x, application_config::start_pos_y, application_config::start_width, TRUE, and application_state::width.
Referenced by main().
application_get_framebuffer_size()
void application_get_framebuffer_size (u32 * width, u32 * height)
Retrieves the current window (framebuffer) size.
Used by the renderer to know what resolution to create/resize the swapchain to.
Parameters
width Output variable for the current width.
height Output variable for the current height.
Definition at line 301 of file application.c.
References app_state, application_state::height, and application_state::width.
Referenced by vulkan_renderer_backend_initialize().
application_run()
b8 application_run ()
Starts the main application loop.
Begins running the game loop, which includes:
Processing events
Updating game logic
Rendering frames
This function blocks until the application exits.
Returns
TRUE if the application exited cleanly; FALSE if an error occurred or early exit.
Definition at line 192 of file application.c.
References app_state, application_on_event(), application_on_key(), application_state::clock, clock_start(), clock_update(), clock::elapsed, EVENT_CODE_APPLICATION_QUIT, EVENT_CODE_KEY_PRESSED, EVENT_CODE_KEY_RELEASED, event_shutdown(), event_unregister(), FALSE, application_state::game_inst, get_memory_usage_str(), input_shutdown(), input_update(), application_state::is_running, application_state::is_suspended, KFATAL, KINFO, application_state::last_time, application_state::platform, platform_get_absolute_time(), platform_pump_messages(), platform_shutdown(), platform_sleep(), game::render, renderer_draw_frame(), renderer_shutdown(), TRUE, and game::update.
Referenced by main().