Koru Game Engine: engine/src/core/clock.h File Reference
clock.h File Reference
Provides a simple clock utility for timing operations.
#include "defines.h"
Data Structures
struct clock
Represents a simple clock that tracks elapsed time.
Typedefs
typedef struct clock clock
Functions
void clock_update (clock *clock)
Updates the clock's elapsed time based on current time.
void clock_start (clock *clock)
Starts or restarts the clock.
void clock_stop (clock *clock)
Stops the clock without resetting its elapsed time.
Detailed Description
Provides a simple clock utility for timing operations.
This module allows measuring elapsed time between start and stop events. It integrates with the platform abstraction layer to retrieve high-resolution time.
Definition in file clock.h.
Typedef Documentation
clock
typedef struct clock clock
Function Documentation
clock_start()
void clock_start (clock * clock)
Starts or restarts the clock.
Resets the elapsed time to zero and records the current time as the start time.
Parameters
clock A pointer to the clock instance to start.
Definition at line 19 of file clock.c.
References clock::elapsed, platform_get_absolute_time(), and clock::start_time.
Referenced by application_run().
clock_stop()
void clock_stop (clock * clock)
Stops the clock without resetting its elapsed time.
Sets the start_time to 0, effectively halting further updates to elapsed time.
Parameters
clock A pointer to the clock instance to stop.
Definition at line 24 of file clock.c.
References clock::start_time.
clock_update()
void clock_update (clock * clock)
Updates the clock's elapsed time based on current time.
This function should be called before querying the elapsed time. If the clock is not running (start_time == 0), this function has no effect.
Parameters
clock A pointer to the clock instance to update.
Definition at line 13 of file clock.c.
References clock::elapsed, platform_get_absolute_time(), and clock::start_time.
Referenced by application_run().