Koru Game Engine: engine/src/containers/darray.c File Reference
darray.c File Reference
Implementation of a dynamic array container.
#include "containers/darray.h"
#include "core/kmemory.h"
#include "core/logger.h"
Functions
void * _darray_create (u64 length, u64 stride)
Creates a new dynamic array with a given initial capacity and element size.
void _darray_destroy (void *array)
Destroys a dynamic array and frees its memory.
u64 _darray_field_get (void *array, u64 field)
Gets the value of a metadata field from the dynamic array.
void _darray_field_set (void *array, u64 field, u64 value)
Sets the value of a metadata field in the dynamic array.
void * _darray_resize (void *array)
Resizes the dynamic array when it runs out of space.
void * _darray_push (void *array, const void *value_ptr)
Pushes an element onto the end of the array.
void _darray_pop (void *array, void *dest)
Removes the last element from the array and stores it in dest.
void * _darray_pop_at (void *array, u64 index, void *dest)
Removes the element at the specified index and copies it to dest.
void * _darray_insert_at (void *array, u64 index, void *value_ptr)
Inserts an element at the specified index.
Detailed Description
Implementation of a dynamic array container.
This module implements a generic dynamic array (darray) system that supports:
Dynamic resizing based on usage
Insertion and removal at arbitrary indices
Type-safe macro wrappers for use in C code
Memory tracking via MEMORY_TAG_DARRAY
The internal layout consists of:
A header block containing metadata: capacity, length, stride
A contiguous block of elements stored after the header
Usage: This file should not be used directly. Instead, use the macro helpers defined in darray.h.
Definition in file darray.c.
Function Documentation
_darray_create()
void * _darray_create (u64 length, u64 stride)
Creates a new dynamic array with a given initial capacity and element size.
Internal function. Should not be called directly — use darray_create(type) instead.
Parameters
length Initial capacity of the array.
stride Size of each element in bytes.
Returns
A pointer to the newly created dynamic array.
Definition at line 24 of file darray.c.
References DARRAY_CAPACITY, DARRAY_FIELD_LENGTH, DARRAY_LENGTH, DARRAY_STRIDE, kallocate(), kset_memory(), and MEMORY_TAG_DARRAY.
Referenced by _darray_resize().
_darray_destroy()
void _darray_destroy (void * array)
Destroys a dynamic array and frees its memory.
Internal function. Should not be called directly — use darray_destroy(array) instead.
Parameters
array Pointer to the dynamic array to destroy.
Definition at line 44 of file darray.c.
References DARRAY_CAPACITY, DARRAY_FIELD_LENGTH, DARRAY_STRIDE, kfree(), and MEMORY_TAG_DARRAY.
Referenced by _darray_resize().
_darray_field_get()
u64 _darray_field_get (void * array, u64 field)
Gets the value of a metadata field from the dynamic array.
Internal function. Used by macros like darray_capacity() and darray_length().
Parameters
array Pointer to the dynamic array.
field Index of the field to retrieve (e.g., DARRAY_CAPACITY).
Returns
The value of the requested field.
Definition at line 56 of file darray.c.
References DARRAY_FIELD_LENGTH.
_darray_field_set()
void _darray_field_set (void * array, u64 field, u64 value)
Sets the value of a metadata field in the dynamic array.
Internal function. Used by macros like darray_clear() and darray_length_set().
Parameters
array Pointer to the dynamic array.
field Index of the field to set.
value New value for the field.
Definition at line 63 of file darray.c.
References DARRAY_FIELD_LENGTH.
Referenced by _darray_insert_at(), _darray_pop(), _darray_pop_at(), _darray_push(), and _darray_resize().
_darray_insert_at()
void * _darray_insert_at (void * array, u64 index, void * value_ptr)
Inserts an element at the specified index.
Internal function. Use darray_insert_at(array, index, value) instead.
Parameters
array Pointer to the dynamic array.
index Index where the element should be inserted.
value_ptr Pointer to the value to insert.
Returns
A pointer to the modified array (possibly reallocated).
Definition at line 155 of file darray.c.
References _darray_field_set(), _darray_resize(), darray_capacity, DARRAY_LENGTH, darray_length, darray_stride, kcopy_memory(), and KERROR.
_darray_pop()
void _darray_pop (void * array, void * dest)
Removes the last element from the array and stores it in dest.
Internal function. Use darray_pop(array, &dest) instead.
Parameters
array Pointer to the dynamic array.
dest Pointer to where the popped element should be copied.
Definition at line 112 of file darray.c.
References _darray_field_set(), DARRAY_LENGTH, darray_length, darray_stride, and kcopy_memory().
_darray_pop_at()
void * _darray_pop_at (void * array, u64 index, void * dest)
Removes the element at the specified index and copies it to dest.
Internal function. Use darray_pop_at(array, index, &dest) instead.
Parameters
array Pointer to the dynamic array.
index Index of the element to remove.
dest Pointer to where the removed element should be copied.
Definition at line 127 of file darray.c.
References _darray_field_set(), DARRAY_LENGTH, darray_length, darray_stride, kcopy_memory(), and KERROR.
_darray_push()
void * _darray_push (void * array, const void * value_ptr)
Pushes an element onto the end of the array.
If the array is full, it will be resized internally.
Internal function. Use darray_push(array, value) instead.
Parameters
array Pointer to the dynamic array.
value_ptr Pointer to the value to insert.
Returns
A pointer to the array (possibly reallocated).
Definition at line 90 of file darray.c.
References _darray_field_set(), _darray_resize(), darray_capacity, DARRAY_LENGTH, darray_length, darray_stride, and kcopy_memory().
_darray_resize()
void * _darray_resize (void * array)
Resizes the dynamic array when it runs out of space.
Doubles the capacity if needed. Internal function used by darray_push().
Parameters
array Pointer to the dynamic array.
Returns
A pointer to the resized array (may be different from input).
Definition at line 69 of file darray.c.
References _darray_create(), _darray_destroy(), _darray_field_set(), darray_capacity, DARRAY_LENGTH, darray_length, DARRAY_RESIZE_FACTOR, darray_stride, and kcopy_memory().
Referenced by _darray_insert_at(), and _darray_push().