Koru Game Engine: engine/src/containers/darray.h File Reference
darray.h File Reference
Dynamic array implementation with automatic resizing.
#include "defines.h"
Macros
#define DARRAY_DEFAULT_CAPACITY 1
Default initial capacity for new dynamic arrays.
#define DARRAY_RESIZE_FACTOR 2
Factor by which the array grows when full.
#define darray_create(type) _darray_create(DARRAY_DEFAULT_CAPACITY, sizeof(type))
Creates a dynamic array with default capacity for a specific type.
#define darray_reserve(type, capacity) _darray_create(capacity, sizeof(type))
Creates a dynamic array with a custom initial capacity.
#define darray_destroy(array) _darray_destroy(array)
Destroys a dynamic array and frees its memory.
#define darray_push(array, value)
Adds an element to the end of the array.
#define darray_pop(array, value_ptr) _darray_pop(array, value_ptr)
Removes the last element from the array and copies it to the destination.
#define darray_insert_at(array, index, value)
Inserts an element at a specific index.
#define darray_pop_at(array, index, value_ptr) _darray_pop_at(array, index, value_ptr)
Removes the element at a specific index and copies it to the destination.
#define darray_clear(array) _darray_field_set(array, DARRAY_LENGTH, 0)
Clears the array without freeing memory.
#define darray_capacity(array) _darray_field_get(array, DARRAY_CAPACITY)
Gets the current capacity (allocated slots) of the array.
#define darray_length(array) _darray_field_get(array, DARRAY_LENGTH)
Gets the current length (number of elements) in the array.
#define darray_stride(array) _darray_field_get(array, DARRAY_STRIDE)
Gets the size of each element (in bytes) in the array.
#define darray_length_set(array, value) _darray_field_set(array, DARRAY_LENGTH, value)
Sets the current length of the array.
Enumerations
enum { DARRAY_CAPACITY , DARRAY_LENGTH , DARRAY_STRIDE , DARRAY_FIELD_LENGTH }
Memory layout of a dynamic array.
Functions
KAPI void * _darray_create (u64 length, u64 stride)
Creates a new dynamic array with a given initial capacity and element size.
KAPI void _darray_destroy (void *array)
Destroys a dynamic array and frees its memory.
KAPI u64 _darray_field_get (void *array, u64 field)
Gets the value of a metadata field from the dynamic array.
KAPI void _darray_field_set (void *array, u64 field, u64 value)
Sets the value of a metadata field in the dynamic array.
KAPI void * _darray_resize (void *array)
Resizes the dynamic array when it runs out of space.
KAPI void * _darray_push (void *array, const void *value_ptr)
Pushes an element onto the end of the array.
KAPI void _darray_pop (void *array, void *dest)
Removes the last element from the array and stores it in dest.
KAPI void * _darray_pop_at (void *array, u64 index, void *dest)
Removes the element at the specified index and copies it to dest.
KAPI void * _darray_insert_at (void *array, u64 index, void *value_ptr)
Inserts an element at the specified index.
Detailed Description
Dynamic array implementation with automatic resizing.
This module provides a flexible dynamic array (darray) system that can store any data type. It supports:
Dynamic resizing based on capacity and growth factor
Insertion and removal at arbitrary indices
Compile-time type safety through macros
Tracking of length, capacity, and stride
Usage: Use the macro helpers like darray_create(type) and darray_push() to work with typed arrays. Never call internal _darray_* functions directly.
Definition in file darray.h.
Macro Definition Documentation
darray_capacity
#define darray_capacity (array) _darray_field_get(array, DARRAY_CAPACITY)
Gets the current capacity (allocated slots) of the array.
Example:
u64 cap = darray_capacity(my_array);
Definition at line 247 of file darray.h.
darray_clear
#define darray_clear (array) _darray_field_set(array, DARRAY_LENGTH, 0)
Clears the array without freeing memory.
Resets the length to zero.
Example:
darray_clear(my_array);
Definition at line 236 of file darray.h.
darray_create
#define darray_create (type) _darray_create(DARRAY_DEFAULT_CAPACITY, sizeof(type))
Creates a dynamic array with default capacity for a specific type.
Example:
i32* my_array = darray_create(i32);
Definition at line 148 of file darray.h.
DARRAY_DEFAULT_CAPACITY
#define DARRAY_DEFAULT_CAPACITY 1
Default initial capacity for new dynamic arrays.
Definition at line 137 of file darray.h.
darray_destroy
#define darray_destroy (array) _darray_destroy(array)
Destroys a dynamic array and frees its memory.
Example:
darray_destroy(my_array);
Definition at line 170 of file darray.h.
darray_insert_at
#define darray_insert_at (array, index, value)
Value:
    {                                                   \
        typeof(value) temp = value;                     \
        array = _darray_insert_at(array, index, &temp); \
    }
Inserts an element at a specific index.
Example:
darray_insert_at(my_array, 2, 99); // Insert 99 at index 2
Definition at line 208 of file darray.h.
darray_length
#define darray_length (array) _darray_field_get(array, DARRAY_LENGTH)
Gets the current length (number of elements) in the array.
Example:
u64 len = darray_length(my_array);
Definition at line 258 of file darray.h.
darray_length_set
#define darray_length_set (array, value) _darray_field_set(array, DARRAY_LENGTH, value)
Sets the current length of the array.
Useful for manually managing array length.
Example:
darray_length_set(my_array, 5); // Set logical length to 5
Definition at line 282 of file darray.h.
darray_pop
#define darray_pop (array, value_ptr) _darray_pop(array, value_ptr)
Removes the last element from the array and copies it to the destination.
Example:
i32 value;
darray_pop(my_array, &value);
Definition at line 197 of file darray.h.
darray_pop_at
#define darray_pop_at (array, index, value_ptr) _darray_pop_at(array, index, value_ptr)
Removes the element at a specific index and copies it to the destination.
Example:
i32 value;
darray_pop_at(my_array, 1, &value); // Remove item at index 1
Definition at line 223 of file darray.h.
darray_push
#define darray_push (array, value)
Value:
    {                                       \
        typeof(value) temp = value;         \
        array = _darray_push(array, &temp); \
    }
Adds an element to the end of the array.
Automatically resizes the array if necessary.
Example:
darray_push(my_array, 42);
Definition at line 182 of file darray.h.
darray_reserve
#define darray_reserve (type, capacity) _darray_create(capacity, sizeof(type))
Creates a dynamic array with a custom initial capacity.
Example:
i32* my_array = darray_reserve(i32, 10); // Reserve space for 10 integers
Definition at line 159 of file darray.h.
DARRAY_RESIZE_FACTOR
#define DARRAY_RESIZE_FACTOR 2
Factor by which the array grows when full.
Definition at line 138 of file darray.h.
darray_stride
#define darray_stride (array) _darray_field_get(array, DARRAY_STRIDE)
Gets the size of each element (in bytes) in the array.
Example:
u64 stride = darray_stride(my_array);
Definition at line 269 of file darray.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Memory layout of a dynamic array.
The dynamic array is implemented as a contiguous block of memory with the following layout:
[0] u64: capacity (number of elements that can be held)
[1] u64: length (number of elements currently stored)
[2] u64: stride (size in bytes of each element)
[3] void*: pointer to the start of the elements array
Enumerator
DARRAY_CAPACITY
Index of the capacity field (max number of elements)
DARRAY_LENGTH
Index of the length field (current number of elements)
DARRAY_STRIDE
Index of the stride field (size of each element in bytes)
DARRAY_FIELD_LENGTH
Total number of metadata fields before the first element.
Definition at line 31 of file darray.h.
Function Documentation
_darray_create()
KAPI void * _darray_create (u64 length, u64 stride)
Creates a new dynamic array with a given initial capacity and element size.
Internal function. Should not be called directly use darray_create(type) instead.
Parameters
length Initial capacity of the array.
stride Size of each element in bytes.
Returns
A pointer to the newly created dynamic array.
Definition at line 24 of file darray.c.
References DARRAY_CAPACITY, DARRAY_FIELD_LENGTH, DARRAY_LENGTH, DARRAY_STRIDE, kallocate(), kset_memory(), and MEMORY_TAG_DARRAY.
Referenced by _darray_resize().
_darray_destroy()
KAPI void _darray_destroy (void * array)
Destroys a dynamic array and frees its memory.
Internal function. Should not be called directly use darray_destroy(array) instead.
Parameters
array Pointer to the dynamic array to destroy.
Definition at line 44 of file darray.c.
References DARRAY_CAPACITY, DARRAY_FIELD_LENGTH, DARRAY_STRIDE, kfree(), and MEMORY_TAG_DARRAY.
Referenced by _darray_resize().
_darray_field_get()
KAPI u64 _darray_field_get (void * array, u64 field)
Gets the value of a metadata field from the dynamic array.
Internal function. Used by macros like darray_capacity() and darray_length().
Parameters
array Pointer to the dynamic array.
field Index of the field to retrieve (e.g., DARRAY_CAPACITY).
Returns
The value of the requested field.
Definition at line 56 of file darray.c.
References DARRAY_FIELD_LENGTH.
_darray_field_set()
KAPI void _darray_field_set (void * array, u64 field, u64 value)
Sets the value of a metadata field in the dynamic array.
Internal function. Used by macros like darray_clear() and darray_length_set().
Parameters
array Pointer to the dynamic array.
field Index of the field to set.
value New value for the field.
Definition at line 63 of file darray.c.
References DARRAY_FIELD_LENGTH.
Referenced by _darray_insert_at(), _darray_pop(), _darray_pop_at(), _darray_push(), and _darray_resize().
_darray_insert_at()
KAPI void * _darray_insert_at (void * array, u64 index, void * value_ptr)
Inserts an element at the specified index.
Internal function. Use darray_insert_at(array, index, value) instead.
Parameters
array Pointer to the dynamic array.
index Index where the element should be inserted.
value_ptr Pointer to the value to insert.
Returns
A pointer to the modified array (possibly reallocated).
Definition at line 155 of file darray.c.
References _darray_field_set(), _darray_resize(), darray_capacity, DARRAY_LENGTH, darray_length, darray_stride, kcopy_memory(), and KERROR.
_darray_pop()
KAPI void _darray_pop (void * array, void * dest)
Removes the last element from the array and stores it in dest.
Internal function. Use darray_pop(array, &dest) instead.
Parameters
array Pointer to the dynamic array.
dest Pointer to where the popped element should be copied.
Definition at line 112 of file darray.c.
References _darray_field_set(), DARRAY_LENGTH, darray_length, darray_stride, and kcopy_memory().
_darray_pop_at()
KAPI void * _darray_pop_at (void * array, u64 index, void * dest)
Removes the element at the specified index and copies it to dest.
Internal function. Use darray_pop_at(array, index, &dest) instead.
Parameters
array Pointer to the dynamic array.
index Index of the element to remove.
dest Pointer to where the removed element should be copied.
Definition at line 127 of file darray.c.
References _darray_field_set(), DARRAY_LENGTH, darray_length, darray_stride, kcopy_memory(), and KERROR.
_darray_push()
KAPI void * _darray_push (void * array, const void * value_ptr)
Pushes an element onto the end of the array.
If the array is full, it will be resized internally.
Internal function. Use darray_push(array, value) instead.
Parameters
array Pointer to the dynamic array.
value_ptr Pointer to the value to insert.
Returns
A pointer to the array (possibly reallocated).
Definition at line 90 of file darray.c.
References _darray_field_set(), _darray_resize(), darray_capacity, DARRAY_LENGTH, darray_length, darray_stride, and kcopy_memory().
_darray_resize()
KAPI void * _darray_resize (void * array)
Resizes the dynamic array when it runs out of space.
Doubles the capacity if needed. Internal function used by darray_push().
Parameters
array Pointer to the dynamic array.
Returns
A pointer to the resized array (may be different from input).
Definition at line 69 of file darray.c.
References _darray_create(), _darray_destroy(), _darray_field_set(), darray_capacity, DARRAY_LENGTH, darray_length, DARRAY_RESIZE_FACTOR, darray_stride, and kcopy_memory().
Referenced by _darray_insert_at(), and _darray_push().