Koru Game Engine: engine/src/entry.h File Reference
entry.h File Reference
Main entry point interface for the engine.
#include "core/application.h"
#include "core/kmemory.h"
#include "core/logger.h"
#include "game_types.h"
Functions
b8 create_game (game *out_game)
Externally-defined function to create and configure a game instance.
int main (void)
The main entry point of the application.
Detailed Description
Main entry point interface for the engine.
This file defines the externally-defined create_game() function that must be implemented by client applications. It also contains the main() function declaration which initializes and runs the game loop.
Responsibilities:
Define the entry point contract
Ensure proper initialization order
Integrate memory and logging systems at startup
Definition in file entry.h.
Function Documentation
create_game()
b8 create_game (game * out_game) extern
Externally-defined function to create and configure a game instance.
This function must be implemented by the client application (e.g., testbed). It sets up:
Window configuration
Game-specific function pointers (initialize/update/render/etc.)
Game state memory allocation
Parameters
out_game A pointer to an uninitialized game struct that will be populated.
Returns
TRUE if the game was successfully created; FALSE otherwise.
Definition at line 20 of file entry.c.
References game::app_config, game_initialize(), game_on_resize(), game_render(), game_update(), game::initialize, kallocate(), MEMORY_TAG_GAME, application_config::name, game::on_resize, game::render, application_config::start_height, application_config::start_pos_x, application_config::start_pos_y, application_config::start_width, game::state, TRUE, and game::update.
Referenced by main().
main()
int main (void)
The main entry point of the application.
This function performs the following steps:
Requests a configured game instance from create_game()
Validates required function pointers
Initializes the core application system
Starts the main application/game loop
Returns
Exit code indicating success or failure.
0: Success
-1: Failed to create game
-2: Missing required game function pointers
1: Application failed during initialization
2: Application failed during shutdown
Definition at line 51 of file entry.h.
References application_create(), application_run(), create_game(), game::initialize, initialize_memory(), KFATAL, KINFO, game::on_resize, game::render, shutdown_memory(), and game::update.