Koru Game Engine: testbed/src/entry.c File Reference
entry.c File Reference
Testbed application entry point implementation.
#include "game.h"
#include <entry.h>
#include <core/kmemory.h>
Functions
b8 create_game (game *out_game)
Externally-defined function to create and configure a game instance.
Detailed Description
Testbed application entry point implementation.
This file implements the required create_game() function used by the engine. It sets up the game configuration and allocates the game state.
Responsibilities:
Configure window settings
Assign game lifecycle function pointers
Allocate game-specific memory
Definition in file entry.c.
Function Documentation
create_game()
b8 create_game (game * out_game)
Externally-defined function to create and configure a game instance.
This function must be implemented by the client application (e.g., testbed). It sets up:
Window configuration
Game-specific function pointers (initialize/update/render/etc.)
Game state memory allocation
Parameters
out_game A pointer to an uninitialized game struct that will be populated.
Returns
True if the game was successfully created; False otherwise.
Definition at line 20 of file entry.c.
References game::app_config, game::application_state, game_initialize(), game_on_resize(), game_render(), game_update(), game::initialize, kallocate(), MEMORY_TAG_GAME, application_config::name, game::on_resize, game::render, application_config::start_height, application_config::start_pos_x, application_config::start_pos_y, application_config::start_width, game::state, True, and game::update.
Referenced by main().