Koru Game Engine: engine/src/core/event.h File Reference
event.h File Reference
Event system for inter-component communication.
#include "defines.h"
Data Structures
struct event_context
Context structure used to pass event-specific data.
Typedefs
typedef struct event_context event_context
Context structure used to pass event-specific data.
typedef b8(* PFN_on_event) (u16 code, void *sender, void *listener_inst, event_context data)
Event handler callback function type.
typedef enum system_event_code system_event_code
Built-in system event codes.
Enumerations
enum system_event_code {
EVENT_CODE_APPLICATION_QUIT = 0x01 , EVENT_CODE_KEY_PRESSED = 0x02 , EVENT_CODE_KEY_RELEASED = 0x03 , EVENT_CODE_BUTTON_PRESSED = 0x04 ,
EVENT_CODE_BUTTON_RELEASED = 0x05 , EVENT_CODE_MOUSE_MOVED = 0x06 , EVENT_CODE_MOUSE_WHEEL = 0x07 , EVENT_CODE_RESIZED = 0x08 ,
MAX_EVENT_CODE = 0xFF
}
Built-in system event codes.
Functions
b8 event_initialize ()
Initializes the event system.
void event_shutdown ()
Shuts down the event system.
KAPI b8 event_register (u16 code, void *listener, PFN_on_event on_event)
Registers a listener for a specific event code.
KAPI b8 event_unregister (u16 code, void *listener, PFN_on_event on_event)
Unregisters a listener for a specific event code.
KAPI b8 event_fire (u16 code, void *sender, event_context context)
Fires an event to all registered listeners for the given code.
Detailed Description
Event system for inter-component communication.
This module provides a generic event system that allows components to:
Register listeners for specific event codes
Fire events with optional context data
Unregister listeners when no longer needed
Events are identified by a 16-bit code, and can carry up to 128 bytes of arbitrary data via the event_context union. System-defined event codes use values up to 0xFF; applications should define their own codes starting from 0x100 or higher.
Definition in file event.h.
Typedef Documentation
event_context
typedef struct event_context event_context
Context structure used to pass event-specific data.
This structure contains a union of various primitive types, allowing event handlers to interpret data flexibly based on the event code. Total size is guaranteed to be 128 bytes.
PFN_on_event
typedef b8(* PFN_on_event) (u16 code, void *sender, void *listener_inst, event_context data)
Event handler callback function type.
Called when an event matching the registered code is fired.
Parameters
code The event code.
sender A pointer to the object that triggered the event.
listener_inst A pointer to the listener instance (optional).
data The event context containing additional data.
Returns
TRUE if the event was handled; FALSE to allow further propagation.
Definition at line 79 of file event.h.
system_event_code
typedef enum system_event_code system_event_code
Built-in system event codes.
These are reserved for internal engine use. Applications should use custom codes above MAX_EVENT_CODE.
Enumeration Type Documentation
system_event_code
enum system_event_code
Built-in system event codes.
These are reserved for internal engine use. Applications should use custom codes above MAX_EVENT_CODE.
Enumerator
EVENT_CODE_APPLICATION_QUIT
Shuts the application down on the next frame.
EVENT_CODE_KEY_PRESSED
Fired when a keyboard key is pressed.
Usage:
u16 key_code = context.data.u16[0];
EVENT_CODE_KEY_RELEASED
Fired when a keyboard key is released.
Usage:
u16 key_code = context.data.u16[0];
EVENT_CODE_BUTTON_PRESSED
Fired when a mouse button is pressed.
Usage:
u16 button = context.data.u16[0];
EVENT_CODE_BUTTON_RELEASED
Fired when a mouse button is released.
Usage:
u16 button = context.data.u16[0];
EVENT_CODE_MOUSE_MOVED
Fired when the mouse is moved.
Usage:
u16 x = context.data.u16[0];
u16 y = context.data.u16[1];
EVENT_CODE_MOUSE_WHEEL
Fired when the mouse wheel is scrolled.
Usage:
u8 z_delta = context.data.u8[0];
EVENT_CODE_RESIZED
Fired when the window is resized or resolution changes.
Usage:
u16 width = context.data.u16[0];
u16 height = context.data.u16[1];
MAX_EVENT_CODE
Maximum valid system event code.
Reserved for internal use — applications should define custom codes beyond this.
Definition at line 143 of file event.h.
Function Documentation
event_fire()
KAPI b8 event_fire (u16 code, void * sender, event_context context)
Fires an event to all registered listeners for the given code.
If any handler returns TRUE, the event is considered handled and will not be passed to remaining listeners.
Parameters
code The event code to fire.
sender A pointer to the object that triggered the event. Can be NULL.
context The event context containing additional data.
Returns
TRUE if handled by at least one listener; FALSE otherwise.
Definition at line 156 of file event.c.
References registered_event::callback, context, darray_length, event_code_entry::events, FALSE, is_initialized, registered_event::listener, event_system_state::registered, state, and TRUE.
Referenced by application_on_key(), input_process_button(), input_process_key(), input_process_mouse_move(), and input_process_mouse_wheel().
event_initialize()
b8 event_initialize ()
Initializes the event system.
Must be called before any other event functions are used. Sets up internal structures for managing event listeners.
Returns
TRUE if initialization succeeded; FALSE otherwise.
Definition at line 76 of file event.c.
References FALSE, is_initialized, kzero_memory(), state, and TRUE.
Referenced by application_create().
event_register()
KAPI b8 event_register (u16 code, void * listener, PFN_on_event on_event)
Registers a listener for a specific event code.
Prevents duplicate registrations of the same listener/callback pair. Multiple different callbacks for the same code are allowed.
Parameters
code The event code to listen for.
listener A pointer to a listener instance. Can be NULL.
on_event The callback function to invoke when the event fires.
Returns
TRUE if successfully registered; FALSE if already registered or invalid parameters.
Definition at line 100 of file event.c.
References registered_event::callback, darray_create, darray_length, darray_push, event_code_entry::events, FALSE, is_initialized, registered_event::listener, event_system_state::registered, state, and TRUE.
Referenced by application_create().
event_shutdown()
void event_shutdown ()
Shuts down the event system.
Cleans up internal state, removes all registered listeners, and prepares for safe termination.
Definition at line 88 of file event.c.
References darray_destroy, event_code_entry::events, FALSE, is_initialized, MAX_MESSAGE_CODES, event_system_state::registered, and state.
Referenced by application_run().
event_unregister()
KAPI b8 event_unregister (u16 code, void * listener, PFN_on_event on_event)
Unregisters a listener for a specific event code.
If no matching registration exists, this function returns FALSE.
Parameters
code The event code to stop listening for.
listener A pointer to a listener instance. Can be NULL.
on_event The callback function to unregister.
Returns
TRUE if successfully unregistered; FALSE if not found.
Definition at line 129 of file event.c.
References registered_event::callback, darray_length, darray_pop_at, event_code_entry::events, FALSE, is_initialized, registered_event::listener, event_system_state::registered, state, and TRUE.
Referenced by application_run().