Koru Game Engine: engine/src/core/event.c File Reference
event.c File Reference
Implementation of a generic event system for inter-component communication.
#include "core/event.h"
#include "core/kmemory.h"
#include "containers/darray.h"
Data Structures
struct registered_event
Internal structure representing a registered event listener.
struct event_code_entry
Entry for an event code, containing all registered listeners.
struct event_system_state
Global state for the event system.
Macros
#define MAX_MESSAGE_CODES 16384
Maximum number of unique event codes supported.
Typedefs
typedef struct registered_event registered_event
Internal structure representing a registered event listener.
typedef struct event_code_entry event_code_entry
Entry for an event code, containing all registered listeners.
typedef struct event_system_state event_system_state
Global state for the event system.
Functions
b8 event_initialize ()
Initializes the event system.
void event_shutdown ()
Shuts down the event system.
b8 event_register (u16 code, void *listener, PFN_on_event on_event)
Registers a listener for a specific event code.
b8 event_unregister (u16 code, void *listener, PFN_on_event on_event)
Unregisters a listener for a specific event code.
b8 event_fire (u16 code, void *sender, event_context context)
Fires an event to all registered listeners for the given code.
Variables
static b8 is_initialized = False
Internal state tracking whether the system has been initialized.
static event_system_state state
Static global instance of the event system state.
Detailed Description
Implementation of a generic event system for inter-component communication.
This module implements a centralized event system that allows components to:
Register listeners for specific event codes
Fire events with optional context data
Unregister listeners when no longer needed
Internally, it uses dynamic arrays (darray) to manage event callbacks per code, and ensures that duplicate registrations are not allowed.
Usage: Use the public API functions in event.h to interact with this system. Never access internal structures directly.
Definition in file event.c.
Macro Definition Documentation
MAX_MESSAGE_CODES
#define MAX_MESSAGE_CODES 16384
Maximum number of unique event codes supported.
Definition at line 50 of file event.c.
Typedef Documentation
event_code_entry
typedef struct event_code_entry event_code_entry
Entry for an event code, containing all registered listeners.
Each event code maps to an array of registered events.
event_system_state
typedef struct event_system_state event_system_state
Global state for the event system.
Maintains a lookup table mapping event codes to their listeners.
registered_event
typedef struct registered_event registered_event
Internal structure representing a registered event listener.
Function Documentation
event_fire()
b8 event_fire (u16 code, void * sender, event_context context)
Fires an event to all registered listeners for the given code.
If any handler returns True, the event is considered handled and will not be passed to remaining listeners.
Parameters
code The event code to fire.
sender A pointer to the object that triggered the event. Can be NULL.
context The event context containing additional data.
Returns
True if handled by at least one listener; False otherwise.
Definition at line 156 of file event.c.
References registered_event::callback, context, darray_length, event_code_entry::events, False, is_initialized, registered_event::listener, event_system_state::registered, state, and True.
Referenced by application_on_key(), input_process_button(), input_process_key(), input_process_mouse_move(), and input_process_mouse_wheel().
event_initialize()
b8 event_initialize ()
Initializes the event system.
Must be called before any other event functions are used. Sets up internal structures for managing event listeners.
Returns
True if initialization succeeded; False otherwise.
Definition at line 76 of file event.c.
References False, is_initialized, kzero_memory(), state, and True.
Referenced by application_create().
event_register()
b8 event_register (u16 code, void * listener, PFN_on_event on_event)
Registers a listener for a specific event code.
Prevents duplicate registrations of the same listener/callback pair. Multiple different callbacks for the same code are allowed.
Parameters
code The event code to listen for.
listener A pointer to a listener instance. Can be NULL.
on_event The callback function to invoke when the event fires.
Returns
True if successfully registered; False if already registered or invalid parameters.
Definition at line 100 of file event.c.
References registered_event::callback, darray_create, darray_length, darray_push, event_code_entry::events, False, is_initialized, registered_event::listener, event_system_state::registered, state, and True.
Referenced by application_create().
event_shutdown()
void event_shutdown ()
Shuts down the event system.
Cleans up internal state, removes all registered listeners, and prepares for safe termination.
Definition at line 88 of file event.c.
References darray_destroy, event_code_entry::events, False, is_initialized, MAX_MESSAGE_CODES, event_system_state::registered, and state.
Referenced by application_run().
event_unregister()
b8 event_unregister (u16 code, void * listener, PFN_on_event on_event)
Unregisters a listener for a specific event code.
If no matching registration exists, this function returns False.
Parameters
code The event code to stop listening for.
listener A pointer to a listener instance. Can be NULL.
on_event The callback function to unregister.
Returns
True if successfully unregistered; False if not found.
Definition at line 129 of file event.c.
References registered_event::callback, darray_length, darray_pop_at, event_code_entry::events, False, is_initialized, registered_event::listener, event_system_state::registered, state, and True.
Referenced by application_run().
Variable Documentation
is_initialized
b8 is_initialized = False static
Internal state tracking whether the system has been initialized.
Definition at line 69 of file event.c.
Referenced by event_fire(), event_initialize(), event_register(), event_shutdown(), and event_unregister().
state
event_system_state state static
Static global instance of the event system state.
Definition at line 74 of file event.c.
Referenced by event_fire(), event_initialize(), event_register(), event_shutdown(), and event_unregister().