Koru Game Engine: engine/src/platform/filesystem.h File Reference
filesystem.h File Reference
#include "defines.h"
Data Structures
struct file_handle
Typedefs
typedef struct file_handle file_handle
typedef enum file_modes file_modes
Enumerations
enum file_modes { FILE_MODE_READ = 0x1 , FILE_MODE_WRITE = 0x2 }
Functions
KAPI b8 filesystem_exists (const char *path)
KAPI b8 filesystem_open (const char *path, file_modes mode, b8 binary, file_handle *out_handle)
KAPI void filesystem_close (file_handle *handle)
KAPI b8 filesystem_read_line (file_handle *handle, char **line_buf)
KAPI b8 filesystem_write_line (file_handle *handle, const char *text)
KAPI b8 filesystem_read (file_handle *handle, u64 data_size, void *out_data, u64 *out_bytes_read)
KAPI b8 filesystem_read_all_bytes (file_handle *handle, u8 **out_bytes, u64 *out_bytes_read)
KAPI b8 filesystem_write (file_handle *handle, u64 data_size, const void *data, u64 *out_bytes_written)
Typedef Documentation
file_handle
typedef struct file_handle file_handle
file_modes
typedef enum file_modes file_modes
Enumeration Type Documentation
file_modes
enum file_modes
Represents the modes in which a file can be opened.
Enumerator
FILE_MODE_READ
FILE_MODE_WRITE
Definition at line 22 of file filesystem.h.
Function Documentation
filesystem_close()
KAPI void filesystem_close (file_handle * handle)
Closes the provided handle to a file.
Parameters
handle A pointer to a file_handle structure which holds the handle to be closed.
Definition at line 44 of file filesystem.c.
References False, file_handle::handle, and file_handle::is_valid.
Referenced by create_shader_module().
filesystem_exists()
KAPI b8 filesystem_exists (const char * path)
Checks if a file with the given path exists.
Parameters
path The path of the file to be checked.
Returns
True if exists; otherwise false.
Definition at line 10 of file filesystem.c.
filesystem_open()
KAPI b8 filesystem_open (const char * path, file_modes mode, b8 binary, file_handle * out_handle)
Attempt to open file located at path.
Parameters
path The path of the file to be opened.
mode Mode flags for the file when opened (read/write). See file_modes enum in filesystem.h.
binary Indicates if the file should be opened in binary mode.
out_handle A pointer to a file_handle structure which holds the handle information.
Returns
True if opened successfully; otherwise false.
Definition at line 15 of file filesystem.c.
References False, FILE_MODE_READ, FILE_MODE_WRITE, file_handle::handle, file_handle::is_valid, KERROR, and True.
Referenced by create_shader_module(), and initialize_logging().
filesystem_read()
KAPI b8 filesystem_read (file_handle * handle, u64 data_size, void * out_data, u64 * out_bytes_read)
Reads up to data_size bytes of data into out_bytes_read. Allocates *out_data, which must be freed by the caller.
Parameters
handle A pointer to a file_handle structure.
data_size The number of bytes to read.
out_data A pointer to a block of memory to be populated by this method.
out_bytes_read A pointer to a number which will be populated with the number of bytes actually read from the file.
Returns
True if successful; otherwise false.
Definition at line 81 of file filesystem.c.
References False, file_handle::handle, and True.
filesystem_read_all_bytes()
KAPI b8 filesystem_read_all_bytes (file_handle * handle, u8 ** out_bytes, u64 * out_bytes_read)
Reads up to data_size bytes of data into out_bytes_read. Allocates *out_bytes, which must be freed by the caller.
Parameters
handle A pointer to a file_handle structure.
out_bytes A pointer to a byte array which will be allocated and populated by this method.
out_bytes_read A pointer to a number which will be populated with the number of bytes actually read from the file.
Returns
True if successful; otherwise false.
Definition at line 92 of file filesystem.c.
References False, file_handle::handle, kallocate(), MEMORY_TAG_STRING, and True.
Referenced by create_shader_module().
filesystem_read_line()
KAPI b8 filesystem_read_line (file_handle * handle, char ** line_buf)
Reads up to a newline or EOF. Allocates *line_buf, which must be freed by the caller.
Parameters
handle A pointer to a file_handle structure.
line_buf A pointer to a character array which will be allocated and populated by this method.
Returns
True if successful; otherwise false.
Definition at line 52 of file filesystem.c.
References False, file_handle::handle, kallocate(), MEMORY_TAG_STRING, and True.
filesystem_write()
KAPI b8 filesystem_write (file_handle * handle, u64 data_size, const void * data, u64 * out_bytes_written)
Writes provided data to the file.
Parameters
handle A pointer to a file_handle structure.
data_size The size of the data in bytes.
data The data to be written.
out_bytes_written A pointer to a number which will be populated with the number of bytes actually written to the file.
Returns
True if successful; otherwise false.
Definition at line 109 of file filesystem.c.
References False, file_handle::handle, and True.
Referenced by append_to_log_file().
filesystem_write_line()
KAPI b8 filesystem_write_line (file_handle * handle, const char * text)
Writes text to the provided file, appending a '
' afterward.
Parameters
handle A pointer to a file_handle structure.
text The text to be written.
Returns
True if successful; otherwise false.
Definition at line 66 of file filesystem.c.
References False, and file_handle::handle.