Koru Game Engine: engine/src/platform/filesystem.c File Reference
filesystem.c File Reference
Implements a simple cross-platform filesystem abstraction layer. This module allows for basic file operations such as checking for file existence, opening, reading, writing, and closing files.
#include "filesystem.h"
#include "core/logger.h"
#include "core/kmemory.h"
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
Functions
b8 filesystem_exists (const char *path)
b8 filesystem_open (const char *path, file_modes mode, b8 binary, file_handle *out_handle)
void filesystem_close (file_handle *handle)
b8 filesystem_read_line (file_handle *handle, u64 max_length, char **line_buf, u64 *out_line_length)
b8 filesystem_write_line (file_handle *handle, const char *text)
b8 filesystem_read (file_handle *handle, u64 data_size, void *out_data, u64 *out_bytes_read)
b8 filesystem_read_all_bytes (file_handle *handle, u8 **out_bytes, u64 *out_bytes_read)
b8 filesystem_write (file_handle *handle, u64 data_size, const void *data, u64 *out_bytes_written)
Detailed Description
Implements a simple cross-platform filesystem abstraction layer. This module allows for basic file operations such as checking for file existence, opening, reading, writing, and closing files.
Definition in file filesystem.c.
Function Documentation
filesystem_close()
void filesystem_close (file_handle * handle)
Closes the provided handle to a file.
Parameters
handle A pointer to a file_handle structure which holds the handle to be closed.
Definition at line 57 of file filesystem.c.
References False, file_handle::handle, and file_handle::is_valid.
Referenced by create_shader_module(), and load_configuration_file().
filesystem_exists()
b8 filesystem_exists (const char * path)
Checks if a file with the given path exists.
Parameters
path The path of the file to be checked.
Returns
True if exists; otherwise false.
Definition at line 18 of file filesystem.c.
filesystem_open()
b8 filesystem_open (const char * path, file_modes mode, b8 binary, file_handle * out_handle)
Attempt to open file located at path.
Parameters
path The path of the file to be opened.
mode Mode flags for the file when opened (read/write). See file_modes enum in filesystem.h.
binary Indicates if the file should be opened in binary mode.
out_handle A pointer to a file_handle structure which holds the handle information.
Returns
True if opened successfully; otherwise false.
Definition at line 28 of file filesystem.c.
References False, FILE_MODE_READ, FILE_MODE_WRITE, file_handle::handle, file_handle::is_valid, KERROR, and True.
Referenced by create_shader_module(), initialize_logging(), and load_configuration_file().
filesystem_read()
b8 filesystem_read (file_handle * handle, u64 data_size, void * out_data, u64 * out_bytes_read)
Reads up to data_size bytes of data into out_bytes_read. Allocates *out_data, which must be freed by the caller.
Parameters
handle A pointer to a file_handle structure.
data_size The number of bytes to read.
out_data A pointer to a block of memory to be populated by this method.
out_bytes_read A pointer to a number which will be populated with the number of bytes actually read from the file.
Returns
True if successful; otherwise false.
Definition at line 94 of file filesystem.c.
References False, file_handle::handle, and True.
filesystem_read_all_bytes()
b8 filesystem_read_all_bytes (file_handle * handle, u8 ** out_bytes, u64 * out_bytes_read)
Reads up to data_size bytes of data into out_bytes_read. Allocates *out_bytes, which must be freed by the caller.
Parameters
handle A pointer to a file_handle structure.
out_bytes A pointer to a byte array which will be allocated and populated by this method.
out_bytes_read A pointer to a number which will be populated with the number of bytes actually read from the file.
Returns
True if successful; otherwise false.
Definition at line 105 of file filesystem.c.
References False, file_handle::handle, kallocate(), MEMORY_TAG_STRING, and True.
Referenced by create_shader_module().
filesystem_read_line()
b8 filesystem_read_line (file_handle * handle, u64 max_length, char ** line_buf, u64 * out_line_length)
Reads up to a newline or EOF. Allocates *line_buf, which must be freed by the caller.
Parameters
handle A pointer to a file_handle structure.
max_length The maximum length to be read from the line.
line_buf A pointer to a character array populated by this method. Must already be allocated.
out_line_length A pointer to hold the line length read from the file.
Returns
True if successful; otherwise false.
Definition at line 65 of file filesystem.c.
References False, file_handle::handle, and True.
Referenced by load_configuration_file().
filesystem_write()
b8 filesystem_write (file_handle * handle, u64 data_size, const void * data, u64 * out_bytes_written)
Writes provided data to the file.
Parameters
handle A pointer to a file_handle structure.
data_size The size of the data in bytes.
data The data to be written.
out_bytes_written A pointer to a number which will be populated with the number of bytes actually written to the file.
Returns
True if successful; otherwise false.
Definition at line 122 of file filesystem.c.
References False, file_handle::handle, and True.
Referenced by append_to_log_file().
filesystem_write_line()
b8 filesystem_write_line (file_handle * handle, const char * text)
Writes text to the provided file, appending a '
' afterward.
Parameters
handle A pointer to a file_handle structure.
text The text to be written.
Returns
True if successful; otherwise false.
Definition at line 79 of file filesystem.c.
References False, and file_handle::handle.