Koru Game Engine: testbed/src/game.h File Reference
game.h File Reference
Interface for the testbed game implementation.
#include <defines.h>
#include <game_types.h>
#include <math/math_types.h>
Data Structures
struct game_state
Internal game state structure.
Typedefs
typedef struct game_state game_state
Internal game state structure.
Functions
b8 game_initialize (game *game_inst)
Called when the game instance is initialized.
b8 game_update (game *game_inst, f32 delta_time)
Called every frame to update game logic.
b8 game_render (game *game_inst, f32 delta_time)
Called every frame to render the game.
void game_on_resize (game *game_inst, u32 width, u32 height)
Called when the window is resized.
Detailed Description
Interface for the testbed game implementation.
Declares the game lifecycle functions expected by the engine:
game_initialize()
game_update()
game_render()
game_on_resize()
Also defines the game_state struct for storing per-frame data.
Definition in file game.h.
Typedef Documentation
game_state
typedef struct game_state game_state
Internal game state structure.
This struct holds data that persists across frames. Currently only stores delta time, but can be expanded to include player position, world state, etc.
Function Documentation
game_initialize()
b8 game_initialize (game * game_inst)
Called when the game instance is initialized.
Used to set up systems like rendering, input, audio, etc.
Parameters
game_inst A pointer to the current game instance.
Returns
True if initialization was successful; False otherwise.
Called when the game instance is initialized.
Currently just logs a debug message, but should be extended to initialize:
Renderer
Input system
Game world
Parameters
game_inst A pointer to the current game instance.
Returns
True if initialization succeeded; False otherwise.
Definition at line 66 of file game.c.
References game_state::camera_euler, game_state::camera_position, game_state::camera_view_dirty, KDEBUG, mat4_inverse(), mat4_translation(), game::state, True, vec3_zero(), and game_state::view.
Referenced by create_game().
game_on_resize()
void game_on_resize (game * game_inst, u32 width, u32 height)
Called when the window is resized.
Should be used to adjust viewport, projection matrices, UI layout, etc.
Parameters
game_inst A pointer to the current game instance.
width The new width of the window client area.
height The new height of the window client area.
Called when the window is resized.
Currently does nothing, but should be extended to:
Update viewport dimensions
Recalculate aspect ratios
Resize framebuffers or shadow maps
Parameters
game_inst A pointer to the current game instance.
width New width of the window client area.
height New height of the window client area.
Definition at line 198 of file game.c.
Referenced by create_game().
game_render()
b8 game_render (game * game_inst, f32 delta_time)
Called every frame to render the game.
Handles drawing to screen using a renderer or graphics API.
Parameters
game_inst A pointer to the current game instance.
delta_time Time in seconds since the last frame.
Returns
True if rendering succeeded; False on unrecoverable error.
Called every frame to render the game.
Currently a placeholder; this would normally handle:
Drawing geometry
Updating shaders
Rendering UI
Parameters
game_inst A pointer to the current game instance.
delta_time Time in seconds since the last frame.
Returns
True if rendering succeeded; False on unrecoverable error.
Definition at line 182 of file game.c.
References True.
Referenced by create_game().
game_update()
b8 game_update (game * game_inst, f32 delta_time)
Called every frame to update game logic.
Handles input, physics, AI, etc.
Parameters
game_inst A pointer to the current game instance.
delta_time Time in seconds since the last frame.
Returns
True if update succeeded; False to quit the application.
Called every frame to update game logic.
Currently a placeholder; this would normally handle:
Input processing
Game logic updates
Physics simulation
Parameters
game_inst A pointer to the current game instance.
delta_time Time in seconds since the last frame.
Returns
True if update succeeded; False to request application exit.
Definition at line 93 of file game.c.
References camera_pitch(), game_state::camera_position, game_state::camera_view_dirty, camera_yaw(), get_memory_alloc_count(), input_is_key_down(), input_was_key_up(), KDEBUG, mat4_backward(), mat4_forward(), mat4_left(), mat4_right(), recalculate_view_matrix(), renderer_set_view(), game::state, True, vec3_add(), vec3_compare(), vec3_normalize(), vec3_zero(), game_state::view, vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by create_game().