Koru Game Engine: testbed/src/game.c File Reference
game.c File Reference
Implementation of the testbed game logic.
#include "game.h"
#include <core/event.h>
#include "core/input.h"
#include "core/kmemory.h"
#include <core/logger.h>
#include <math/kmath.h>
#include <renderer/renderer_frontend.h>
Functions
void recalculate_view_matrix (game_state *state)
void camera_pitch (game_state *state, f32 amount)
void camera_yaw (game_state *state, f32 amount)
b8 game_initialize (game *game_inst)
Initializes the game instance.
b8 game_update (game *game_inst, f32 delta_time)
Updates the game state each frame.
b8 game_render (game *game_inst, f32 delta_time)
Renders the game each frame.
void game_on_resize (game *game_inst, u32 width, u32 height)
Handles window resize events.
Detailed Description
Implementation of the testbed game logic.
Contains placeholder implementations for the core game functions:
Initialization (game_initialize)
Frame update (game_update)
Rendering (game_render)
Resize handling (game_on_resize)
Can be extended to add real gameplay features.
Definition in file game.c.
Function Documentation
camera_pitch()
void camera_pitch (game_state * state, f32 amount)
Definition at line 41 of file game.c.
References game_state::camera_euler, game_state::camera_view_dirty, deg_to_rad(), KCLAMP, True, and vec3_u::x.
Referenced by game_update().
camera_yaw()
void camera_yaw (game_state * state, f32 amount)
Definition at line 51 of file game.c.
References game_state::camera_euler, game_state::camera_view_dirty, True, and vec3_u::y.
Referenced by game_update().
game_initialize()
b8 game_initialize (game * game_inst)
Initializes the game instance.
Called when the game instance is initialized.
Currently just logs a debug message, but should be extended to initialize:
Renderer
Input system
Game world
Parameters
game_inst A pointer to the current game instance.
Returns
True if initialization succeeded; False otherwise.
Definition at line 67 of file game.c.
References game_state::camera_euler, game_state::camera_position, game_state::camera_view_dirty, KDEBUG, mat4_inverse(), mat4_translation(), game::state, True, vec3_zero(), and game_state::view.
Referenced by create_game().
game_on_resize()
void game_on_resize (game * game_inst, u32 width, u32 height)
Handles window resize events.
Called when the window is resized.
Currently does nothing, but should be extended to:
Update viewport dimensions
Recalculate aspect ratios
Resize framebuffers or shadow maps
Parameters
game_inst A pointer to the current game instance.
width New width of the window client area.
height New height of the window client area.
Definition at line 209 of file game.c.
Referenced by create_game().
game_render()
b8 game_render (game * game_inst, f32 delta_time)
Renders the game each frame.
Called every frame to render the game.
Currently a placeholder; this would normally handle:
Drawing geometry
Updating shaders
Rendering UI
Parameters
game_inst A pointer to the current game instance.
delta_time Time in seconds since the last frame.
Returns
True if rendering succeeded; False on unrecoverable error.
Definition at line 193 of file game.c.
References True.
Referenced by create_game().
game_update()
b8 game_update (game * game_inst, f32 delta_time)
Updates the game state each frame.
Called every frame to update game logic.
Currently a placeholder; this would normally handle:
Input processing
Game logic updates
Physics simulation
Parameters
game_inst A pointer to the current game instance.
delta_time Time in seconds since the last frame.
Returns
True if update succeeded; False to request application exit.
Definition at line 94 of file game.c.
References camera_pitch(), game_state::camera_position, game_state::camera_view_dirty, camera_yaw(), context, EVENT_CODE_DEBUG0, event_fire(), get_memory_alloc_count(), input_is_key_down(), input_is_key_up(), input_was_key_down(), input_was_key_up(), KDEBUG, mat4_backward(), mat4_forward(), mat4_left(), mat4_right(), recalculate_view_matrix(), renderer_set_view(), game::state, True, vec3_add(), vec3_compare(), vec3_normalize(), vec3_zero(), game_state::view, vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by create_game().
recalculate_view_matrix()
void recalculate_view_matrix (game_state * state)
Definition at line 29 of file game.c.
References game_state::camera_euler, game_state::camera_position, game_state::camera_view_dirty, False, mat4_euler_xyz(), mat4_inverse(), mat4_mul(), mat4_translation(), game_state::view, vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by game_update().