Koru Game Engine: engine/src/systems/geometry_system.h File Reference
geometry_system.h File Reference
Geometry management system.
#include "renderer/renderer_types.inl"
Data Structures
struct geometry_system_config
Configuration structure for initializing the geometry system.
struct geometry_config
Configuration structure for creating a geometry.
Macros
#define DEFAULT_GEOMETRY_NAME "default"
Default geometry name used when a requested geometry is not found.
Typedefs
typedef struct geometry_system_config geometry_system_config
typedef struct geometry_config geometry_config
Functions
b8 geometry_system_initialize (u64 *memory_requirement, void *state, geometry_system_config config)
Initializes the geometry system with the provided configuration.
void geometry_system_shutdown (void *state)
Shuts down the geometry system and releases any allocated resources.
geometry * geometry_system_acquire_by_id (u32 id)
Acquires an existing geometry by id.
geometry * geometry_system_acquire_from_config (geometry_config config, b8 auto_release)
Registers and acquires a new geometry using the given config.
void geometry_system_release (geometry *geometry)
Releases a reference to the provided geometry.
geometry * geometry_system_get_default ()
Obtains a pointer to the default geometry.
geometry_config geometry_system_generate_plane_config (f32 width, f32 height, u32 x_segment_count, u32 y_segment_count, f32 tile_x, f32 tile_y, const char *name, const char *material_name)
Generates configuration for plane geometries given the provided parameters. NOTE: vertex and index arrays are dynamically allocated and should be freed upon object disposal. Thus, this should not be considered production code.
Detailed Description
Geometry management system.
This module provides functionality to manage geometry resources within the engine. It supports loading, acquiring, and releasing geometries, as well as automatic cleanup of unused resources.
Usage:
Initialize the geometry system with geometry_system_initialize(), providing configuration options.
Acquire geometries by name using geometry_system_acquire(). If the geometry is not already loaded, it will be created with default properties.
Release geometries using geometry_system_release(). If a geometry was marked for auto-release, it will be freed when no longer in use.
Shutdown the geometry system with geometry_system_shutdown() to free all resources.
Definition in file geometry_system.h.
Macro Definition Documentation
DEFAULT_GEOMETRY_NAME
#define DEFAULT_GEOMETRY_NAME "default"
Default geometry name used when a requested geometry is not found.
Definition at line 25 of file geometry_system.h.
Typedef Documentation
geometry_config
typedef struct geometry_config geometry_config
geometry_system_config
typedef struct geometry_system_config geometry_system_config
Function Documentation
geometry_system_acquire_by_id()
geometry * geometry_system_acquire_by_id (u32 id)
Acquires an existing geometry by id.
Parameters
id The geometry identifier to acquire by.
Returns
A pointer to the acquired geometry or nullptr if failed.
Definition at line 129 of file geometry_system.c.
References geometry_reference::geometry, geometry::id, INVALID_ID, KERROR, geometry_reference::reference_count, geometry_system_state::registered_geometries, and state_ptr.
geometry_system_acquire_from_config()
geometry * geometry_system_acquire_from_config (geometry_config config, b8 auto_release)
Registers and acquires a new geometry using the given config.
Parameters
config The geometry configuration.
auto_release Indicates if the acquired geometry should be unloaded when its reference count reaches 0.
Returns
A pointer to the acquired geometry or nullptr if failed.
Definition at line 140 of file geometry_system.c.
References geometry_reference::auto_release, geometry_system_state::config, create_geometry(), geometry_reference::geometry, geometry::id, INVALID_ID, KERROR, geometry_system_config::max_geometry_count, geometry_reference::reference_count, geometry_system_state::registered_geometries, and state_ptr.
Referenced by application_create().
geometry_system_generate_plane_config()
geometry_config geometry_system_generate_plane_config (f32 width, f32 height, u32 x_segment_count, u32 y_segment_count, f32 tile_x, f32 tile_y, const char * name, const char * material_name)
Generates configuration for plane geometries given the provided parameters. NOTE: vertex and index arrays are dynamically allocated and should be freed upon object disposal. Thus, this should not be considered production code.
Parameters
width The overall width of the plane. Must be non-zero.
height The overall height of the plane. Must be non-zero.
x_segment_count The number of segments along the x-axis in the plane. Must be non-zero.
y_segment_count The number of segments along the y-axis in the plane. Must be non-zero.
tile_x The number of times the texture should tile across the plane on the x-axis. Must be non-zero.
tile_y The number of times the texture should tile across the plane on the y-axis. Must be non-zero.
name The name of the generated geometry.
material_name The name of the material to be used.
Returns
A geometry configuration which can then be fed into geometry_system_acquire_from_config().
Definition at line 280 of file geometry_system.c.
References DEFAULT_GEOMETRY_NAME, DEFAULT_MATERIAL_NAME, GEOMETRY_NAME_MAX_LENGTH, geometry_config::index_count, geometry_config::indices, kallocate(), KWARN, geometry_config::material_name, MATERIAL_NAME_MAX_LENGTH, MEMORY_TAG_ARRAY, geometry_config::name, vertex_3d::position, string_length(), string_ncopy(), vertex_3d::texcoord, geometry_config::vertex_count, geometry_config::vertices, vec2_u::x, vec3_u::x, vec2_u::y, and vec3_u::y.
Referenced by application_create().
geometry_system_get_default()
geometry * geometry_system_get_default ()
Obtains a pointer to the default geometry.
Returns
A pointer to the default geometry.
Definition at line 192 of file geometry_system.c.
References geometry_system_state::default_geometry, KFATAL, and state_ptr.
geometry_system_initialize()
b8 geometry_system_initialize (u64 * memory_requirement, void * state, geometry_system_config config)
Initializes the geometry system with the provided configuration.
Parameters
memory_requirement Pointer to a variable that will be set to the required memory size for the system.
state Pointer to a pre-allocated block of memory for the system state. If nullptr, the function will only calculate the memory requirement.
config Configuration parameters for initializing the system.
Returns
True if initialization was successful, False otherwise.
Definition at line 87 of file geometry_system.c.
References geometry_system_state::config, create_default_geometry(), False, geometry::generation, geometry_reference::geometry, geometry::id, geometry::internal_id, INVALID_ID, KFATAL, geometry_system_config::max_geometry_count, geometry_system_state::registered_geometries, state_ptr, and True.
Referenced by application_create().
geometry_system_release()
void geometry_system_release (geometry * geometry)
Releases a reference to the provided geometry.
Parameters
geometry The geometry to be released.
Definition at line 166 of file geometry_system.c.
References geometry_reference::auto_release, destroy_geometry(), False, geometry_reference::geometry, geometry::id, INVALID_ID, KFATAL, KWARN, geometry_reference::reference_count, geometry_system_state::registered_geometries, and state_ptr.
geometry_system_shutdown()
void geometry_system_shutdown (void * state)
Shuts down the geometry system and releases any allocated resources.
Parameters
state Pointer to the system state to be shut down.
Definition at line 125 of file geometry_system.c.
Referenced by application_run().