Koru Game Engine: engine/src/containers/hashtable.h File Reference
hashtable.h File Reference
Represents a simple hashtable. Members of this structure should not be modified outside the functions associated with it.
#include "defines.h"
Data Structures
struct hashtable
Represents a simple hashtable structure.
Typedefs
typedef struct hashtable hashtable
Functions
KAPI void hashtable_create (u64 element_size, u32 element_count, void *memory, b8 is_pointer_type, hashtable *out_hashtable)
Creates a hashtable and stores it in out_hashtable.
KAPI void hashtable_destroy (hashtable *table)
Destroys the provided hashtable. Does not release memory for pointer types.
KAPI b8 hashtable_set (hashtable *table, const char *name, void *value)
Stores a copy of the data in value in the provided hashtable. Only use for tables which were NOT created with is_pointer_type = true.
KAPI b8 hashtable_set_ptr (hashtable *table, const char *name, void **value)
Stores a pointer as provided in value in the hashtable. Only use for tables which were created with is_pointer_type = true.
KAPI b8 hashtable_get (hashtable *table, const char *name, void *out_value)
Obtains a copy of data present in the hashtable. Only use for tables which were NOT created with is_pointer_type = true.
KAPI b8 hashtable_get_ptr (hashtable *table, const char *name, void **out_value)
Obtains a pointer to data present in the hashtable. Only use for tables which were created with is_pointer_type = true.
KAPI b8 hashtable_fill (hashtable *table, void *value)
Fills all entries in the hashtable with the given value.
Detailed Description
Represents a simple hashtable. Members of this structure should not be modified outside the functions associated with it.
For non-pointer types, table retains a copy of the value. For pointer types, make sure to use the _ptr setter and getter. Table does not take ownership of pointers or associated memory allocations, and should be managed externally.
Usage:
Create a hashtable with hashtable_create(), providing element size, count, memory block, and type info.
Use hashtable_set() and hashtable_get() for non-pointer types.
Use hashtable_set_ptr() and hashtable_get_ptr() for pointer types.
Destroy the hashtable with hashtable_destroy(). Note:
The hashtable does not handle collisions; ensure unique keys or increase element count.
Definition in file hashtable.h.
Typedef Documentation
hashtable
typedef struct hashtable hashtable
Function Documentation
hashtable_create()
KAPI void hashtable_create (u64 element_size, u32 element_count, void * memory, b8 is_pointer_type, hashtable * out_hashtable)
Creates a hashtable and stores it in out_hashtable.
Parameters
element_size The size of each element in bytes.
element_count The maximum number of elements. Cannot be resized.
memory A block of memory to be used. Should be equal in size to element_size * element_count;
is_pointer_type Indicates if this hashtable will hold pointer types.
out_hashtable A pointer to a hashtable in which to hold relevant data.
Definition at line 54 of file hashtable.c.
References hashtable::element_count, hashtable::element_size, hashtable::is_pointer_type, KERROR, kzero_memory(), and hashtable::memory.
Referenced by material_system_initialize(), and texture_system_initialize().
hashtable_destroy()
KAPI void hashtable_destroy (hashtable * table)
Destroys the provided hashtable. Does not release memory for pointer types.
Parameters
table A pointer to the table to be destroyed.
Definition at line 76 of file hashtable.c.
References kzero_memory().
hashtable_fill()
KAPI b8 hashtable_fill (hashtable * table, void * value)
Fills all entries in the hashtable with the given value.
Useful when non-existent names should return some default value. Should not be used with pointer table types.
Parameters
table A pointer to the table filled. Required.
value The value to be filled with. Required.
Returns
True if successful; otherwise false.
Definition at line 158 of file hashtable.c.
References hashtable::element_count, hashtable::element_size, False, hashtable::is_pointer_type, kcopy_memory(), KERROR, KWARN, hashtable::memory, and True.
Referenced by material_system_initialize(), and texture_system_initialize().
hashtable_get()
KAPI b8 hashtable_get (hashtable * table, const char * name, void * out_value)
Obtains a copy of data present in the hashtable. Only use for tables which were NOT created with is_pointer_type = true.
Parameters
table A pointer to the table to retrieved from. Required.
name The name of the entry to retrieved. Required.
value A pointer to store the retrieved value. Required.
Returns
True; or false if a null pointer is passed.
Definition at line 120 of file hashtable.c.
References hashtable::element_count, hashtable::element_size, False, hash_name(), hashtable::is_pointer_type, kcopy_memory(), KERROR, KWARN, hashtable::memory, and True.
Referenced by material_system_acquire_from_config(), material_system_release(), texture_system_acquire(), and texture_system_release().
hashtable_get_ptr()
KAPI b8 hashtable_get_ptr (hashtable * table, const char * name, void ** out_value)
Obtains a pointer to data present in the hashtable. Only use for tables which were created with is_pointer_type = true.
Parameters
table A pointer to the table to retrieved from. Required.
name The name of the entry to retrieved. Required.
value A pointer to store the retrieved value. Required.
Returns
True if retrieved successfully; false if a null pointer is passed or is the retrieved value is 0.
Definition at line 138 of file hashtable.c.
References hashtable::element_count, False, hash_name(), hashtable::is_pointer_type, KERROR, KWARN, and hashtable::memory.
hashtable_set()
KAPI b8 hashtable_set (hashtable * table, const char * name, void * value)
Stores a copy of the data in value in the provided hashtable. Only use for tables which were NOT created with is_pointer_type = true.
Parameters
table A pointer to the table to get from. Required.
name The name of the entry to set. Required.
value The value to be set. Required.
Returns
True, or false if a null pointer is passed.
Definition at line 83 of file hashtable.c.
References hashtable::element_count, hashtable::element_size, False, hash_name(), hashtable::is_pointer_type, kcopy_memory(), KERROR, hashtable::memory, and True.
Referenced by material_system_acquire_from_config(), material_system_release(), texture_system_acquire(), and texture_system_release().
hashtable_set_ptr()
KAPI b8 hashtable_set_ptr (hashtable * table, const char * name, void ** value)
Stores a pointer as provided in value in the hashtable. Only use for tables which were created with is_pointer_type = true.
Parameters
table A pointer to the table to get from. Required.
name The name of the entry to set. Required.
value A pointer value to be set. Can pass 0 to 'unset' an entry.
Returns
True; or false if a null pointer is passed or if the entry is 0.
Definition at line 101 of file hashtable.c.
References hashtable::element_count, False, hash_name(), hashtable::is_pointer_type, KERROR, KWARN, hashtable::memory, and True.