Koru Game Engine: engine/src/containers/hashtable.c File Reference
hashtable.c File Reference
Implementation of a simple hashtable.
#include "hashtable.h"
#include "core/kmemory.h"
#include "core/logger.h"
Functions
u64 hash_name (const char *name, u32 element_count)
Generates a hash value for a given string.
void hashtable_create (u64 element_size, u32 element_count, void *memory, b8 is_pointer_type, hashtable *out_hashtable)
Creates a hashtable and stores it in out_hashtable.
void hashtable_destroy (hashtable *table)
Destroys the provided hashtable. Does not release memory for pointer types.
b8 hashtable_set (hashtable *table, const char *name, void *value)
Stores a copy of the data in value in the provided hashtable. Only use for tables which were NOT created with is_pointer_type = true.
b8 hashtable_set_ptr (hashtable *table, const char *name, void **value)
Stores a pointer as provided in value in the hashtable. Only use for tables which were created with is_pointer_type = true.
b8 hashtable_get (hashtable *table, const char *name, void *out_value)
Obtains a copy of data present in the hashtable. Only use for tables which were NOT created with is_pointer_type = true.
b8 hashtable_get_ptr (hashtable *table, const char *name, void **out_value)
Obtains a pointer to data present in the hashtable. Only use for tables which were created with is_pointer_type = true.
b8 hashtable_fill (hashtable *table, void *value)
Fills all entries in the hashtable with the given value.
Detailed Description
Implementation of a simple hashtable.
This module provides a basic hashtable implementation that supports storing and retrieving both pointer and non-pointer types. It uses a simple hashing function to map string keys to indices in a fixed-size array.
Usage:
Create a hashtable with hashtable_create(), providing element size, count, memory block, and type info.
Use hashtable_set() and hashtable_get() for non-pointer types.
Use hashtable_set_ptr() and hashtable_get_ptr() for pointer types.
Destroy the hashtable with hashtable_destroy().
Note:
The hashtable does not handle collisions; ensure unique keys or increase element count.
Memory management for pointer types is the responsibility of the caller.
Definition in file hashtable.c.
Function Documentation
hash_name()
u64 hash_name (const char * name, u32 element_count)
Generates a hash value for a given string.
Uses a simple hashing algorithm to compute a hash based on character values and a prime multiplier. The resulting hash is then modded by the element_count to ensure it fits within the table size.
Simple hash function for strings, based on djb2 by Dan Bernstein.
Parameters
name The input string to hash.
element_count The size of the hashtable (number of elements).
Returns
A hash value in the range [0, element_count - 1].
Definition at line 37 of file hashtable.c.
Referenced by hashtable_get(), hashtable_get_ptr(), hashtable_set(), and hashtable_set_ptr().
hashtable_create()
void hashtable_create (u64 element_size, u32 element_count, void * memory, b8 is_pointer_type, hashtable * out_hashtable)
Creates a hashtable and stores it in out_hashtable.
Parameters
element_size The size of each element in bytes.
element_count The maximum number of elements. Cannot be resized.
memory A block of memory to be used. Should be equal in size to element_size * element_count;
is_pointer_type Indicates if this hashtable will hold pointer types.
out_hashtable A pointer to a hashtable in which to hold relevant data.
Definition at line 54 of file hashtable.c.
References hashtable::element_count, hashtable::element_size, hashtable::is_pointer_type, KERROR, kzero_memory(), and hashtable::memory.
Referenced by material_system_initialize(), and texture_system_initialize().
hashtable_destroy()
void hashtable_destroy (hashtable * table)
Destroys the provided hashtable. Does not release memory for pointer types.
Parameters
table A pointer to the table to be destroyed.
Definition at line 76 of file hashtable.c.
References kzero_memory().
hashtable_fill()
b8 hashtable_fill (hashtable * table, void * value)
Fills all entries in the hashtable with the given value.
Useful when non-existent names should return some default value. Should not be used with pointer table types.
Parameters
table A pointer to the table filled. Required.
value The value to be filled with. Required.
Returns
True if successful; otherwise false.
Definition at line 158 of file hashtable.c.
References hashtable::element_count, hashtable::element_size, False, hashtable::is_pointer_type, kcopy_memory(), KERROR, KWARN, hashtable::memory, and True.
Referenced by material_system_initialize(), and texture_system_initialize().
hashtable_get()
b8 hashtable_get (hashtable * table, const char * name, void * out_value)
Obtains a copy of data present in the hashtable. Only use for tables which were NOT created with is_pointer_type = true.
Parameters
table A pointer to the table to retrieved from. Required.
name The name of the entry to retrieved. Required.
value A pointer to store the retrieved value. Required.
Returns
True; or false if a null pointer is passed.
Definition at line 120 of file hashtable.c.
References hashtable::element_count, hashtable::element_size, False, hash_name(), hashtable::is_pointer_type, kcopy_memory(), KERROR, KWARN, hashtable::memory, and True.
Referenced by material_system_acquire_from_config(), material_system_release(), texture_system_acquire(), and texture_system_release().
hashtable_get_ptr()
b8 hashtable_get_ptr (hashtable * table, const char * name, void ** out_value)
Obtains a pointer to data present in the hashtable. Only use for tables which were created with is_pointer_type = true.
Parameters
table A pointer to the table to retrieved from. Required.
name The name of the entry to retrieved. Required.
value A pointer to store the retrieved value. Required.
Returns
True if retrieved successfully; false if a null pointer is passed or is the retrieved value is 0.
Definition at line 138 of file hashtable.c.
References hashtable::element_count, False, hash_name(), hashtable::is_pointer_type, KERROR, KWARN, and hashtable::memory.
hashtable_set()
b8 hashtable_set (hashtable * table, const char * name, void * value)
Stores a copy of the data in value in the provided hashtable. Only use for tables which were NOT created with is_pointer_type = true.
Parameters
table A pointer to the table to get from. Required.
name The name of the entry to set. Required.
value The value to be set. Required.
Returns
True, or false if a null pointer is passed.
Definition at line 83 of file hashtable.c.
References hashtable::element_count, hashtable::element_size, False, hash_name(), hashtable::is_pointer_type, kcopy_memory(), KERROR, hashtable::memory, and True.
Referenced by material_system_acquire_from_config(), material_system_release(), texture_system_acquire(), and texture_system_release().
hashtable_set_ptr()
b8 hashtable_set_ptr (hashtable * table, const char * name, void ** value)
Stores a pointer as provided in value in the hashtable. Only use for tables which were created with is_pointer_type = true.
Parameters
table A pointer to the table to get from. Required.
name The name of the entry to set. Required.
value A pointer value to be set. Can pass 0 to 'unset' an entry.
Returns
True; or false if a null pointer is passed or if the entry is 0.
Definition at line 101 of file hashtable.c.
References hashtable::element_count, False, hash_name(), hashtable::is_pointer_type, KERROR, KWARN, hashtable::memory, and True.