Koru Game Engine: engine/src/math/kmath.c File Reference
kmath.c File Reference
Math utilities for the Koru Engine.
#include "kmath.h"
Functions
f32 ksin (f32 x)
Calculates the sine of the given angle in radians.
f32 kcos (f32 x)
Calculates the cosine of the given angle in radians.
f32 ktan (f32 x)
Calculates the tangent of the given angle in radians.
f32 kacos (f32 x)
Calculates the arccosine of x.
f32 ksqrt (f32 x)
Calculates the square root of x.
f32 kabs (f32 x)
Calculates the absolute value of x.
i32 krandom ()
Generates a random integer between 0 and RAND_MAX.
i32 krandom_in_range (i32 min, i32 max)
Generates a random integer within the specified range [min, max].
f32 fkrandom ()
Generates a random floating-point number between 0.0 and 1.0.
f32 fkrandom_in_range (f32 min, f32 max)
Generates a random float within the specified range [min, max].
Variables
static b8 rand_seeded = False
Detailed Description
Math utilities for the Koru Engine.
This module wraps basic math functions from <math.h> to avoid importing it everywhere. It also provides random number generation functionality with optional range support.
All functions are safe to call before full engine initialization, except those that require seeded randomness.
Definition in file kmath.c.
Function Documentation
fkrandom()
f32 fkrandom ()
Generates a random floating-point number between 0.0 and 1.0.
Returns
Random float in [0.0, 1.0]
Definition at line 79 of file kmath.c.
References krandom().
fkrandom_in_range()
f32 fkrandom_in_range (f32 min, f32 max)
Generates a random float within the specified range [min, max].
Parameters
min Minimum value (inclusive)
max Maximum value (inclusive)
Returns
Random float in range
Definition at line 83 of file kmath.c.
References krandom().
kabs()
f32 kabs (f32 x)
Calculates the absolute value of x.
Note that these are here in order to prevent having to import the entire <math.h> everywhere.
Definition at line 51 of file kmath.c.
Referenced by vec2_compare(), vec3_compare(), and vec4_compare().
kacos()
f32 kacos (f32 x)
Calculates the arccosine of x.
Parameters
x Value between -1 and 1
Returns
Angle in radians
Definition at line 38 of file kmath.c.
Referenced by quat_slerp().
kcos()
f32 kcos (f32 x)
Calculates the cosine of the given angle in radians.
Parameters
x Angle in radians
Returns
Cosine of x
Definition at line 30 of file kmath.c.
Referenced by mat4_euler_x(), mat4_euler_y(), mat4_euler_z(), quat_from_axis_angle(), and quat_slerp().
krandom()
i32 krandom ()
Generates a random integer between 0 and RAND_MAX.
Returns
Random integer
Definition at line 55 of file kmath.c.
References platform_get_absolute_time(), rand_seeded, and True.
Referenced by fkrandom(), and fkrandom_in_range().
krandom_in_range()
i32 krandom_in_range (i32 min, i32 max)
Generates a random integer within the specified range [min, max].
Parameters
min Minimum value (inclusive)
max Maximum value (inclusive)
Returns
Random integer in range
Definition at line 63 of file kmath.c.
References platform_get_absolute_time(), rand_seeded, and True.
ksin()
f32 ksin (f32 x)
Calculates the sine of the given angle in radians.
Parameters
x Angle in radians
Returns
Sine of x
Definition at line 26 of file kmath.c.
Referenced by mat4_euler_x(), mat4_euler_y(), mat4_euler_z(), quat_from_axis_angle(), and quat_slerp().
ksqrt()
f32 ksqrt (f32 x)
Calculates the square root of x.
Parameters
x Non-negative value
Returns
Square root of x
Definition at line 42 of file kmath.c.
Referenced by quat_normal(), vec2_length(), vec3_length(), and vec4_length().
ktan()
f32 ktan (f32 x)
Calculates the tangent of the given angle in radians.
Parameters
x Angle in radians
Returns
Tangent of x
Definition at line 34 of file kmath.c.
Referenced by mat4_perspective().
Variable Documentation
rand_seeded
b8 rand_seeded = False static
Note that these are here in order to prevent having to import the entire <math.h> everywhere.
Definition at line 24 of file kmath.c.
Referenced by krandom(), and krandom_in_range().