Koru Game Engine: engine/src/math/kmath.h File Reference
kmath.h File Reference
Core mathematical operations and constants for the Koru engine.
#include "core/kmemory.h"
#include "defines.h"
#include "math_types.h"
Macros
#define K_PI 3.14159265358979323846f
Pi (π) constant.
#define K_PI_2 2.0f * K_PI
2π constant (tau)
#define K_HALF_PI 0.5f * K_PI
π/2 constant
#define K_QUARTER_PI 0.25f * K_PI
π/4 constant
#define K_ONE_OVER_PI 1.0f / K_PI
1/π constant
#define K_ONE_OVER_TWO_PI 1.0f / K_PI_2
1/(2π) constant
#define K_SQRT_TWO 1.41421356237309504880f
Square root of 2.
#define K_SQRT_THREE 1.73205080756887729352f
Square root of 3.
#define K_SQRT_ONE_OVER_TWO 0.70710678118654752440f
Square root of 1/2.
#define K_SQRT_ONE_OVER_THREE 0.57735026918962576450f
Square root of 1/3.
#define K_DEG2RAD_MULTIPLIER K_PI / 180.0f
Multiplier to convert degrees to radians.
#define K_RAD2DEG_MULTIPLIER 180.0f / K_PI
Multiplier to convert radians to degrees.
#define K_SEC_TO_MS_MULTIPLIER 1000.0f
Multiplier to convert seconds to milliseconds.
#define K_MS_TO_SEC_MULTIPLIER 0.001f
Multiplier to convert milliseconds to seconds.
#define K_INFINITY 1e30f
Representation of positive infinity.
#define K_FLOAT_EPSILON 1.192092896e-07f
Smallest positive float where 1.0 + K_FLOAT_EPSILON != 1.0.
Functions
KAPI f32 ksin (f32 x)
Calculates the sine of the given angle in radians.
KAPI f32 kcos (f32 x)
Calculates the cosine of the given angle in radians.
KAPI f32 ktan (f32 x)
Calculates the tangent of the given angle in radians.
KAPI f32 kacos (f32 x)
Calculates the arccosine of x.
KAPI f32 ksqrt (f32 x)
Calculates the square root of x.
KAPI f32 kabs (f32 x)
Calculates the absolute value of x.
KINLINE b8 is_power_of_2 (u64 value)
KAPI i32 krandom ()
Generates a random integer between 0 and RAND_MAX.
KAPI i32 krandom_in_range (i32 min, i32 max)
Generates a random integer within the specified range [min, max].
KAPI f32 fkrandom ()
Generates a random floating-point number between 0.0 and 1.0.
KAPI f32 fkrandom_in_range (f32 min, f32 max)
Generates a random float within the specified range [min, max].
KINLINE vec2 vec2_create (f32 x, f32 y)
Creates and returns a new 2-element vector using the supplied values.
KINLINE vec2 vec2_zero ()
Creates and returns a 2-component vector with all components set to 0.0f.
KINLINE vec2 vec2_one ()
Creates and returns a 2-component vector with all components set to 1.0f.
KINLINE vec2 vec2_up ()
Creates and returns a 2-component vector pointing up (0, 1).
KINLINE vec2 vec2_down ()
Creates and returns a 2-component vector pointing down (0, -1).
KINLINE vec2 vec2_left ()
Creates and returns a 2-component vector pointing left (-1, 0).
KINLINE vec2 vec2_right ()
Creates and returns a 2-component vector pointing right (1, 0).
KINLINE vec2 vec2_add (vec2 vector_0, vec2 vector_1)
Adds vector_1 to vector_0 and returns a copy of the result.
KINLINE vec2 vec2_sub (vec2 vector_0, vec2 vector_1)
Subtracts vector_1 from vector_0 and returns a copy of the result.
KINLINE vec2 vec2_mul (vec2 vector_0, vec2 vector_1)
Multiplies vector_0 by vector_1 and returns a copy of the result.
KINLINE vec2 vec2_div (vec2 vector_0, vec2 vector_1)
Divides vector_0 by vector_1 and returns a copy of the result.
KINLINE f32 vec2_length_squared (vec2 vector)
Returns the squared length of the provided vector.
KINLINE f32 vec2_length (vec2 vector)
Returns the length of the provided vector.
KINLINE void vec2_normalize (vec2 *vector)
Normalizes the provided vector in place to a unit vector.
KINLINE vec2 vec2_normalized (vec2 vector)
Returns a normalized copy of the supplied vector.
KINLINE b8 vec2_compare (vec2 vector_0, vec2 vector_1, f32 tolerance)
Compares all elements of vector_0 and vector_1 and ensures the difference is less than tolerance.
KINLINE f32 vec2_distance (vec2 vector_0, vec2 vector_1)
Returns the distance between vector_0 and vector_1.
KINLINE vec3 vec3_create (f32 x, f32 y, f32 z)
Creates and returns a new 3-element vector using the supplied values.
KINLINE vec3 vec3_from_vec4 (vec4 vector)
Creates a 3D vector from a 4D vector, dropping the w component.
KINLINE vec4 vec3_to_vec4 (vec3 vector, f32 w)
Returns a new vec4 using vector as the x, y and z components and w for w.
KINLINE vec3 vec3_zero ()
Creates and returns a 3-component vector with all components set to 0.0f.
KINLINE vec3 vec3_one ()
Creates and returns a 3-component vector with all components set to 1.0f.
KINLINE vec3 vec3_up ()
Creates and returns a 3-component vector pointing up (0, 1, 0).
KINLINE vec3 vec3_down ()
Creates and returns a 3-component vector pointing down (0, -1, 0).
KINLINE vec3 vec3_left ()
Creates and returns a 3-component vector pointing left (-1, 0, 0).
KINLINE vec3 vec3_right ()
Creates and returns a 3-component vector pointing right (1, 0, 0).
KINLINE vec3 vec3_forward ()
Creates and returns a 3-component vector pointing forward (0, 0, -1).
KINLINE vec3 vec3_back ()
Creates and returns a 3-component vector pointing backward (0, 0, 1).
KINLINE vec3 vec3_add (vec3 vector_0, vec3 vector_1)
Adds vector_1 to vector_0 and returns a copy of the result.
KINLINE vec3 vec3_sub (vec3 vector_0, vec3 vector_1)
Subtracts vector_1 from vector_0 and returns a copy of the result.
KINLINE vec3 vec3_mul (vec3 vector_0, vec3 vector_1)
Multiplies vector_0 by vector_1 and returns a copy of the result.
KINLINE vec3 vec3_mul_scalar (vec3 vector_0, f32 scalar)
Multiplies all elements of vector_0 by scalar and returns a copy of the result.
KINLINE vec3 vec3_div (vec3 vector_0, vec3 vector_1)
Divides vector_0 by vector_1 and returns a copy of the result.
KINLINE f32 vec3_length_squared (vec3 vector)
Returns the squared length of the provided vector.
KINLINE f32 vec3_length (vec3 vector)
Returns the length of the provided vector.
KINLINE void vec3_normalize (vec3 *vector)
Normalizes the provided vector in place to a unit vector.
KINLINE vec3 vec3_normalized (vec3 vector)
Returns a normalized copy of the supplied vector.
KINLINE f32 vec3_dot (vec3 vector_0, vec3 vector_1)
Returns the dot product between the provided vectors. Typically used to calculate the difference in direction.
KINLINE vec3 vec3_cross (vec3 vector_0, vec3 vector_1)
Calculates and returns the cross product of the supplied vectors. The cross product is a new vector which is orthoganal to both provided vectors.
KINLINE const b8 vec3_compare (vec3 vector_0, vec3 vector_1, f32 tolerance)
Compares all elements of vector_0 and vector_1 and ensures the difference is less than tolerance.
KINLINE f32 vec3_distance (vec3 vector_0, vec3 vector_1)
Returns the distance between vector_0 and vector_1.
KINLINE vec4 vec4_create (f32 x, f32 y, f32 z, f32 w)
Creates and returns a new 4-element vector using the supplied values.
KINLINE vec3 vec4_to_vec3 (vec4 vector)
Returns a new vec3 containing the x, y and z components of the supplied vec4, essentially dropping the w component.
KINLINE vec4 vec4_from_vec3 (vec3 vector, f32 w)
Returns a new vec4 using vector as the x, y and z components and w for w.
KINLINE vec4 vec4_zero ()
Creates and returns a 3-component vector with all components set to 0.0f.
KINLINE vec4 vec4_one ()
Creates and returns a 3-component vector with all components set to 1.0f.
KINLINE vec4 vec4_add (vec4 vector_0, vec4 vector_1)
Adds vector_1 to vector_0 and returns a copy of the result.
KINLINE vec4 vec4_sub (vec4 vector_0, vec4 vector_1)
Subtracts vector_1 from vector_0 and returns a copy of the result.
KINLINE vec4 vec4_mul (vec4 vector_0, vec4 vector_1)
Multiplies vector_0 by vector_1 and returns a copy of the result.
KINLINE vec4 vec4_div (vec4 vector_0, vec4 vector_1)
Divides vector_0 by vector_1 and returns a copy of the result.
KINLINE f32 vec4_length_squared (vec4 vector)
Returns the squared length of the provided vector.
KINLINE f32 vec4_length (vec4 vector)
Returns the length of the provided vector.
KINLINE void vec4_normalize (vec4 *vector)
Normalizes the provided vector in place to a unit vector.
KINLINE vec4 vec4_normalized (vec4 vector)
Returns a normalized copy of the supplied vector.
KINLINE f32 vec4_dot_f32 (f32 a0, f32 a1, f32 a2, f32 a3, f32 b0, f32 b1, f32 b2, f32 b3)
Calculates the dot product between two 4D vectors.
KINLINE b8 vec4_compare (vec4 vector_0, vec4 vector_1, f32 tolerance)
Compares all elements of vector_0 and vector_1 with given tolerance.
KINLINE f32 vec4_distance (vec4 vector_0, vec4 vector_1)
Calculates the distance between two 4D vectors.
KINLINE mat4 mat4_identity ()
Creates and returns an identity matrix:
KINLINE mat4 mat4_mul (mat4 matrix_0, mat4 matrix_1)
Returns the result of multiplying matrix_0 and matrix_1.
KINLINE mat4 mat4_orthographic (f32 left, f32 right, f32 bottom, f32 top, f32 near_clip, f32 far_clip)
Creates and returns an orthographic projection matrix. Typically used to render flat or 2D scenes.
KINLINE mat4 mat4_perspective (f32 fov_radians, f32 aspect_ratio, f32 near_clip, f32 far_clip)
Creates and returns a perspective matrix. Typically used to render 3d scenes.
KINLINE mat4 mat4_look_at (vec3 position, vec3 target, vec3 up)
Creates and returns a look-at matrix, or a matrix looking at target from the perspective of position.
KINLINE mat4 mat4_transposed (mat4 matrix)
Returns a transposed copy of the provided matrix (rows->colums)
KINLINE mat4 mat4_inverse (mat4 matrix)
Creates and returns an inverse of the provided matrix.
KINLINE mat4 mat4_translation (vec3 position)
Creates a translation matrix from the given position vector.
KINLINE mat4 mat4_scale (vec3 scale)
Returns a scale matrix using the provided scale.
KINLINE mat4 mat4_euler_x (f32 angle_radians)
Creates a rotation matrix for the X axis using the given angle in radians.
KINLINE mat4 mat4_euler_y (f32 angle_radians)
Creates a rotation matrix for the Y axis using the given angle in radians.
KINLINE mat4 mat4_euler_z (f32 angle_radians)
Creates a rotation matrix for the Z axis using the given angle in radians.
KINLINE mat4 mat4_euler_xyz (f32 x_radians, f32 y_radians, f32 z_radians)
Creates a rotation matrix for all three axes (XYZ) using the given angles in radians.
KINLINE vec3 mat4_forward (mat4 matrix)
Returns a forward vector relative to the provided matrix.
KINLINE vec3 mat4_backward (mat4 matrix)
Returns a backward vector relative to the provided matrix.
KINLINE vec3 mat4_up (mat4 matrix)
Returns a upward vector relative to the provided matrix.
KINLINE vec3 mat4_down (mat4 matrix)
Returns a downward vector relative to the provided matrix.
KINLINE vec3 mat4_left (mat4 matrix)
Returns a left vector relative to the provided matrix.
KINLINE vec3 mat4_right (mat4 matrix)
Returns a right vector relative to the provided matrix.
KINLINE quat quat_identity ()
Returns an identity quaternion (no rotation).
KINLINE f32 quat_normal (quat q)
Calculates the norm (length) of the quaternion.
KINLINE quat quat_normalize (quat q)
Normalizes the given quaternion.
KINLINE quat quat_conjugate (quat q)
Returns the conjugate of the given quaternion.
KINLINE quat quat_inverse (quat q)
Returns the inverse of the given quaternion.
KINLINE quat quat_mul (quat q_0, quat q_1)
Multiplies two quaternions together.
KINLINE f32 quat_dot (quat q_0, quat q_1)
Calculates the dot product of two quaternions.
KINLINE mat4 quat_to_mat4 (quat q)
Converts a quaternion to a 4x4 rotation matrix.
KINLINE mat4 quat_to_rotation_matrix (quat q, vec3 center)
Creates a rotation matrix from a quaternion with a specified center point.
KINLINE quat quat_from_axis_angle (vec3 axis, f32 angle, b8 normalize)
Creates a quaternion from an axis-angle representation.
KINLINE quat quat_slerp (quat q_0, quat q_1, f32 percentage)
Performs spherical linear interpolation (SLERP) between two quaternions.
KINLINE f32 deg_to_rad (f32 degrees)
Converts provided degrees to radians.
KINLINE f32 rad_to_deg (f32 radians)
Converts provided radians to degrees.
Detailed Description
Core mathematical operations and constants for the Koru engine.
Provides:
Common mathematical constants
Vector operations (2D, 3D, 4D)
Basic trigonometric functions
Random number generation
Utility functions for game math
Definition in file kmath.h.
Macro Definition Documentation
K_DEG2RAD_MULTIPLIER
#define K_DEG2RAD_MULTIPLIER K_PI / 180.0f
Multiplier to convert degrees to radians.
Definition at line 54 of file kmath.h.
K_FLOAT_EPSILON
#define K_FLOAT_EPSILON 1.192092896e-07f
Smallest positive float where 1.0 + K_FLOAT_EPSILON != 1.0.
Definition at line 69 of file kmath.h.
K_HALF_PI
#define K_HALF_PI 0.5f * K_PI
π/2 constant
Definition at line 30 of file kmath.h.
K_INFINITY
#define K_INFINITY 1e30f
Representation of positive infinity.
Definition at line 66 of file kmath.h.
K_MS_TO_SEC_MULTIPLIER
#define K_MS_TO_SEC_MULTIPLIER 0.001f
Multiplier to convert milliseconds to seconds.
Definition at line 63 of file kmath.h.
K_ONE_OVER_PI
#define K_ONE_OVER_PI 1.0f / K_PI
1/π constant
Definition at line 36 of file kmath.h.
K_ONE_OVER_TWO_PI
#define K_ONE_OVER_TWO_PI 1.0f / K_PI_2
1/(2π) constant
Definition at line 39 of file kmath.h.
K_PI
#define K_PI 3.14159265358979323846f
Pi (π) constant.
Definition at line 24 of file kmath.h.
K_PI_2
#define K_PI_2 2.0f * K_PI
2π constant (tau)
Definition at line 27 of file kmath.h.
K_QUARTER_PI
#define K_QUARTER_PI 0.25f * K_PI
π/4 constant
Definition at line 33 of file kmath.h.
K_RAD2DEG_MULTIPLIER
#define K_RAD2DEG_MULTIPLIER 180.0f / K_PI
Multiplier to convert radians to degrees.
Definition at line 57 of file kmath.h.
K_SEC_TO_MS_MULTIPLIER
#define K_SEC_TO_MS_MULTIPLIER 1000.0f
Multiplier to convert seconds to milliseconds.
Definition at line 60 of file kmath.h.
K_SQRT_ONE_OVER_THREE
#define K_SQRT_ONE_OVER_THREE 0.57735026918962576450f
Square root of 1/3.
Definition at line 51 of file kmath.h.
K_SQRT_ONE_OVER_TWO
#define K_SQRT_ONE_OVER_TWO 0.70710678118654752440f
Square root of 1/2.
Definition at line 48 of file kmath.h.
K_SQRT_THREE
#define K_SQRT_THREE 1.73205080756887729352f
Square root of 3.
Definition at line 45 of file kmath.h.
K_SQRT_TWO
#define K_SQRT_TWO 1.41421356237309504880f
Square root of 2.
Definition at line 42 of file kmath.h.
Function Documentation
deg_to_rad()
KINLINE f32 deg_to_rad (f32 degrees)
Converts provided degrees to radians.
Parameters
degrees The degrees to be converted.
Returns
The amount in radians.
Definition at line 1537 of file kmath.h.
References K_DEG2RAD_MULTIPLIER.
Referenced by camera_pitch(), renderer_on_resized(), and renderer_system_initialize().
fkrandom()
KAPI f32 fkrandom ()
Generates a random floating-point number between 0.0 and 1.0.
Returns
Random float in [0.0, 1.0]
Definition at line 79 of file kmath.c.
References krandom().
fkrandom_in_range()
KAPI f32 fkrandom_in_range (f32 min, f32 max)
Generates a random float within the specified range [min, max].
Parameters
min Minimum value (inclusive)
max Maximum value (inclusive)
Returns
Random float in range
Definition at line 83 of file kmath.c.
References krandom().
is_power_of_2()
KINLINE b8 is_power_of_2 (u64 value)
Indicates if the value is a power of 2. 0 is considered not a power of 2.
Parameters
value The value to be interpreted.
Returns
True if a power of 2, otherwise False.
Definition at line 122 of file kmath.h.
kabs()
KAPI f32 kabs (f32 x)
Calculates the absolute value of x.
Parameters
x Input value
Returns
Absolute value of x
Note that these are here in order to prevent having to import the entire <math.h> everywhere.
Definition at line 51 of file kmath.c.
Referenced by vec2_compare(), vec3_compare(), and vec4_compare().
kacos()
KAPI f32 kacos (f32 x)
Calculates the arccosine of x.
Parameters
x Value between -1 and 1
Returns
Angle in radians
Definition at line 38 of file kmath.c.
Referenced by quat_slerp().
kcos()
KAPI f32 kcos (f32 x)
Calculates the cosine of the given angle in radians.
Parameters
x Angle in radians
Returns
Cosine of x
Definition at line 30 of file kmath.c.
Referenced by mat4_euler_x(), mat4_euler_y(), mat4_euler_z(), quat_from_axis_angle(), and quat_slerp().
krandom()
KAPI i32 krandom ()
Generates a random integer between 0 and RAND_MAX.
Returns
Random integer
Definition at line 55 of file kmath.c.
References platform_get_absolute_time(), rand_seeded, and True.
Referenced by fkrandom(), and fkrandom_in_range().
krandom_in_range()
KAPI i32 krandom_in_range (i32 min, i32 max)
Generates a random integer within the specified range [min, max].
Parameters
min Minimum value (inclusive)
max Maximum value (inclusive)
Returns
Random integer in range
Definition at line 63 of file kmath.c.
References platform_get_absolute_time(), rand_seeded, and True.
ksin()
KAPI f32 ksin (f32 x)
Calculates the sine of the given angle in radians.
Parameters
x Angle in radians
Returns
Sine of x
Definition at line 26 of file kmath.c.
Referenced by mat4_euler_x(), mat4_euler_y(), mat4_euler_z(), quat_from_axis_angle(), quat_slerp(), and vulkan_object_shader_update_object().
ksqrt()
KAPI f32 ksqrt (f32 x)
Calculates the square root of x.
Parameters
x Non-negative value
Returns
Square root of x
Definition at line 42 of file kmath.c.
Referenced by quat_normal(), vec2_length(), vec3_length(), and vec4_length().
ktan()
KAPI f32 ktan (f32 x)
Calculates the tangent of the given angle in radians.
Parameters
x Angle in radians
Returns
Tangent of x
Definition at line 34 of file kmath.c.
Referenced by mat4_perspective().
mat4_backward()
KINLINE vec3 mat4_backward (mat4 matrix)
Returns a backward vector relative to the provided matrix.
Parameters
matrix The matrix from which to base the vector.
Returns
A 3-component directional vector.
Definition at line 1206 of file kmath.h.
References mat4_u::data, vec3_normalize(), vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by game_update().
mat4_down()
KINLINE vec3 mat4_down (mat4 matrix)
Returns a downward vector relative to the provided matrix.
Parameters
matrix The matrix from which to base the vector.
Returns
A 3-component directional vector.
Definition at line 1236 of file kmath.h.
References mat4_u::data, vec3_normalize(), vec3_u::x, vec3_u::y, and vec3_u::z.
mat4_euler_x()
KINLINE mat4 mat4_euler_x (f32 angle_radians)
Creates a rotation matrix for the X axis using the given angle in radians.
Parameters
angle_radians The angle of rotation in radians.
Returns
A new rotation matrix.
Definition at line 1119 of file kmath.h.
References mat4_u::data, kcos(), ksin(), and mat4_identity().
Referenced by mat4_euler_xyz().
mat4_euler_xyz()
KINLINE mat4 mat4_euler_xyz (f32 x_radians, f32 y_radians, f32 z_radians)
Creates a rotation matrix for all three axes (XYZ) using the given angles in radians.
Parameters
x_radians The angle of rotation around X axis in radians.
y_radians The angle of rotation around Y axis in radians.
z_radians The angle of rotation around Z axis in radians.
Returns
A new rotation matrix.
Definition at line 1176 of file kmath.h.
References mat4_euler_x(), mat4_euler_y(), mat4_euler_z(), and mat4_mul().
Referenced by recalculate_view_matrix().
mat4_euler_y()
KINLINE mat4 mat4_euler_y (f32 angle_radians)
Creates a rotation matrix for the Y axis using the given angle in radians.
Parameters
angle_radians The angle of rotation in radians.
Returns
A new rotation matrix.
Definition at line 1137 of file kmath.h.
References mat4_u::data, kcos(), ksin(), and mat4_identity().
Referenced by mat4_euler_xyz().
mat4_euler_z()
KINLINE mat4 mat4_euler_z (f32 angle_radians)
Creates a rotation matrix for the Z axis using the given angle in radians.
Parameters
angle_radians The angle of rotation in radians.
Returns
A new rotation matrix.
Definition at line 1155 of file kmath.h.
References mat4_u::data, kcos(), ksin(), and mat4_identity().
Referenced by mat4_euler_xyz().
mat4_forward()
KINLINE vec3 mat4_forward (mat4 matrix)
Returns a forward vector relative to the provided matrix.
Parameters
matrix The matrix from which to base the vector.
Returns
A 3-component directional vector.
Definition at line 1191 of file kmath.h.
References mat4_u::data, vec3_normalize(), vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by game_update().
mat4_identity()
KINLINE mat4 mat4_identity ()
Creates and returns an identity matrix:
{
  {1, 0, 0, 0},
  {0, 1, 0, 0},
  {0, 0, 1, 0},
  {0, 0, 0, 1}
}
Returns
A new identity matrix
Definition at line 866 of file kmath.h.
References mat4_u::data, and kzero_memory().
Referenced by mat4_euler_x(), mat4_euler_y(), mat4_euler_z(), mat4_mul(), mat4_orthographic(), mat4_scale(), mat4_translation(), mat4_transposed(), and quat_to_mat4().
mat4_inverse()
KINLINE mat4 mat4_inverse (mat4 matrix)
Creates and returns an inverse of the provided matrix.
Parameters
matrix The matrix to be inverted.
Returns
A inverted copy of the provided matrix.
Definition at line 1027 of file kmath.h.
References mat4_u::data.
Referenced by game_initialize(), recalculate_view_matrix(), and renderer_system_initialize().
mat4_left()
KINLINE vec3 mat4_left (mat4 matrix)
Returns a left vector relative to the provided matrix.
Parameters
matrix The matrix from which to base the vector.
Returns
A 3-component directional vector.
Definition at line 1251 of file kmath.h.
References mat4_u::data, vec3_normalize(), vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by game_update().
mat4_look_at()
KINLINE mat4 mat4_look_at (vec3 position, vec3 target, vec3 up)
Creates and returns a look-at matrix, or a matrix looking at target from the perspective of position.
Parameters
position The position of the matrix.
target The position to "look at".
up The up vector.
Returns
A matrix looking at target from the perspective of position.
Definition at line 963 of file kmath.h.
References mat4_u::data, vec3_cross(), vec3_dot(), vec3_normalized(), vec3_u::x, vec3_u::y, and vec3_u::z.
mat4_mul()
KINLINE mat4 mat4_mul (mat4 matrix_0, mat4 matrix_1)
Returns the result of multiplying matrix_0 and matrix_1.
Parameters
matrix_0 The first matrix to be multiplied.
matrix_1 The second matrix to be multiplied.
Returns
The result of the matrix multiplication.
Definition at line 883 of file kmath.h.
References mat4_u::data, and mat4_identity().
Referenced by mat4_euler_xyz(), and recalculate_view_matrix().
mat4_orthographic()
KINLINE mat4 mat4_orthographic (f32 left, f32 right, f32 bottom, f32 top, f32 near_clip, f32 far_clip)
Creates and returns an orthographic projection matrix. Typically used to render flat or 2D scenes.
Parameters
left The left side of the view frustum.
right The right side of the view frustum.
bottom The bottom side of the view frustum.
top The top side of the view frustum.
near_clip The near clipping plane distance.
far_clip The far clipping plane distance.
Returns
A new orthographic projection matrix.
Definition at line 916 of file kmath.h.
References mat4_u::data, and mat4_identity().
mat4_perspective()
KINLINE mat4 mat4_perspective (f32 fov_radians, f32 aspect_ratio, f32 near_clip, f32 far_clip)
Creates and returns a perspective matrix. Typically used to render 3d scenes.
Parameters
fov_radians The field of view in radians.
aspect_ratio The aspect ratio.
near_clip The near clipping plane distance.
far_clip The far clipping plane distance.
Returns
A new perspective matrix.
Definition at line 942 of file kmath.h.
References mat4_u::data, ktan(), and kzero_memory().
Referenced by renderer_on_resized(), and renderer_system_initialize().
mat4_right()
KINLINE vec3 mat4_right (mat4 matrix)
Returns a right vector relative to the provided matrix.
Parameters
matrix The matrix from which to base the vector.
Returns
A 3-component directional vector.
Definition at line 1266 of file kmath.h.
References mat4_u::data, vec3_normalize(), vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by game_update().
mat4_scale()
KINLINE mat4 mat4_scale (vec3 scale)
Returns a scale matrix using the provided scale.
Parameters
scale The 3-component scale.
Returns
A scale matrix.
Definition at line 1105 of file kmath.h.
References mat4_u::data, mat4_identity(), vec3_u::x, vec3_u::y, and vec3_u::z.
mat4_translation()
KINLINE mat4 mat4_translation (vec3 position)
Creates a translation matrix from the given position vector.
Parameters
position The translation position.
Returns
A new translation matrix.
Definition at line 1091 of file kmath.h.
References mat4_u::data, mat4_identity(), vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by game_initialize(), recalculate_view_matrix(), renderer_draw_frame(), and renderer_system_initialize().
mat4_transposed()
KINLINE mat4 mat4_transposed (mat4 matrix)
Returns a transposed copy of the provided matrix (rows->colums)
Parameters
matrix The matrix to be transposed.
Returns
A transposed copy of of the provided matrix.
Definition at line 1000 of file kmath.h.
References mat4_u::data, and mat4_identity().
mat4_up()
KINLINE vec3 mat4_up (mat4 matrix)
Returns a upward vector relative to the provided matrix.
Parameters
matrix The matrix from which to base the vector.
Returns
A 3-component directional vector.
Definition at line 1221 of file kmath.h.
References mat4_u::data, vec3_normalize(), vec3_u::x, vec3_u::y, and vec3_u::z.
quat_conjugate()
KINLINE quat quat_conjugate (quat q)
Returns the conjugate of the given quaternion.
Parameters
q The quaternion to get conjugate of.
Returns
The conjugate quaternion.
Definition at line 1324 of file kmath.h.
References vec4_u::w, vec4_u::x, vec4_u::y, and vec4_u::z.
Referenced by quat_inverse().
quat_dot()
KINLINE f32 quat_dot (quat q_0, quat q_1)
Calculates the dot product of two quaternions.
Parameters
q_0 The first quaternion.
q_1 The second quaternion.
Returns
The dot product of the two quaternions.
Definition at line 1382 of file kmath.h.
References vec4_u::w, vec4_u::x, vec4_u::y, and vec4_u::z.
Referenced by quat_slerp().
quat_from_axis_angle()
KINLINE quat quat_from_axis_angle (vec3 axis, f32 angle, b8 normalize)
Creates a quaternion from an axis-angle representation.
Parameters
axis The axis of rotation.
angle The angle of rotation in radians.
normalize Whether to normalize the resulting quaternion.
Returns
A new quaternion representing the rotation.
Definition at line 1459 of file kmath.h.
References kcos(), ksin(), quat_normalize(), vec3_u::x, vec3_u::y, and vec3_u::z.
quat_identity()
KINLINE quat quat_identity ()
Returns an identity quaternion (no rotation).
Returns
An identity quaternion.
Definition at line 1284 of file kmath.h.
quat_inverse()
KINLINE quat quat_inverse (quat q)
Returns the inverse of the given quaternion.
Parameters
q The quaternion to invert.
Returns
The inverse quaternion.
Definition at line 1338 of file kmath.h.
References quat_conjugate(), and quat_normalize().
quat_mul()
KINLINE quat quat_mul (quat q_0, quat q_1)
Multiplies two quaternions together.
Parameters
q_0 The first quaternion.
q_1 The second quaternion.
Returns
The product of the two quaternions.
Definition at line 1349 of file kmath.h.
References vec4_u::w, vec4_u::x, vec4_u::y, and vec4_u::z.
quat_normal()
KINLINE f32 quat_normal (quat q)
Calculates the norm (length) of the quaternion.
Parameters
q The quaternion to calculate norm for.
Returns
The norm of the quaternion.
Definition at line 1294 of file kmath.h.
References ksqrt(), vec4_u::w, vec4_u::x, vec4_u::y, and vec4_u::z.
Referenced by quat_normalize().
quat_normalize()
KINLINE quat quat_normalize (quat q)
Normalizes the given quaternion.
Parameters
q The quaternion to normalize.
Returns
A normalized copy of the quaternion.
Definition at line 1308 of file kmath.h.
References quat_normal(), vec4_u::w, vec4_u::x, vec4_u::y, and vec4_u::z.
Referenced by quat_from_axis_angle(), quat_inverse(), quat_slerp(), and quat_to_mat4().
quat_slerp()
KINLINE quat quat_slerp (quat q_0, quat q_1, f32 percentage)
Performs spherical linear interpolation (SLERP) between two quaternions.
Parameters
q_0 The starting quaternion.
q_1 The ending quaternion.
percentage The interpolation percentage (0.0 to 1.0).
Returns
The interpolated quaternion between q_0 and q_1.
Definition at line 1479 of file kmath.h.
References kacos(), kcos(), ksin(), quat_dot(), quat_normalize(), vec4_u::w, vec4_u::x, vec4_u::y, and vec4_u::z.
quat_to_mat4()
KINLINE mat4 quat_to_mat4 (quat q)
Converts a quaternion to a 4x4 rotation matrix.
Parameters
q The quaternion to convert.
Returns
A 4x4 rotation matrix representing the same rotation as the quaternion.
Definition at line 1395 of file kmath.h.
References mat4_u::data, mat4_identity(), quat_normalize(), vec4_u::w, vec4_u::x, vec4_u::y, and vec4_u::z.
quat_to_rotation_matrix()
KINLINE mat4 quat_to_rotation_matrix (quat q, vec3 center)
Creates a rotation matrix from a quaternion with a specified center point.
Parameters
q The quaternion representing the rotation.
center The center point around which to rotate.
Returns
A 4x4 transformation matrix combining rotation and translation.
Definition at line 1425 of file kmath.h.
References mat4_u::data, vec4_u::w, vec3_u::x, vec4_u::x, vec3_u::y, vec4_u::y, vec3_u::z, and vec4_u::z.
rad_to_deg()
KINLINE f32 rad_to_deg (f32 radians)
Converts provided radians to degrees.
Parameters
radians The radians to be converted.
Returns
The amount in degrees.
Definition at line 1547 of file kmath.h.
References K_RAD2DEG_MULTIPLIER.
vec2_add()
KINLINE vec2 vec2_add (vec2 vector_0, vec2 vector_1)
Adds vector_1 to vector_0 and returns a copy of the result.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The resulting vector.
Definition at line 221 of file kmath.h.
References vec2_u::x, and vec2_u::y.
vec2_compare()
KINLINE b8 vec2_compare (vec2 vector_0, vec2 vector_1, f32 tolerance)
Compares all elements of vector_0 and vector_1 and ensures the difference is less than tolerance.
Parameters
vector_0 The first vector.
vector_1 The second vector.
tolerance The difference tolerance. Typically K_FLOAT_EPSILON or similar.
Returns
True if within tolerance; otherwise false.
Definition at line 317 of file kmath.h.
References False, kabs(), True, vec2_u::x, and vec2_u::y.
vec2_create()
KINLINE vec2 vec2_create (f32 x, f32 y)
Creates and returns a new 2-element vector using the supplied values.
Parameters
x The x value.
y The y value.
Returns
A new 2-element vector.
Definition at line 165 of file kmath.h.
References vec2_u::x, and vec2_u::y.
vec2_distance()
KINLINE f32 vec2_distance (vec2 vector_0, vec2 vector_1)
Returns the distance between vector_0 and vector_1.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The distance between vector_0 and vector_1.
Definition at line 336 of file kmath.h.
References vec2_length(), vec2_u::x, and vec2_u::y.
vec2_div()
KINLINE vec2 vec2_div (vec2 vector_0, vec2 vector_1)
Divides vector_0 by vector_1 and returns a copy of the result.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The resulting vector.
Definition at line 260 of file kmath.h.
References vec2_u::x, and vec2_u::y.
vec2_down()
KINLINE vec2 vec2_down ()
Creates and returns a 2-component vector pointing down (0, -1).
Definition at line 196 of file kmath.h.
vec2_left()
KINLINE vec2 vec2_left ()
Creates and returns a 2-component vector pointing left (-1, 0).
Definition at line 203 of file kmath.h.
vec2_length()
KINLINE f32 vec2_length (vec2 vector)
Returns the length of the provided vector.
Parameters
vector The vector to retrieve the length of.
Returns
The length.
Definition at line 282 of file kmath.h.
References ksqrt(), and vec2_length_squared().
Referenced by vec2_distance(), and vec2_normalize().
vec2_length_squared()
KINLINE f32 vec2_length_squared (vec2 vector)
Returns the squared length of the provided vector.
Parameters
vector The vector to retrieve the squared length of.
Returns
The squared length.
Definition at line 272 of file kmath.h.
References vec2_u::x, and vec2_u::y.
Referenced by vec2_length().
vec2_mul()
KINLINE vec2 vec2_mul (vec2 vector_0, vec2 vector_1)
Multiplies vector_0 by vector_1 and returns a copy of the result.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The resulting vector.
Definition at line 247 of file kmath.h.
References vec2_u::x, and vec2_u::y.
vec2_normalize()
KINLINE void vec2_normalize (vec2 * vector)
Normalizes the provided vector in place to a unit vector.
Parameters
vector A pointer to the vector to be normalized.
Definition at line 291 of file kmath.h.
References vec2_length(), vec2_u::x, and vec2_u::y.
Referenced by vec2_normalized().
vec2_normalized()
KINLINE vec2 vec2_normalized (vec2 vector)
Returns a normalized copy of the supplied vector.
Parameters
vector The vector to be normalized.
Returns
A normalized copy of the supplied vector
Definition at line 303 of file kmath.h.
References vec2_normalize().
vec2_one()
KINLINE vec2 vec2_one ()
Creates and returns a 2-component vector with all components set to 1.0f.
Definition at line 182 of file kmath.h.
vec2_right()
KINLINE vec2 vec2_right ()
Creates and returns a 2-component vector pointing right (1, 0).
Definition at line 210 of file kmath.h.
vec2_sub()
KINLINE vec2 vec2_sub (vec2 vector_0, vec2 vector_1)
Subtracts vector_1 from vector_0 and returns a copy of the result.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The resulting vector.
Definition at line 234 of file kmath.h.
References vec2_u::x, and vec2_u::y.
vec2_up()
KINLINE vec2 vec2_up ()
Creates and returns a 2-component vector pointing up (0, 1).
Definition at line 189 of file kmath.h.
vec2_zero()
KINLINE vec2 vec2_zero ()
Creates and returns a 2-component vector with all components set to 0.0f.
Definition at line 175 of file kmath.h.
vec3_add()
KINLINE vec3 vec3_add (vec3 vector_0, vec3 vector_1)
Adds vector_1 to vector_0 and returns a copy of the result.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The resulting vector.
Definition at line 443 of file kmath.h.
References vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by game_update().
vec3_back()
KINLINE vec3 vec3_back ()
Creates and returns a 3-component vector pointing backward (0, 0, 1).
Definition at line 432 of file kmath.h.
vec3_compare()
KINLINE const b8 vec3_compare (vec3 vector_0, vec3 vector_1, f32 tolerance)
Compares all elements of vector_0 and vector_1 and ensures the difference is less than tolerance.
Parameters
vector_0 The first vector.
vector_1 The second vector.
tolerance The difference tolerance. Typically K_FLOAT_EPSILON or similar.
Returns
True if within tolerance; otherwise false.
Definition at line 589 of file kmath.h.
References False, kabs(), True, vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by game_update().
vec3_create()
KINLINE vec3 vec3_create (f32 x, f32 y, f32 z)
Creates and returns a new 3-element vector using the supplied values.
Parameters
x The x value.
y The y value.
z The z value.
Returns
A new 3-element vector.
Definition at line 355 of file kmath.h.
vec3_cross()
KINLINE vec3 vec3_cross (vec3 vector_0, vec3 vector_1)
Calculates and returns the cross product of the supplied vectors. The cross product is a new vector which is orthoganal to both provided vectors.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The cross product.
Definition at line 573 of file kmath.h.
References vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by mat4_look_at().
vec3_distance()
KINLINE f32 vec3_distance (vec3 vector_0, vec3 vector_1)
Returns the distance between vector_0 and vector_1.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The distance between vector_0 and vector_1.
Definition at line 612 of file kmath.h.
References vec3_length(), vec3_u::x, vec3_u::y, and vec3_u::z.
vec3_div()
KINLINE vec3 vec3_div (vec3 vector_0, vec3 vector_1)
Divides vector_0 by vector_1 and returns a copy of the result.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The resulting vector.
Definition at line 499 of file kmath.h.
References vec3_u::x, vec3_u::y, and vec3_u::z.
vec3_dot()
KINLINE f32 vec3_dot (vec3 vector_0, vec3 vector_1)
Returns the dot product between the provided vectors. Typically used to calculate the difference in direction.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The dot product.
Definition at line 557 of file kmath.h.
References vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by mat4_look_at().
vec3_down()
KINLINE vec3 vec3_down ()
Creates and returns a 3-component vector pointing down (0, -1, 0).
Definition at line 404 of file kmath.h.
vec3_forward()
KINLINE vec3 vec3_forward ()
Creates and returns a 3-component vector pointing forward (0, 0, -1).
Definition at line 425 of file kmath.h.
vec3_from_vec4()
KINLINE vec3 vec3_from_vec4 (vec4 vector)
Creates a 3D vector from a 4D vector, dropping the w component.
Parameters
vector The 4-component vector to extract from.
Returns
A new vec3
Definition at line 365 of file kmath.h.
References vec4_u::x, vec4_u::y, and vec4_u::z.
vec3_left()
KINLINE vec3 vec3_left ()
Creates and returns a 3-component vector pointing left (-1, 0, 0).
Definition at line 411 of file kmath.h.
vec3_length()
KINLINE f32 vec3_length (vec3 vector)
Returns the length of the provided vector.
Parameters
vector The vector to retrieve the length of.
Returns
The length.
Definition at line 522 of file kmath.h.
References ksqrt(), and vec3_length_squared().
Referenced by vec3_distance(), and vec3_normalize().
vec3_length_squared()
KINLINE f32 vec3_length_squared (vec3 vector)
Returns the squared length of the provided vector.
Parameters
vector The vector to retrieve the squared length of.
Returns
The squared length.
Definition at line 512 of file kmath.h.
References vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by vec3_length().
vec3_mul()
KINLINE vec3 vec3_mul (vec3 vector_0, vec3 vector_1)
Multiplies vector_0 by vector_1 and returns a copy of the result.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The resulting vector.
Definition at line 471 of file kmath.h.
References vec3_u::x, vec3_u::y, and vec3_u::z.
vec3_mul_scalar()
KINLINE vec3 vec3_mul_scalar (vec3 vector_0, f32 scalar)
Multiplies all elements of vector_0 by scalar and returns a copy of the result.
Parameters
vector_0 The vector to be multiplied.
scalar The scalar value.
Returns
A copy of the scaled vector.
Definition at line 485 of file kmath.h.
References vec3_u::x, vec3_u::y, and vec3_u::z.
vec3_normalize()
KINLINE void vec3_normalize (vec3 * vector)
Normalizes the provided vector in place to a unit vector.
Parameters
vector A pointer to the vector to be normalized.
Definition at line 531 of file kmath.h.
References vec3_length(), vec3_u::x, vec3_u::y, and vec3_u::z.
Referenced by game_update(), mat4_backward(), mat4_down(), mat4_forward(), mat4_left(), mat4_right(), mat4_up(), and vec3_normalized().
vec3_normalized()
KINLINE vec3 vec3_normalized (vec3 vector)
Returns a normalized copy of the supplied vector.
Parameters
vector The vector to be normalized.
Returns
A normalized copy of the supplied vector
Definition at line 544 of file kmath.h.
References vec3_normalize().
Referenced by mat4_look_at().
vec3_one()
KINLINE vec3 vec3_one ()
Creates and returns a 3-component vector with all components set to 1.0f.
Definition at line 390 of file kmath.h.
vec3_right()
KINLINE vec3 vec3_right ()
Creates and returns a 3-component vector pointing right (1, 0, 0).
Definition at line 418 of file kmath.h.
vec3_sub()
KINLINE vec3 vec3_sub (vec3 vector_0, vec3 vector_1)
Subtracts vector_1 from vector_0 and returns a copy of the result.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The resulting vector.
Definition at line 457 of file kmath.h.
References vec3_u::x, vec3_u::y, and vec3_u::z.
vec3_to_vec4()
KINLINE vec4 vec3_to_vec4 (vec3 vector, f32 w)
Returns a new vec4 using vector as the x, y and z components and w for w.
Parameters
vector The 3-component vector.
w The w component.
Returns
A new vec4
Definition at line 376 of file kmath.h.
References vec3_u::x, vec3_u::y, and vec3_u::z.
vec3_up()
KINLINE vec3 vec3_up ()
Creates and returns a 3-component vector pointing up (0, 1, 0).
Definition at line 397 of file kmath.h.
vec3_zero()
KINLINE vec3 vec3_zero ()
Creates and returns a 3-component vector with all components set to 0.0f.
Definition at line 383 of file kmath.h.
Referenced by game_initialize(), game_update(), and renderer_draw_frame().
vec4_add()
KINLINE vec4 vec4_add (vec4 vector_0, vec4 vector_1)
Adds vector_1 to vector_0 and returns a copy of the result.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The resulting vector.
Definition at line 695 of file kmath.h.
References vec4_u::elements.
vec4_compare()
KINLINE b8 vec4_compare (vec4 vector_0, vec4 vector_1, f32 tolerance)
Compares all elements of vector_0 and vector_1 with given tolerance.
Parameters
vector_0 First vector to compare
vector_1 Second vector to compare
tolerance Maximum allowed difference per component
Returns
True if all components are within tolerance, false otherwise
Definition at line 825 of file kmath.h.
References False, kabs(), True, vec4_u::w, vec4_u::x, vec4_u::y, and vec4_u::z.
vec4_create()
KINLINE vec4 vec4_create (f32 x, f32 y, f32 z, f32 w)
Creates and returns a new 4-element vector using the supplied values.
Parameters
x The x value.
y The y value.
z The z value.
w The w value.
Returns
A new 4-element vector.
Definition at line 633 of file kmath.h.
References vec4_u::w, vec4_u::x, vec4_u::y, and vec4_u::z.
Referenced by vulkan_object_shader_update_object().
vec4_distance()
KINLINE f32 vec4_distance (vec4 vector_0, vec4 vector_1)
Calculates the distance between two 4D vectors.
Parameters
vector_0 First vector
vector_1 Second vector
Returns
Euclidean distance between vectors
Definition at line 848 of file kmath.h.
References vec4_length(), and vec4_sub().
vec4_div()
KINLINE vec4 vec4_div (vec4 vector_0, vec4 vector_1)
Divides vector_0 by vector_1 and returns a copy of the result.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The resulting vector.
Definition at line 740 of file kmath.h.
References vec4_u::elements.
vec4_dot_f32()
KINLINE f32 vec4_dot_f32 (f32 a0, f32 a1, f32 a2, f32 a3, f32 b0, f32 b1, f32 b2, f32 b3)
Calculates the dot product between two 4D vectors.
Parameters
a0 First component of vector A
a1 Second component of vector A
a2 Third component of vector A
a3 Fourth component of vector A
b0 First component of vector B
b1 Second component of vector B
b2 Third component of vector B
b3 Fourth component of vector B
Returns
Dot product result
Definition at line 805 of file kmath.h.
vec4_from_vec3()
KINLINE vec4 vec4_from_vec3 (vec3 vector, f32 w)
Returns a new vec4 using vector as the x, y and z components and w for w.
Parameters
vector The 3-component vector.
w The w component.
Returns
A new vec4
Definition at line 664 of file kmath.h.
References vec3_u::x, vec3_u::y, and vec3_u::z.
vec4_length()
KINLINE f32 vec4_length (vec4 vector)
Returns the length of the provided vector.
Parameters
vector The vector to retrieve the length of.
Returns
The length.
Definition at line 764 of file kmath.h.
References ksqrt(), and vec4_length_squared().
Referenced by vec4_distance(), and vec4_normalize().
vec4_length_squared()
KINLINE f32 vec4_length_squared (vec4 vector)
Returns the squared length of the provided vector.
Parameters
vector The vector to retrieve the squared length of.
Returns
The squared length.
Definition at line 754 of file kmath.h.
References vec4_u::w, vec4_u::x, vec4_u::y, and vec4_u::z.
Referenced by vec4_length().
vec4_mul()
KINLINE vec4 vec4_mul (vec4 vector_0, vec4 vector_1)
Multiplies vector_0 by vector_1 and returns a copy of the result.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The resulting vector.
Definition at line 725 of file kmath.h.
References vec4_u::elements.
vec4_normalize()
KINLINE void vec4_normalize (vec4 * vector)
Normalizes the provided vector in place to a unit vector.
Parameters
vector A pointer to the vector to be normalized.
Definition at line 773 of file kmath.h.
References vec4_length(), vec4_u::w, vec4_u::x, vec4_u::y, and vec4_u::z.
Referenced by vec4_normalized().
vec4_normalized()
KINLINE vec4 vec4_normalized (vec4 vector)
Returns a normalized copy of the supplied vector.
Parameters
vector The vector to be normalized.
Returns
A normalized copy of the supplied vector
Definition at line 787 of file kmath.h.
References vec4_normalize().
vec4_one()
KINLINE vec4 vec4_one ()
Creates and returns a 3-component vector with all components set to 1.0f.
Definition at line 684 of file kmath.h.
Referenced by renderer_draw_frame().
vec4_sub()
KINLINE vec4 vec4_sub (vec4 vector_0, vec4 vector_1)
Subtracts vector_1 from vector_0 and returns a copy of the result.
Parameters
vector_0 The first vector.
vector_1 The second vector.
Returns
The resulting vector.
Definition at line 710 of file kmath.h.
References vec4_u::elements.
Referenced by vec4_distance().
vec4_to_vec3()
KINLINE vec3 vec4_to_vec3 (vec4 vector)
Returns a new vec3 containing the x, y and z components of the supplied vec4, essentially dropping the w component.
Parameters
vector The 4-component vector to extract from.
Returns
A new vec3
Definition at line 653 of file kmath.h.
References vec4_u::x, vec4_u::y, and vec4_u::z.
vec4_zero()
KINLINE vec4 vec4_zero ()
Creates and returns a 3-component vector with all components set to 0.0f.
Definition at line 677 of file kmath.h.