Koru Game Engine: engine/src/core/kmemory.h File Reference
kmemory.h File Reference
Memory allocation system with tagging and tracking.
#include "defines.h"
Typedefs
typedef enum memory_tag memory_tag
Memory allocation tag types.
Enumerations
enum memory_tag {
MEMORY_TAG_UNKNOWN , MEMORY_TAG_ARRAY , MEMORY_TAG_LINEAR_ALLOCATOR , MEMORY_TAG_DARRAY ,
MEMORY_TAG_DICT , MEMORY_TAG_RING_QUEUE , MEMORY_TAG_BST , MEMORY_TAG_STRING ,
MEMORY_TAG_APPLICATION , MEMORY_TAG_JOB , MEMORY_TAG_TEXTURE , MEMORY_TAG_MATERIAL_INSTANCE ,
MEMORY_TAG_RENDERER , MEMORY_TAG_GAME , MEMORY_TAG_TRANSFORM , MEMORY_TAG_ENTITY ,
MEMORY_TAG_ENTITY_NODE , MEMORY_TAG_SCENE , MEMORY_TAG_MAX_TAGS
}
Memory allocation tag types.
Functions
KAPI void initialize_memory (u64 *memory_requirement, void *state)
Initializes the memory allocator subsystem.
KAPI void shutdown_memory (void *state)
Shuts down the memory allocator subsystem.
KAPI void * kallocate (u64 size, memory_tag tag)
Allocates memory with the given size and tag.
KAPI void kfree (void *block, u64 size, memory_tag tag)
Frees a previously allocated memory block.
KAPI void * kzero_memory (void *block, u64 size)
Fills the provided memory block with zeros.
KAPI void * kcopy_memory (void *dest, const void *source, u64 size)
Copies memory from one location to another.
KAPI void * kset_memory (void *dest, i32 value, u64 size)
Fills a memory block with a specific byte value.
KAPI char * get_memory_usage_str ()
Gets a formatted string showing current memory usage per tag.
KAPI u64 get_memory_alloc_count ()
Gets the total number of memory allocations made.
Detailed Description
Memory allocation system with tagging and tracking.
This module introduces a tagged memory allocator that helps track:
Where memory is being used (e.g., textures, entities, renderer, etc.)
Total allocations per tag
Potential leaks or misuses
Usage: Replace raw malloc()/free() calls with kallocate()/kfree().
Definition in file kmemory.h.
Typedef Documentation
memory_tag
typedef enum memory_tag memory_tag
Memory allocation tag types.
Used to categorize memory allocations for tracking, debugging, and profiling. Each tag should be used consistently for similar kinds of allocations.
Enumeration Type Documentation
memory_tag
enum memory_tag
Memory allocation tag types.
Used to categorize memory allocations for tracking, debugging, and profiling. Each tag should be used consistently for similar kinds of allocations.
Enumerator
MEMORY_TAG_UNKNOWN
For temporary use only. Should eventually be replaced with a proper tag.
MEMORY_TAG_ARRAY
Dynamic arrays (e.g., array_push)
MEMORY_TAG_LINEAR_ALLOCATOR
Linear allocator for fast, sequential allocations.
MEMORY_TAG_DARRAY
Dynamic arrays that grow/shrink dynamically
MEMORY_TAG_DICT
Dictionary/Hash Table allocations
MEMORY_TAG_RING_QUEUE
Ring queue structures
MEMORY_TAG_BST
Binary search trees
MEMORY_TAG_STRING
String-related allocations
MEMORY_TAG_APPLICATION
Application-level state
MEMORY_TAG_JOB
Job system allocations
MEMORY_TAG_TEXTURE
Texture data
MEMORY_TAG_MATERIAL_INSTANCE
Material instances
MEMORY_TAG_RENDERER
Renderer-specific allocations
MEMORY_TAG_GAME
Game logic/state
MEMORY_TAG_TRANSFORM
Transform components
MEMORY_TAG_ENTITY
Entity objects
MEMORY_TAG_ENTITY_NODE
Scene graph entity nodes
MEMORY_TAG_SCENE
Scene management
MEMORY_TAG_MAX_TAGS
Must be last – represents total number of tags
Definition at line 24 of file kmemory.h.
Function Documentation
get_memory_alloc_count()
KAPI u64 get_memory_alloc_count ()
Gets the total number of memory allocations made.
This is useful for tracking memory usage and potential leaks.
Returns
The total number of allocations made since the application started.
Definition at line 244 of file kmemory.c.
References memory_system_state::alloc_count, and state_ptr.
Referenced by game_update().
get_memory_usage_str()
KAPI char * get_memory_usage_str ()
Gets a formatted string showing current memory usage per tag.
Useful for logging and debugging.
Returns
A heap-allocated string containing formatted memory usage info. Caller must free it using kfree().
Gets a formatted string showing current memory usage per tag.
Useful for logging and debugging. Automatically scales values to KB/MB/GB.
Returns
A heap-allocated string containing formatted memory usage info. Caller must free it using kfree().
Definition at line 206 of file kmemory.c.
References MEMORY_TAG_MAX_TAGS, memory_tag_strings, state_ptr, memory_system_state::stats, and memory_stats::tagged_allocations.
Referenced by application_run().
initialize_memory()
KAPI void initialize_memory (u64 * memory_requirement, void * state)
Initializes the memory allocator subsystem.
Sets internal counters to zero and prepares for tracking allocations.
Initializes the memory allocator subsystem.
Resets all counters to zero.
Definition at line 90 of file kmemory.c.
References memory_system_state::alloc_count, platform_zero_memory(), state_ptr, and memory_system_state::stats.
Referenced by application_create().
kallocate()
KAPI void * kallocate (u64 size, memory_tag tag)
Allocates memory with the given size and tag.
Parameters
size The number of bytes to allocate.
tag A memory_tag to classify this allocation.
Returns
A pointer to the allocated memory block.
Allocates memory with the given size and tag.
Adds the allocation to internal statistics and returns a pointer to the block.
Parameters
size The number of bytes to allocate.
tag A memory_tag used to categorize this allocation.
Returns
A pointer to the allocated memory block.
Definition at line 122 of file kmemory.c.
References memory_system_state::alloc_count, False, KWARN, MEMORY_TAG_UNKNOWN, platform_allocate(), platform_zero_memory(), state_ptr, memory_system_state::stats, memory_stats::tagged_allocations, and memory_stats::total_allocated.
Referenced by _darray_create(), application_create(), create(), create_game(), filesystem_read_all_bytes(), geometry_system_generate_plane_config(), linear_allocator_create(), physical_device_meets_requirements(), string_duplicate(), vulkan_device_query_swapchain_support(), vulkan_framebuffer_create(), and vulkan_renderer_create_texture().
kcopy_memory()
KAPI void * kcopy_memory (void * dest, const void * source, u64 size)
Copies memory from one location to another.
Parameters
dest Destination memory block.
source Source memory block.
size Number of bytes to copy.
Returns
Pointer to the destination memory block.
Copies memory from one location to another.
Parameters
dest Destination memory block.
source Source memory block.
size Number of bytes to copy.
Returns
Pointer to the destination memory block.
Definition at line 182 of file kmemory.c.
References platform_copy_memory().
Referenced by _darray_insert_at(), _darray_pop(), _darray_pop_at(), _darray_push(), _darray_resize(), hashtable_fill(), hashtable_get(), hashtable_set(), input_update(), string_duplicate(), string_format_v(), and vulkan_buffer_load_data().
kfree()
KAPI void kfree (void * block, u64 size, memory_tag tag)
Frees a previously allocated memory block.
Parameters
block Pointer to the memory block to free.
size Size of the memory block in bytes.
tag Tag used when originally allocating the block.
Subtracts the deallocated size from internal statistics.
Parameters
block Pointer to the memory block to free.
size Size of the block in bytes (must match original allocation).
tag Tag used when originally allocating the block.
Definition at line 149 of file kmemory.c.
References False, KWARN, MEMORY_TAG_UNKNOWN, platform_free(), state_ptr, memory_system_state::stats, memory_stats::tagged_allocations, and memory_stats::total_allocated.
Referenced by _darray_destroy(), application_create(), create_shader_module(), linear_allocator_destroy(), physical_device_meets_requirements(), vulkan_device_destroy(), vulkan_framebuffer_destroy(), and vulkan_renderer_destroy_texture().
kset_memory()
KAPI void * kset_memory (void * dest, i32 value, u64 size)
Fills a memory block with a specific byte value.
Parameters
dest Destination memory block.
value Byte value to fill with.
size Number of bytes to fill.
Returns
Pointer to the filled memory block.
Fills a memory block with a specific byte value.
Parameters
dest Destination memory block.
value Byte value to fill the block with.
size Number of bytes to fill.
Returns
Pointer to the filled memory block.
Definition at line 194 of file kmemory.c.
References platform_set_memory().
Referenced by _darray_create(), and create_default_textures().
kzero_memory()
KAPI void * kzero_memory (void * block, u64 size)
Fills the provided memory block with zeros.
Parameters
block Pointer to the memory block.
size Number of bytes to zero out.
Returns
Pointer to the zeroed memory block.
Definition at line 170 of file kmemory.c.
References platform_zero_memory().
Referenced by create_command_buffers(), create_default_geometry(), create_default_material(), create_shader_module(), destroy_material(), destroy_texture(), event_system_initialize(), hashtable_create(), hashtable_destroy(), input_system_initialize(), linear_allocator_free_all(), load_configuration_file(), load_material(), log_output(), mat4_identity(), mat4_perspective(), string_to_vec2(), string_to_vec3(), string_to_vec4(), vulkan_buffer_create(), vulkan_command_buffer_allocate(), vulkan_device_destroy(), vulkan_graphics_pipeline_create(), vulkan_image_copy_from_buffer(), vulkan_material_shader_apply_material(), vulkan_material_shader_create(), vulkan_renderer_destroy_geometry(), vulkan_renderer_destroy_texture(), and vulkan_renderpass_begin().
shutdown_memory()
KAPI void shutdown_memory (void * state)
Shuts down the memory allocator subsystem.
Currently does nothing but may be extended to log final stats or validate leaks.
Shuts down the memory allocator subsystem.
Currently does nothing but can be extended to log final usage or detect leaks.
Definition at line 107 of file kmemory.c.
References state_ptr.
Referenced by application_run().