Koru Game Engine: engine/src/core/kmemory.c File Reference
kmemory.c File Reference
Implementation of the tagged memory allocation system.
#include "kmemory.h"
#include "core/logger.h"
#include "platform/platform.h"
#include <string.h>
#include <stdio.h>
Data Structures
struct memory_stats
Tracks memory usage statistics.
Functions
void initialize_memory ()
Initializes the memory tracking system.
void shutdown_memory ()
Shuts down the memory tracking system.
void * kallocate (u64 size, memory_tag tag)
Allocates memory with a given size and tag.
void kfree (void *block, u64 size, memory_tag tag)
Frees a previously allocated memory block.
void * kzero_memory (void *block, u64 size)
Fills the provided memory block with zeros.
void * kcopy_memory (void *dest, const void *source, u64 size)
Copies data from one memory block to another.
void * kset_memory (void *dest, i32 value, u64 size)
Sets every byte in a memory block to a specific value.
char * get_memory_usage_str ()
Generates a formatted string showing current memory usage per tag.
Variables
static const char * memory_tag_strings [MEMORY_TAG_MAX_TAGS]
Human-readable strings for each memory tag.
static struct memory_stats stats
Global instance of memory usage statistics.
Detailed Description
Implementation of the tagged memory allocation system.
This module implements a memory tracking system that allows allocations to be categorized using tags (e.g., MEMORY_TAG_RENDERER, MEMORY_TAG_GAME). It provides:
Memory usage statistics per tag
Allocation and deallocation wrappers with tracking
Helper functions like kzero_memory(), kcopy_memory(), and kset_memory()
A utility function to generate formatted memory usage strings for debugging
The system wraps platform-specific memory functions (platform_allocate, platform_free) to ensure consistent behavior and logging.
Usage: Replace raw memory operations with kallocate() / kfree() to enable tracking.
Definition in file kmemory.c.
Function Documentation
get_memory_usage_str()
char * get_memory_usage_str ()
Generates a formatted string showing current memory usage per tag.
Gets a formatted string showing current memory usage per tag.
Useful for logging and debugging. Automatically scales values to KB/MB/GB.
Returns
A heap-allocated string containing formatted memory usage info. Caller must free it using kfree().
Definition at line 184 of file kmemory.c.
References MEMORY_TAG_MAX_TAGS, memory_tag_strings, stats, and memory_stats::tagged_allocations.
Referenced by application_run().
initialize_memory()
void initialize_memory ()
Initializes the memory tracking system.
Initializes the memory allocator subsystem.
Resets all counters to zero.
Definition at line 83 of file kmemory.c.
References platform_zero_memory(), and stats.
Referenced by main().
kallocate()
void * kallocate (u64 size, memory_tag tag)
Allocates memory with a given size and tag.
Allocates memory with the given size and tag.
Adds the allocation to internal statistics and returns a pointer to the block.
Parameters
size The number of bytes to allocate.
tag A memory_tag used to categorize this allocation.
Returns
A pointer to the allocated memory block.
Definition at line 105 of file kmemory.c.
References False, KWARN, MEMORY_TAG_UNKNOWN, platform_allocate(), platform_zero_memory(), stats, memory_stats::tagged_allocations, and memory_stats::total_allocated.
Referenced by _darray_create(), create(), create_game(), physical_device_meets_requirements(), renderer_initialize(), string_duplicate(), vulkan_device_query_swapchain_support(), and vulkan_framebuffer_create().
kcopy_memory()
void * kcopy_memory (void * dest, const void * source, u64 size)
Copies data from one memory block to another.
Copies memory from one location to another.
Parameters
dest Destination memory block.
source Source memory block.
size Number of bytes to copy.
Returns
Pointer to the destination memory block.
Definition at line 160 of file kmemory.c.
References platform_copy_memory().
Referenced by _darray_insert_at(), _darray_pop(), _darray_pop_at(), _darray_push(), _darray_resize(), input_update(), and string_duplicate().
kfree()
void kfree (void * block, u64 size, memory_tag tag)
Frees a previously allocated memory block.
Subtracts the deallocated size from internal statistics.
Parameters
block Pointer to the memory block to free.
size Size of the block in bytes (must match original allocation).
tag Tag used when originally allocating the block.
Definition at line 129 of file kmemory.c.
References False, KWARN, MEMORY_TAG_UNKNOWN, platform_free(), stats, memory_stats::tagged_allocations, and memory_stats::total_allocated.
Referenced by _darray_destroy(), physical_device_meets_requirements(), renderer_shutdown(), vulkan_device_destroy(), and vulkan_framebuffer_destroy().
kset_memory()
void * kset_memory (void * dest, i32 value, u64 size)
Sets every byte in a memory block to a specific value.
Fills a memory block with a specific byte value.
Parameters
dest Destination memory block.
value Byte value to fill the block with.
size Number of bytes to fill.
Returns
Pointer to the filled memory block.
Definition at line 172 of file kmemory.c.
References platform_set_memory().
Referenced by _darray_create().
kzero_memory()
void * kzero_memory (void * block, u64 size)
Fills the provided memory block with zeros.
Parameters
block Pointer to the memory block.
size Number of bytes to zero out.
Returns
Pointer to the zeroed memory block.
Definition at line 148 of file kmemory.c.
References platform_zero_memory().
Referenced by create_command_buffers(), event_initialize(), input_initialize(), mat4_identity(), mat4_perspective(), vulkan_command_buffer_allocate(), vulkan_device_destroy(), and vulkan_renderpass_begin().
shutdown_memory()
void shutdown_memory ()
Shuts down the memory tracking system.
Shuts down the memory allocator subsystem.
Currently does nothing but can be extended to log final usage or detect leaks.
Definition at line 92 of file kmemory.c.
Referenced by main().
Variable Documentation
memory_tag_strings
const char* memory_tag_strings[MEMORY_TAG_MAX_TAGS] static
Initial value:
= {
    "UNKNOWN    ",
    "ARRAY      ",
    "DARRAY     ",
    "DICT       ",
    "RING_QUEUE ",
    "BST        ",
    "STRING     ",
    "APPLICATION",
    "JOB        ",
    "TEXTURE    ",
    "MAT_INST   ",
    "RENDERER   ",
    "GAME       ",
    "TRANSFORM  ",
    "ENTITY     ",
    "ENTITY_NODE",
    "SCENE      "}
Human-readable strings for each memory tag.
Used when printing memory usage stats to provide meaningful labels.
Definition at line 52 of file kmemory.c.
Referenced by get_memory_usage_str().
stats
struct memory_stats stats static
Global instance of memory usage statistics.
Aggregates all memory allocations tracked by kallocate/kfree.
Definition at line 76 of file kmemory.c.
Referenced by get_memory_usage_str(), initialize_memory(), kallocate(), and kfree().