Koru Game Engine: engine/src/core/kstring.h File Reference
kstring.h File Reference
Lightweight string utility library.
#include "defines.h"
#include "math/math_types.h"
Functions
KAPI u64 string_length (const char *str)
Returns the length of the given null-terminated string.
KAPI char * string_duplicate (const char *str)
Duplicates the given null-terminated string into a new heap-allocated copy.
KAPI b8 strings_equal (const char *str0, const char *str1)
Compares two null-terminated strings for equality (case-sensitive).
KAPI b8 strings_equali (const char *str0, const char *str1)
Compares two null-terminated strings for equality (case-insensitive).
KAPI i32 string_format (char *dest, const char *format,...)
Performs string formatting against the given format string and parameters. NOTE: that this performs a dynamic allocation and should be freed by the caller.
KAPI i32 string_format_v (char *dest, const char *format, void *va_list)
Performs variadic string formatting against the given format string and va_list. NOTE: that this performs a dynamic allocation and should be freed by the caller.
KAPI char * string_copy (char *dest, const char *source)
Copies the source string to the destination string, including the null terminator.
KAPI char * string_ncopy (char *dest, const char *source, i64 length)
Copies up to length characters from the source string to the destination string. If the source string is shorter than length, the destination is null-terminated.
KAPI char * string_trim (char *str)
Trims leading and trailing whitespace from the given string in place.
KAPI void string_mid (char *dest, const char *source, i32 start, i32 length)
Extracts a substring from the source string, starting at the given index and of the given length.
KAPI i32 string_index_of (char *str, char c)
Returns the index of the first occurance of c in str; otherwise -1.
KAPI b8 string_to_vec4 (char *str, vec4 *out_vector)
Attempts to parse a vector from the provided string.
KAPI b8 string_to_vec3 (char *str, vec3 *out_vector)
Attempts to parse a vector from the provided string.
KAPI b8 string_to_vec2 (char *str, vec2 *out_vector)
Attempts to parse a vector from the provided string.
KAPI b8 string_to_f32 (char *str, f32 *f)
Attempts to parse a 32-bit floating-point number from the provided string.
KAPI b8 string_to_f64 (char *str, f64 *f)
Attempts to parse a 64-bit floating-point number from the provided string.
KAPI b8 string_to_i8 (char *str, i8 *i)
Attempts to parse an 8-bit signed integer from the provided string.
KAPI b8 string_to_i16 (char *str, i16 *i)
Attempts to parse a 16-bit signed integer from the provided string.
KAPI b8 string_to_i32 (char *str, i32 *i)
Attempts to parse a 32-bit signed integer from the provided string.
KAPI b8 string_to_i64 (char *str, i64 *i)
Attempts to parse a 64-bit signed integer from the provided string.
KAPI b8 string_to_u8 (char *str, u8 *u)
Attempts to parse an 8-bit unsigned integer from the provided string.
KAPI b8 string_to_u16 (char *str, u16 *u)
Attempts to parse a 16-bit unsigned integer from the provided string.
KAPI b8 string_to_u32 (char *str, u32 *u)
Attempts to parse a 32-bit unsigned integer from the provided string.
KAPI b8 string_to_u64 (char *str, u64 *u)
Attempts to parse a 64-bit unsigned integer from the provided string.
KAPI b8 string_to_bool (char *str, b8 *b)
Attempts to parse a boolean from the provided string. "true" or "1" are considered true; anything else is false.
KAPI char * string_empty (char *str)
Empties the given string by setting the first character to 0.
Detailed Description
Lightweight string utility library.
This module provides basic string operations that are:
Safe(r) than raw C string functions
Integrated with the engine's memory system
Designed for clarity and maintainability
These utilities are intended to be used internally within the engine, not exposed to end-user game code (which should use standard C strings).
Definition in file kstring.h.
Function Documentation
string_copy()
KAPI char * string_copy (char * dest, const char * source)
Copies the source string to the destination string, including the null terminator.
Parameters
dest The destination string buffer. Must be large enough to hold the source string.
source The source null-terminated string to copy.
Returns
A pointer to the destination string.
Definition at line 76 of file kstring.c.
string_duplicate()
KAPI char * string_duplicate (const char * str)
Duplicates the given null-terminated string into a new heap-allocated copy.
Uses kallocate() so the duplicated string can be tracked by the engine's memory system.
Parameters
str A pointer to a null-terminated string to duplicate.
Returns
A newly allocated copy of the input string. Caller must free using kfree() or string_free().
Definition at line 30 of file kstring.c.
References kallocate(), kcopy_memory(), MEMORY_TAG_STRING, and string_length().
string_empty()
KAPI char * string_empty (char * str)
Empties the given string by setting the first character to 0.
Parameters
str The string to empty.
Returns
A pointer to the emptied string.
Definition at line 287 of file kstring.c.
Referenced by destroy_geometry().
string_format()
KAPI i32 string_format (char * dest, const char * format, ...)
Performs string formatting against the given format string and parameters. NOTE: that this performs a dynamic allocation and should be freed by the caller.
Parameters
format The format string to use for the operation
... The format arguments.
Returns
The newly-formatted string (dynamically allocated).
Definition at line 52 of file kstring.c.
References string_format_v().
Referenced by create_shader_module(), load_texture(), log_output(), and material_system_acquire().
string_format_v()
KAPI i32 string_format_v (char * dest, const char * format, void * va_list)
Performs variadic string formatting against the given format string and va_list. NOTE: that this performs a dynamic allocation and should be freed by the caller.
Parameters
format The string to be formatted.
va_list The variadic argument list.
Returns
The newly-formatted string (dynamically allocated).
Definition at line 63 of file kstring.c.
References kcopy_memory().
Referenced by log_output(), and string_format().
string_index_of()
KAPI i32 string_index_of (char * str, char c)
Returns the index of the first occurance of c in str; otherwise -1.
Parameters
str The string to be scanned.
c The character to search for.
Returns
The index of the first occurance of c; otherwise -1 if not found.
Definition at line 133 of file kstring.c.
References string_length().
Referenced by load_configuration_file().
string_length()
KAPI u64 string_length (const char * str)
Returns the length of the given null-terminated string.
Wraps strlen() to provide a consistent interface within the engine.
Parameters
str A pointer to a null-terminated string.
Returns
The number of characters in the string (excluding the null terminator).
Definition at line 26 of file kstring.c.
Referenced by append_to_log_file(), create_geometry(), destroy_geometry(), geometry_system_generate_plane_config(), load_configuration_file(), load_material(), string_duplicate(), string_index_of(), and string_mid().
string_mid()
KAPI void string_mid (char * dest, const char * source, i32 start, i32 length)
Extracts a substring from the source string, starting at the given index and of the given length.
Parameters
dest The destination buffer to write the substring to. Must be large enough to hold length characters plus a null terminator.
source The source null-terminated string to extract from.
start The starting index in the source string (0-based).
length The number of characters to extract.
Definition at line 108 of file kstring.c.
References string_length().
Referenced by load_configuration_file().
string_ncopy()
KAPI char * string_ncopy (char * dest, const char * source, i64 length)
Copies up to length characters from the source string to the destination string. If the source string is shorter than length, the destination is null-terminated.
Parameters
dest The destination string buffer. Must be large enough to hold length characters plus a null terminator.
source The source null-terminated string to copy from.
length The maximum number of characters to copy from the source string.
Returns
A pointer to the destination string.
Definition at line 80 of file kstring.c.
Referenced by create_default_material(), create_default_textures(), geometry_system_generate_plane_config(), load_configuration_file(), load_material(), and texture_system_release().
string_to_bool()
KAPI b8 string_to_bool (char * str, b8 * b)
Attempts to parse a boolean from the provided string. "true" or "1" are considered true; anything else is false.
Parameters
str The string to parse from. "true" or "1" are considered true; anything else is false.
b A pointer to the boolean to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 279 of file kstring.c.
References False, strings_equal(), and strings_equali().
string_to_f32()
KAPI b8 string_to_f32 (char * str, f32 * f)
Attempts to parse a 32-bit floating-point number from the provided string.
Parameters
str The string to parse from. Should not be postfixed with 'f'.
f A pointer to the float to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 179 of file kstring.c.
References False.
string_to_f64()
KAPI b8 string_to_f64 (char * str, f64 * f)
Attempts to parse a 64-bit floating-point number from the provided string.
Parameters
str The string to parse from.
f A pointer to the float to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 189 of file kstring.c.
References False.
string_to_i16()
KAPI b8 string_to_i16 (char * str, i16 * i)
Attempts to parse a 16-bit signed integer from the provided string.
Parameters
str The string to parse from.
i A pointer to the int to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 209 of file kstring.c.
References False.
string_to_i32()
KAPI b8 string_to_i32 (char * str, i32 * i)
Attempts to parse a 32-bit signed integer from the provided string.
Parameters
str The string to parse from.
i A pointer to the int to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 219 of file kstring.c.
References False.
string_to_i64()
KAPI b8 string_to_i64 (char * str, i64 * i)
Attempts to parse a 64-bit signed integer from the provided string.
Parameters
str The string to parse from.
i A pointer to the int to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 229 of file kstring.c.
References False.
string_to_i8()
KAPI b8 string_to_i8 (char * str, i8 * i)
Attempts to parse an 8-bit signed integer from the provided string.
Parameters
str The string to parse from.
i A pointer to the int to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 199 of file kstring.c.
References False.
string_to_u16()
KAPI b8 string_to_u16 (char * str, u16 * u)
Attempts to parse a 16-bit unsigned integer from the provided string.
Parameters
str The string to parse from.
u A pointer to the int to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 249 of file kstring.c.
References False.
string_to_u32()
KAPI b8 string_to_u32 (char * str, u32 * u)
Attempts to parse a 32-bit unsigned integer from the provided string.
Parameters
str The string to parse from.
u A pointer to the int to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 259 of file kstring.c.
References False.
string_to_u64()
KAPI b8 string_to_u64 (char * str, u64 * u)
Attempts to parse a 64-bit unsigned integer from the provided string.
Parameters
str The string to parse from.
u A pointer to the int to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 269 of file kstring.c.
References False.
string_to_u8()
KAPI b8 string_to_u8 (char * str, u8 * u)
Attempts to parse an 8-bit unsigned integer from the provided string.
Parameters
str The string to parse from.
u A pointer to the int to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 239 of file kstring.c.
References False.
string_to_vec2()
KAPI b8 string_to_vec2 (char * str, vec2 * out_vector)
Attempts to parse a vector from the provided string.
Parameters
str The string to parse from. Should be space-delimited. (i.e. "1.0 2.0")
out_vector A pointer to the vector to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 169 of file kstring.c.
References False, kzero_memory(), vec2_u::x, and vec2_u::y.
string_to_vec3()
KAPI b8 string_to_vec3 (char * str, vec3 * out_vector)
Attempts to parse a vector from the provided string.
Parameters
str The string to parse from. Should be space-delimited. (i.e. "1.0 2.0 3.0")
out_vector A pointer to the vector to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 159 of file kstring.c.
References False, kzero_memory(), vec3_u::x, vec3_u::y, and vec3_u::z.
string_to_vec4()
KAPI b8 string_to_vec4 (char * str, vec4 * out_vector)
Attempts to parse a vector from the provided string.
Parameters
str The string to parse from. Should be space-delimited. (i.e. "1.0 2.0 3.0 4.0")
out_vector A pointer to the vector to write to.
Returns
True if parsed successfully; otherwise false.
Definition at line 149 of file kstring.c.
References False, kzero_memory(), vec4_u::w, vec4_u::x, vec4_u::y, and vec4_u::z.
Referenced by load_configuration_file().
string_trim()
KAPI char * string_trim (char * str)
Trims leading and trailing whitespace from the given string in place.
Parameters
str The string to trim. Must be mutable.
Returns
A pointer to the trimmed string (which may be the same as the input pointer).
Definition at line 84 of file kstring.c.
Referenced by load_configuration_file().
strings_equal()
KAPI b8 strings_equal (const char * str0, const char * str1)
Compares two null-terminated strings for equality (case-sensitive).
This function performs a character-by-character comparison of two strings.
Parameters
str0 First string to compare.
str1 Second string to compare.
Returns
True if both strings are identical; False otherwise.
Definition at line 40 of file kstring.c.
Referenced by physical_device_meets_requirements(), string_to_bool(), and vulkan_renderer_backend_initialize().
strings_equali()
KAPI b8 strings_equali (const char * str0, const char * str1)
Compares two null-terminated strings for equality (case-insensitive).
This function performs a character-by-character comparison of two strings, ignoring case differences.
Parameters
str0 First string to compare.
str1 Second string to compare.
Returns
True if both strings are identical (case-insensitive); False otherwise.
Definition at line 44 of file kstring.c.
Referenced by load_configuration_file(), material_system_acquire_from_config(), material_system_release(), string_to_bool(), texture_system_acquire(), and texture_system_release().