Koru Game Engine: engine/src/memory/linear_allocator.h File Reference
linear_allocator.h File Reference
Linear memory allocator for efficient allocation of fixed-size blocks.
#include "defines.h"
Data Structures
struct linear_allocator
Represents a linear memory allocator.
Typedefs
typedef struct linear_allocator linear_allocator
Functions
KAPI void linear_allocator_create (u64 total_size, void *memory, linear_allocator *out_allocator)
Creates a linear allocator with the specified total size and memory block. This function initializes the linear allocator with a given size and memory block.
KAPI void linear_allocator_destroy (linear_allocator *out_allocator)
Destroys the linear allocator.
KAPI void * linear_allocator_allocate (linear_allocator *allocator, u64 size)
Allocates a block of memory from the linear allocator.
KAPI void linear_allocator_free_all (linear_allocator *allocator)
Frees all allocated memory in the linear allocator.
Detailed Description
Linear memory allocator for efficient allocation of fixed-size blocks.
This allocator is designed for scenarios where memory is allocated in a linear fashion, such as for temporary buffers or scratch memory. It allows for fast allocation and deallocation of memory blocks without the overhead of managing free lists or complex data structures.
Definition in file linear_allocator.h.
Typedef Documentation
linear_allocator
typedef struct linear_allocator linear_allocator
Function Documentation
linear_allocator_allocate()
KAPI void * linear_allocator_allocate (linear_allocator * allocator, u64 size)
Allocates a block of memory from the linear allocator.
This function allocates a block of memory of the specified size from the linear allocator.
Parameters
allocator Pointer to the linear_allocator structure to allocate from.
size The size of the memory block to allocate in bytes.
Returns
Pointer to the allocated memory block, or NULL if allocation fails.
Definition at line 45 of file linear_allocator.c.
References linear_allocator::allocated, KFATAL, linear_allocator::memory, and linear_allocator::total_size.
Referenced by application_create().
linear_allocator_create()
KAPI void linear_allocator_create (u64 total_size, void * memory, linear_allocator * out_allocator)
Creates a linear allocator with the specified total size and memory block. This function initializes the linear allocator with a given size and memory block.
Parameters
total_size The total size of the allocator in bytes.
memory Pointer to the memory block to use for allocation.
out_allocator Pointer to the linear_allocator structure to initialize.
Returns
void
Definition at line 14 of file linear_allocator.c.
References linear_allocator::allocated, kallocate(), linear_allocator::memory, MEMORY_TAG_LINEAR_ALLOCATOR, linear_allocator::owns_memory, and linear_allocator::total_size.
Referenced by application_create().
linear_allocator_destroy()
KAPI void linear_allocator_destroy (linear_allocator * out_allocator)
Destroys the linear allocator.
This function cleans up the linear allocator, freeing any resources it owns.
Parameters
out_allocator Pointer to the linear_allocator structure to destroy.
Returns
void
Definition at line 28 of file linear_allocator.c.
References linear_allocator::allocated, False, kfree(), linear_allocator::memory, MEMORY_TAG_LINEAR_ALLOCATOR, linear_allocator::owns_memory, and linear_allocator::total_size.
linear_allocator_free_all()
KAPI void linear_allocator_free_all (linear_allocator * allocator)
Frees all allocated memory in the linear allocator.
This function resets the allocator, freeing all memory blocks that were allocated. It does not free the memory block itself, only resets the allocation state.
Parameters
allocator Pointer to the linear_allocator structure to free.
Returns
void
Definition at line 65 of file linear_allocator.c.
References linear_allocator::allocated, kzero_memory(), linear_allocator::memory, and linear_allocator::total_size.