Koru Game Engine: engine/src/core/logger.h File Reference
logger.h File Reference
Public interface for the logging system.
#include "defines.h"
Macros
#define LOG_WARN_ENABLED 1
Enables warning-level logging output.
#define LOG_INFO_ENABLED 1
Enables info-level logging output.
#define LOG_DEBUG_ENABLED 1
Enables debug-level logging output.
#define LOG_TRACE_ENABLED 1
Enables trace-level logging output.
#define KFATAL(message, ...) log_output(LOG_LEVEL_FATAL, message, ##__VA_ARGS__)
Logs a fatal-level message.
#define KERROR(message, ...) log_output(LOG_LEVEL_ERROR, message, ##__VA_ARGS__)
Logs an error-level message.
#define KWARN(message, ...) log_output(LOG_LEVEL_WARN, message, ##__VA_ARGS__)
Logs a warning-level message.
#define KINFO(message, ...) log_output(LOG_LEVEL_INFO, message, ##__VA_ARGS__)
Logs an info-level message.
#define KDEBUG(message, ...) log_output(LOG_LEVEL_DEBUG, message, ##__VA_ARGS__)
Logs a debug-level message.
#define KTRACE(message, ...) log_output(LOG_LEVEL_TRACE, message, ##__VA_ARGS__)
Logs a trace-level message.
Typedefs
typedef enum log_level log_level
Log severity levels used for filtering and categorizing log messages.
Enumerations
enum log_level {
LOG_LEVEL_FATAL = 0 , LOG_LEVEL_ERROR = 1 , LOG_LEVEL_WARN = 2 , LOG_LEVEL_INFO = 3 ,
LOG_LEVEL_DEBUG = 4 , LOG_LEVEL_TRACE = 5
}
Log severity levels used for filtering and categorizing log messages.
Functions
b8 initialize_logging (u64 *memory_requirement, void *state)
Initializes the logging system. Called twice; once with state = 0 to get required memory size then a second time passing allocated memory to the state.
void shutdown_logging (void *state)
Shuts down the logging system.
KAPI void log_output (log_level level, const char *message,...)
Logs a formatted message at the specified log level.
Detailed Description
Public interface for the logging system.
This module provides a flexible logging system with support for:
Multiple severity levels (FATAL, ERROR, WARN, INFO, DEBUG, TRACE)
Compile-time log level filtering
Color-coded console output
Assertion failure reporting
Usage: Use the provided macros (KFATAL, KERROR, KWARN, etc.) to log messages at different severity levels.
Definition in file logger.h.
Macro Definition Documentation
KDEBUG
#define KDEBUG (message, ...) log_output(LOG_LEVEL_DEBUG, message, ##__VA_ARGS__)
Logs a debug-level message.
Used for developer diagnostics.
Example:
KDEBUG("Function called with value: %d", x);
Definition at line 213 of file logger.h.
KERROR
#define KERROR (message, ...) log_output(LOG_LEVEL_ERROR, message, ##__VA_ARGS__)
Logs an error-level message.
Used for recoverable errors.
Example:
KERROR("Asset failed to load: %s", asset_name);
Definition at line 165 of file logger.h.
KFATAL
#define KFATAL (message, ...) log_output(LOG_LEVEL_FATAL, message, ##__VA_ARGS__)
Logs a fatal-level message.
Used for unrecoverable errors. Always displayed.
Example:
KFATAL("Out of memory!");
Definition at line 152 of file logger.h.
KINFO
#define KINFO (message, ...) log_output(LOG_LEVEL_INFO, message, ##__VA_ARGS__)
Logs an info-level message.
Used for general status updates.
Example:
KINFO("Engine started successfully.");
Definition at line 196 of file logger.h.
KTRACE
#define KTRACE (message, ...) log_output(LOG_LEVEL_TRACE, message, ##__VA_ARGS__)
Logs a trace-level message.
Most verbose level; used for detailed debugging.
Example:
KTRACE("Frame delta time: %f", dt);
Definition at line 230 of file logger.h.
KWARN
#define KWARN (message, ...) log_output(LOG_LEVEL_WARN, message, ##__VA_ARGS__)
Logs a warning-level message.
Used for non-critical issues.
Example:
KWARN("Deprecated function called");
Definition at line 179 of file logger.h.
LOG_DEBUG_ENABLED
#define LOG_DEBUG_ENABLED 1
Enables debug-level logging output.
Definition at line 37 of file logger.h.
LOG_INFO_ENABLED
#define LOG_INFO_ENABLED 1
Enables info-level logging output.
Definition at line 32 of file logger.h.
LOG_TRACE_ENABLED
#define LOG_TRACE_ENABLED 1
Enables trace-level logging output.
Definition at line 42 of file logger.h.
LOG_WARN_ENABLED
#define LOG_WARN_ENABLED 1
Enables warning-level logging output.
Definition at line 27 of file logger.h.
Typedef Documentation
log_level
typedef enum log_level log_level
Log severity levels used for filtering and categorizing log messages.
These levels help control how much detail is logged during execution. The logging system can be configured to show only messages at or above a certain level.
Enumeration Type Documentation
log_level
enum log_level
Log severity levels used for filtering and categorizing log messages.
These levels help control how much detail is logged during execution. The logging system can be configured to show only messages at or above a certain level.
Enumerator
LOG_LEVEL_FATAL
Fatal errors that cause immediate termination.
Should be used for unrecoverable failures (e.g., out-of-memory, failed asset load).
LOG_LEVEL_ERROR
Non-fatal errors that indicate something went wrong but can be recovered.
Examples: Invalid function parameters, failed state transitions.
LOG_LEVEL_WARN
Warnings about unexpected but recoverable situations.
Example: Deprecated function usage, resource not found but fallback exists.
LOG_LEVEL_INFO
General information messages useful for monitoring application flow.
Example: Startup/shutdown events, major state changes.
LOG_LEVEL_DEBUG
Debugging messages useful during development.
Example: Function entry/exit, internal state dumps, input/output values.
LOG_LEVEL_TRACE
Fine-grained tracing of program execution.
Most verbose level; used for detailed debugging (e.g., every frame update, small logic steps).
Definition at line 58 of file logger.h.
Function Documentation
initialize_logging()
b8 initialize_logging (u64 * memory_requirement, void * state)
Initializes the logging system. Called twice; once with state = 0 to get required memory size then a second time passing allocated memory to the state.
Allocates necessary resources and prepares the logging subsystem. This function should be called before any logging occurs.
Parameters
memory_requirement Pointer to store the required memory size for the logging system.
state Pointer to a pre-allocated memory block for the logger state. If NULL, no state is initialized.
Returns
True if initialization was successful; False otherwise.
Definition at line 64 of file logger.c.
References False, FILE_MODE_WRITE, filesystem_open(), logger_system_state::log_file_handle, LOG_LEVEL_ERROR, platform_console_write_error(), state_ptr, and True.
Referenced by application_create().
log_output()
KAPI void log_output (log_level level, const char * message, ...)
Logs a formatted message at the specified log level.
Supports standard formatting like printf() and includes:
Level prefixing (e.g., "[INFO]: ")
Color coding based on severity (if supported by terminal)
Platform-specific output routing
Parameters
level The severity level of the message (e.g., LOG_LEVEL_DEBUG).
message A format string similar to printf().
... Arguments used to replace format specifiers in the message.
TO-DO: Move string operations to their own thread The ops are pretty slow, and can slow down the engine during startup/shutdown. Work on threading and offset these ops.
Definition at line 95 of file logger.c.
References append_to_log_file(), kzero_memory(), LOG_LEVEL_WARN, MSG_LENGTH, platform_console_write(), platform_console_write_error(), string_format(), and string_format_v().
Referenced by report_assertion_failure().
shutdown_logging()
void shutdown_logging (void * state)
Shuts down the logging system.
Currently just returns. In future versions, this may include:
Flushing buffered logs
Closing log files
Releasing logging resources
Definition at line 85 of file logger.c.
References state_ptr.