Koru Game Engine: engine/src/core/logger.c File Reference
logger.c File Reference
Implementation of the logging system.
#include "logger.h"
#include "platform/platform.h"
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
Data Structures
struct logger_system_state
Macros
#define MSG_LENGTH 32000
Typedefs
typedef struct logger_system_state logger_system_state
Functions
b8 initialize_logging (u64 *memory_requirement, void *state)
Initializes the logging system. Called twice; once with state = 0 to get required memory size then a second time passing allocated memory to the state.
void shutdown_logging (void *state)
Shuts down the logging system.
void log_output (log_level level, const char *message,...)
Logs a formatted message at the specified log level.
void report_assertion_failure (const char *expression, const char *message, const char *file, i32 line)
Logs an assertion failure message to the logging system.
Variables
static logger_system_state * state_ptr
Detailed Description
Implementation of the logging system.
Implements the logging functionality with color-coded terminal output, message formatting, and integration with platform-specific console writes.
Features:
Level-based filtering
ANSI escape codes for color output
Platform abstraction for console output
Assertion failure handler
Definition in file logger.c.
Macro Definition Documentation
MSG_LENGTH
#define MSG_LENGTH 32000
Definition at line 10 of file logger.c.
Typedef Documentation
logger_system_state
typedef struct logger_system_state logger_system_state
Function Documentation
initialize_logging()
b8 initialize_logging (u64 * memory_requirement, void * state)
Initializes the logging system. Called twice; once with state = 0 to get required memory size then a second time passing allocated memory to the state.
Allocates necessary resources and prepares the logging subsystem. This function should be called before any logging occurs.
Parameters
memory_requirement Pointer to store the required memory size for the logging system.
state Pointer to a pre-allocated memory block for the logger state. If NULL, no state is initialized.
Returns
True if initialization was successful; False otherwise.
Definition at line 42 of file logger.c.
References logger_system_state::initialized, state_ptr, and True.
Referenced by application_create().
log_output()
void log_output (log_level level, const char * message, ...)
Logs a formatted message at the specified log level.
Supports standard formatting like printf() and includes:
Level prefixing (e.g., "[INFO]: ")
Color coding based on severity (if supported by terminal)
Platform-specific output routing
Parameters
level The severity level of the message (e.g., LOG_LEVEL_DEBUG).
message A format string similar to printf().
... Arguments used to replace format specifiers in the message.
Definition at line 68 of file logger.c.
References LOG_LEVEL_WARN, MSG_LENGTH, platform_console_write(), and platform_console_write_error().
Referenced by report_assertion_failure().
report_assertion_failure()
void report_assertion_failure (const char * expression, const char * message, const char * file, i32 line)
Logs an assertion failure message to the logging system.
This function should be implemented in logger.c or another source file. It is called internally by the assertion macros when a condition fails.
Parameters
expression The stringified failed condition (e.g., "x != NULL").
message Optional additional context about the assertion.
file The source file where the assertion occurred.
line The line number in the source file.
Definition at line 122 of file logger.c.
References LOG_LEVEL_FATAL, and log_output().
shutdown_logging()
void shutdown_logging (void * state)
Shuts down the logging system.
Currently just returns. In future versions, this may include:
Flushing buffered logs
Closing log files
Releasing logging resources
Definition at line 58 of file logger.c.
References state_ptr.
Variable Documentation
state_ptr
logger_system_state* state_ptr static
Definition at line 38 of file logger.c.
Referenced by initialize_logging(), and shutdown_logging().