Koru Game Engine: engine/src/systems/material_system.h File Reference
material_system.h File Reference
Material management system.
#include "renderer/renderer_types.inl"
Data Structures
struct material_system_config
Configuration options for initializing the material system.
struct material_config
Configuration for creating or loading a material.
Macros
#define DEFAULT_MATERIAL_NAME "default"
Default material name used when a requested texture is not found.
Typedefs
typedef struct material_system_config material_system_config
typedef struct material_config material_config
Functions
b8 material_system_initialize (u64 *memory_requirement, void *state, material_system_config config)
Initializes the material system.
void material_system_shutdown (void *state)
Shuts down the material system, freeing all resources.
material * material_system_acquire (const char *name)
Acquires a material by name.
material * material_system_acquire_from_config (material_config config)
Acquires a material based on the provided configuration.
void material_system_release (const char *name)
Releases a material by name.
material * material_system_get_default ()
Retrieves the default material used when a requested material is not found.
Detailed Description
Material management system.
This module provides functionality to manage material resources within the engine. It supports loading, acquiring, and releasing materials, as well as automatic cleanup of unused resources.
Usage:
Initialize the material system with material_system_initialize(), providing configuration options.
Acquire materials by name using material_system_acquire(). If the material is not already loaded, it will be created with default properties.
Release materials using material_system_release(). If a material was marked for auto-release, it will be freed when no longer in use.
Shutdown the material system with material_system_shutdown() to free all resources.
Definition in file material_system.h.
Macro Definition Documentation
DEFAULT_MATERIAL_NAME
#define DEFAULT_MATERIAL_NAME "default"
Default material name used when a requested texture is not found.
Definition at line 25 of file material_system.h.
Typedef Documentation
material_config
typedef struct material_config material_config
material_system_config
typedef struct material_system_config material_system_config
Function Documentation
material_system_acquire()
material * material_system_acquire (const char * name)
Acquires a material by name.
If the material is not already loaded, it will be created with default properties.
Parameters
name Name of the material to acquire.
Returns
Pointer to the acquired material, or NULL if acquisition failed.
Definition at line 169 of file material_system.c.
References KERROR, load_configuration_file(), material_system_acquire_from_config(), and string_format().
Referenced by create_geometry().
material_system_acquire_from_config()
material * material_system_acquire_from_config (material_config config)
Acquires a material based on the provided configuration.
If a material with the same name already exists, it will be returned. Otherwise, a new material will be created using the specified configuration.
Parameters
config Configuration for the material to be acquired or created.
Returns
Pointer to the acquired or newly created material, or NULL if acquisition failed.
Definition at line 190 of file material_system.c.
References material_reference::auto_release, material_config::auto_release, material_system_state::config, material_system_state::default_material, DEFAULT_MATERIAL_NAME, material::generation, material_reference::handle, hashtable_get(), hashtable_set(), material::id, INVALID_ID, KERROR, KFATAL, KTRACE, load_material(), material_system_config::max_material_count, material_config::name, material_reference::reference_count, material_system_state::registered_material_table, material_system_state::registered_materials, state_ptr, and strings_equali().
Referenced by material_system_acquire().
material_system_get_default()
material * material_system_get_default ()
Retrieves the default material used when a requested material is not found.
Returns
Pointer to the default material.
Definition at line 440 of file material_system.c.
References material_system_state::default_material, KFATAL, and state_ptr.
Referenced by create_default_geometry(), create_geometry(), and vulkan_backend_draw_geometry().
material_system_initialize()
b8 material_system_initialize (u64 * memory_requirement, void * state, material_system_config config)
Initializes the material system.
Parameters
memory_requirement Pointer to store the required memory size for the system state.
state Pointer to pre-allocated memory for the system state.
config Configuration options for the material system.
Returns
True if initialization was successful, False otherwise.
Definition at line 99 of file material_system.c.
References material_reference::auto_release, material_system_state::config, create_default_material(), False, material::generation, material_reference::handle, hashtable_create(), hashtable_fill(), material::id, material::internal_id, INVALID_ID, KFATAL, material_system_config::max_material_count, material_reference::reference_count, material_system_state::registered_material_table, material_system_state::registered_materials, state_ptr, and True.
Referenced by application_create().
material_system_release()
void material_system_release (const char * name)
Releases a material by name.
If the material was marked for auto-release, it will be freed when no longer in use.
Parameters
name Name of the material to release.
Definition at line 255 of file material_system.c.
References material_reference::auto_release, DEFAULT_MATERIAL_NAME, destroy_material(), False, material_reference::handle, hashtable_get(), hashtable_set(), INVALID_ID, KERROR, KTRACE, KWARN, material_reference::reference_count, material_system_state::registered_material_table, material_system_state::registered_materials, state_ptr, and strings_equali().
Referenced by destroy_geometry().
material_system_shutdown()
void material_system_shutdown (void * state)
Shuts down the material system, freeing all resources.
Parameters
state Pointer to the material system state.
Definition at line 151 of file material_system.c.
References material_system_state::config, material_system_state::default_material, destroy_material(), material::id, INVALID_ID, material_system_config::max_material_count, material_system_state::registered_materials, and state_ptr.
Referenced by application_run().