Koru Game Engine: engine/src/systems/material_system.c File Reference
material_system.c File Reference
Implementation of the material system.
#include "material_system.h"
#include "core/logger.h"
#include "core/kstring.h"
#include "containers/hashtable.h"
#include "math/kmath.h"
#include "renderer/renderer_frontend.h"
#include "systems/texture_system.h"
#include "platform/filesystem.h"
Data Structures
struct material_system_state
Internal state of the material system.
struct material_reference
Internal structure to track material references and auto-release status.
Typedefs
typedef struct material_system_state material_system_state
typedef struct material_reference material_reference
Functions
b8 create_default_material (material_system_state *state)
Creates the default material used when no specific material is assigned.
b8 load_material (material_config config, material *m)
Loads a material based on the provided configuration.
void destroy_material (material *m)
Destroys a material, freeing its resources.
b8 load_configuration_file (const char *path, material_config *out_config)
Loads a material configuration from a file.
b8 material_system_initialize (u64 *memory_requirement, void *state, material_system_config config)
Initializes the material system.
void material_system_shutdown (void *state)
Shuts down the material system, freeing all resources.
material * material_system_acquire (const char *name)
Acquires a material by name.
material * material_system_acquire_from_config (material_config config)
Acquires a material based on the provided configuration.
void material_system_release (const char *name)
Releases a material by name.
material * material_system_get_default ()
Retrieves the default material used when a requested material is not found.
Variables
static material_system_state * state_ptr = 0
Detailed Description
Implementation of the material system.
This module implements the functions defined in material_system.h. It manages the creation, acquisition, and release of materials, as well as the default material and material references.
Responsibilities:
Initialize the material system with material_system_initialize().
Acquire materials by name using material_system_acquire().
Release materials using material_system_release().
Shutdown the material system with material_system_shutdown().
Definition in file material_system.c.
Typedef Documentation
material_reference
typedef struct material_reference material_reference
material_system_state
typedef struct material_system_state material_system_state
Function Documentation
create_default_material()
b8 create_default_material (material_system_state * state)
Creates the default material used when no specific material is assigned.
Parameters
state Pointer to the material system state.
Returns
True if the default material was created successfully, False otherwise.
Definition at line 344 of file material_system.c.
References material_system_state::default_material, DEFAULT_MATERIAL_NAME, material::diffuse_color, material::diffuse_map, False, material::generation, material::id, INVALID_ID, KFATAL, kzero_memory(), MATERIAL_NAME_MAX_LENGTH, material::name, renderer_create_material(), string_ncopy(), texture_map::texture, texture_system_get_default_texture(), TEXTURE_USE_MAP_DIFFUSE, True, texture_map::use, and vec4_one().
Referenced by material_system_initialize().
destroy_material()
void destroy_material (material * m)
Destroys a material, freeing its resources.
Parameters
m Pointer to the material to be destroyed.
Definition at line 325 of file material_system.c.
References material::diffuse_map, material::generation, material::id, material::internal_id, INVALID_ID, KTRACE, kzero_memory(), material::name, texture::name, renderer_destroy_material(), texture_map::texture, and texture_system_release().
Referenced by material_system_release(), and material_system_shutdown().
load_configuration_file()
b8 load_configuration_file (const char * path, material_config * out_config)
Loads a material configuration from a file.
Parameters
path Path to the configuration file.
out_config Pointer to the material_config structure to be populated.
Returns
True if the configuration was loaded successfully, False otherwise.
Definition at line 364 of file material_system.c.
References material_config::diffuse_color, material_config::diffuse_map_name, False, FILE_MODE_READ, filesystem_close(), filesystem_open(), filesystem_read_line(), KERROR, KWARN, kzero_memory(), MATERIAL_NAME_MAX_LENGTH, material_config::name, string_index_of(), string_length(), string_mid(), string_ncopy(), string_to_vec4(), string_trim(), strings_equali(), TEXTURE_NAME_MAX_LENGTH, True, and vec4_one().
Referenced by material_system_acquire().
load_material()
b8 load_material (material_config config, material * m)
Loads a material based on the provided configuration.
Parameters
config Configuration for the material to be loaded.
m Pointer to the material structure to be populated.
Returns
True if the material was loaded successfully, False otherwise.
Definition at line 290 of file material_system.c.
References material::diffuse_color, material_config::diffuse_color, material::diffuse_map, material_config::diffuse_map_name, False, KERROR, KWARN, kzero_memory(), MATERIAL_NAME_MAX_LENGTH, material::name, material_config::name, renderer_create_material(), string_length(), string_ncopy(), texture_map::texture, texture_system_acquire(), texture_system_get_default_texture(), TEXTURE_USE_MAP_DIFFUSE, TEXTURE_USE_UNKNOWN, True, and texture_map::use.
Referenced by material_system_acquire_from_config().
material_system_acquire()
material * material_system_acquire (const char * name)
Acquires a material by name.
If the material is not already loaded, it will be created with default properties.
Parameters
name Name of the material to acquire.
Returns
Pointer to the acquired material, or NULL if acquisition failed.
Definition at line 169 of file material_system.c.
References KERROR, load_configuration_file(), material_system_acquire_from_config(), and string_format().
Referenced by create_geometry().
material_system_acquire_from_config()
material * material_system_acquire_from_config (material_config config)
Acquires a material based on the provided configuration.
If a material with the same name already exists, it will be returned. Otherwise, a new material will be created using the specified configuration.
Parameters
config Configuration for the material to be acquired or created.
Returns
Pointer to the acquired or newly created material, or NULL if acquisition failed.
Definition at line 190 of file material_system.c.
References material_reference::auto_release, material_config::auto_release, material_system_state::config, material_system_state::default_material, DEFAULT_MATERIAL_NAME, material::generation, material_reference::handle, hashtable_get(), hashtable_set(), material::id, INVALID_ID, KERROR, KFATAL, KTRACE, load_material(), material_system_config::max_material_count, material_config::name, material_reference::reference_count, material_system_state::registered_material_table, material_system_state::registered_materials, state_ptr, and strings_equali().
Referenced by material_system_acquire().
material_system_get_default()
material * material_system_get_default ()
Retrieves the default material used when a requested material is not found.
Returns
Pointer to the default material.
Definition at line 440 of file material_system.c.
References material_system_state::default_material, KFATAL, and state_ptr.
Referenced by create_default_geometry(), create_geometry(), and vulkan_backend_draw_geometry().
material_system_initialize()
b8 material_system_initialize (u64 * memory_requirement, void * state, material_system_config config)
Initializes the material system.
Parameters
memory_requirement Pointer to store the required memory size for the system state.
state Pointer to pre-allocated memory for the system state.
config Configuration options for the material system.
Returns
True if initialization was successful, False otherwise.
Definition at line 99 of file material_system.c.
References material_reference::auto_release, material_system_state::config, create_default_material(), False, material::generation, material_reference::handle, hashtable_create(), hashtable_fill(), material::id, material::internal_id, INVALID_ID, KFATAL, material_system_config::max_material_count, material_reference::reference_count, material_system_state::registered_material_table, material_system_state::registered_materials, state_ptr, and True.
Referenced by application_create().
material_system_release()
void material_system_release (const char * name)
Releases a material by name.
If the material was marked for auto-release, it will be freed when no longer in use.
Parameters
name Name of the material to release.
Definition at line 255 of file material_system.c.
References material_reference::auto_release, DEFAULT_MATERIAL_NAME, destroy_material(), False, material_reference::handle, hashtable_get(), hashtable_set(), INVALID_ID, KERROR, KTRACE, KWARN, material_reference::reference_count, material_system_state::registered_material_table, material_system_state::registered_materials, state_ptr, and strings_equali().
Referenced by destroy_geometry().
material_system_shutdown()
void material_system_shutdown (void * state)
Shuts down the material system, freeing all resources.
Parameters
state Pointer to the material system state.
Definition at line 151 of file material_system.c.
References material_system_state::config, material_system_state::default_material, destroy_material(), material::id, INVALID_ID, material_system_config::max_material_count, material_system_state::registered_materials, and state_ptr.
Referenced by application_run().
Variable Documentation
state_ptr
material_system_state* state_ptr = 0 static
Pointer to the internal state of the material system.
Definition at line 64 of file material_system.c.
Referenced by material_system_acquire_from_config(), material_system_get_default(), material_system_initialize(), material_system_release(), and material_system_shutdown().