Koru Game Engine: engine/src/platform/platform.h File Reference
platform.h File Reference
Platform abstraction layer interface.
#include "defines.h"
Data Structures
struct platform_state
Opaque state structure for the platform layer.
Typedefs
typedef struct platform_state platform_state
Opaque state structure for the platform layer.
Functions
b8 platform_startup (platform_state *plat_state, const char *application_name, i32 x, i32 y, i32 width, i32 height)
Initializes the platform layer.
void platform_shutdown (platform_state *plat_state)
Shuts down the platform layer.
b8 platform_pump_messages (platform_state *plat_state)
Processes messages/events from the operating system.
void * platform_allocate (u64 size, b8 aligned)
Allocates memory from the platform.
void platform_free (void *block, b8 aligned)
Frees a previously allocated block of memory.
void * platform_zero_memory (void *block, u64 size)
Fills a block of memory with zeros.
void * platform_copy_memory (void *dest, const void *source, u64 size)
Copies bytes from one memory block to another.
void * platform_set_memory (void *dest, i32 value, u64 size)
Fills a block of memory with a specific byte value.
void platform_console_write (const char *message, u8 colour)
Writes a message to the platform console with a given color.
void platform_console_write_error (const char *message, u8 colour)
Writes an error message to the platform console with a color.
f64 platform_get_absolute_time ()
Gets the current time in seconds since some arbitrary fixed point in the past.
void platform_sleep (u64 ms)
Suspends the calling thread for at least the specified number of milliseconds.
Detailed Description
Platform abstraction layer interface.
Defines the cross-platform API for:
Window creation and management
Input handling (keyboard, mouse)
Time and sleep functions
Memory allocation and manipulation
Implemented separately for each OS (e.g., Win32, Linux).
Definition in file platform.h.
Typedef Documentation
platform_state
typedef struct platform_state platform_state
Opaque state structure for the platform layer.
This struct holds internal platform-specific data that the implementation needs, such as window handles, device contexts, input state, etc.
The actual contents are defined privately in platform_*.c files.
Function Documentation
platform_allocate()
void * platform_allocate (u64 size, b8 aligned)
Allocates memory from the platform.
Parameters
size The number of bytes to allocate.
aligned Whether the allocation should be aligned for performance (e.g., SIMD).
Returns
A pointer to the allocated memory block.
Referenced by kallocate().
platform_console_write()
void platform_console_write (const char * message, u8 colour)
Writes a message to the platform console with a given color.
Useful for logging and debugging output.
Parameters
message The message to write.
colour A numeric identifier for the color (e.g., red, green, yellow).
Referenced by log_output().
platform_console_write_error()
void platform_console_write_error (const char * message, u8 colour)
Writes an error message to the platform console with a color.
Used specifically for error-level logs.
Parameters
message The error message to write.
colour A numeric identifier for the color.
Referenced by log_output().
platform_copy_memory()
void * platform_copy_memory (void * dest, const void * source, u64 size)
Copies bytes from one memory block to another.
Parameters
dest A pointer to the destination memory block.
source A pointer to the source memory block.
size The number of bytes to copy.
Returns
A pointer to the destination memory block.
Referenced by kcopy_memory().
platform_free()
void platform_free (void * block, b8 aligned)
Frees a previously allocated block of memory.
Parameters
block A pointer to the memory block to free.
aligned Whether the block was allocated with alignment.
Referenced by kfree().
platform_get_absolute_time()
f64 platform_get_absolute_time ()
Gets the current time in seconds since some arbitrary fixed point in the past.
Designed to be monotonic (never goes backward), suitable for measuring durations.
Returns
The current time in seconds.
Referenced by application_run(), clock_start(), and clock_update().
platform_pump_messages()
b8 platform_pump_messages (platform_state * plat_state)
Processes messages/events from the operating system.
Handles events like:
Keyboard input
Mouse movement and clicks
Window resizing
Close button click
Parameters
plat_state A pointer to the initialized platform_state struct.
Returns
TRUE if the application should continue running; FALSE if quit was requested.
Referenced by application_run().
platform_set_memory()
void * platform_set_memory (void * dest, i32 value, u64 size)
Fills a block of memory with a specific byte value.
Parameters
dest A pointer to the memory block.
value The byte value to set.
size The number of bytes to fill.
Returns
A pointer to the filled memory block.
Referenced by kset_memory().
platform_shutdown()
void platform_shutdown (platform_state * plat_state)
Shuts down the platform layer.
Cleans up:
Window resources
Input devices
Any allocated memory or threads
Parameters
plat_state A pointer to the initialized platform_state struct.
Referenced by application_run().
platform_sleep()
void platform_sleep (u64 ms)
Suspends the calling thread for at least the specified number of milliseconds.
This is a blocking call and should only be used when giving unused CPU time back to the OS.
Parameters
ms The number of milliseconds to sleep.
Referenced by application_run().
platform_startup()
b8 platform_startup (platform_state * plat_state, const char * application_name, i32 x, i32 y, i32 width, i32 height)
Initializes the platform layer.
Sets up:
Window creation
Input devices
Platform-specific memory and timing systems
Parameters
plat_state A pointer to an uninitialized platform_state struct.
application_name The name shown in the window title bar.
x X position of the window on the screen.
y Y position of the window on the screen.
width Width of the window client area.
height Height of the window client area.
Returns
TRUE if initialization was successful; FALSE otherwise.
Referenced by application_create().
platform_zero_memory()
void * platform_zero_memory (void * block, u64 size)
Fills a block of memory with zeros.
Parameters
block A pointer to the memory block.
size The number of bytes to zero out.
Returns
A pointer to the zeroed memory block.
Referenced by initialize_memory(), kallocate(), and kzero_memory().