Koru Game Engine: engine/src/renderer/renderer_backend.c File Reference
renderer_backend.c File Reference
Implementation of renderer backend creation and destruction logic.
#include "core/logger.h"
#include "renderer_backend.h"
#include "vulkan/vulkan_backend.h"
Functions
b8 renderer_backend_create (renderer_backend_type type, renderer_backend *out_renderer_backend)
Creates and initializes a renderer backend of the specified type.
void renderer_backend_destroy (renderer_backend *renderer_backend)
Destroys a renderer backend by clearing all function pointers.
Detailed Description
Implementation of renderer backend creation and destruction logic.
This file defines the functions used to instantiate and destroy specific rendering backends, such as Vulkan. It maps function pointers in the renderer_backend structure to the appropriate implementation functions for the selected backend type.
Definition in file renderer_backend.c.
Function Documentation
renderer_backend_create()
b8 renderer_backend_create (renderer_backend_type type, renderer_backend * out_renderer_backend)
Creates and initializes a renderer backend of the specified type.
Creates a rendering backend of the specified type.
This function sets up the function table for the given backend type and initializes its state. Currently only supports Vulkan, but can be extended to support OpenGL, DirectX, etc.
Parameters
type The type of renderer backend to create.
plat_state A pointer to the platform-specific state.
out_renderer_backend A pointer to a renderer_backend structure to populate.
Returns
True if the backend was successfully created; otherwise False.
Definition at line 25 of file renderer_backend.c.
References False, KERROR, True, vulkan_backend_update_object(), vulkan_renderer_backend_begin_frame(), vulkan_renderer_backend_end_frame(), vulkan_renderer_backend_initialize(), vulkan_renderer_backend_on_resized(), vulkan_renderer_backend_shutdown(), vulkan_renderer_create_texture(), vulkan_renderer_destroy_texture(), and vulkan_renderer_update_global_state().
Referenced by renderer_system_initialize().
renderer_backend_destroy()
void renderer_backend_destroy (renderer_backend * renderer_backend)
Destroys a renderer backend by clearing all function pointers.
Destroys a previously created rendering backend.
This does not free memory or clean up internal resources — it simply resets the function pointers to NULL. Any backend-specific cleanup should be done before calling this function.
Parameters
renderer_backend A pointer to the renderer backend instance to destroy.
Definition at line 55 of file renderer_backend.c.