Koru Game Engine: engine/src/renderer/renderer_frontend.h File Reference
renderer_frontend.h File Reference
Frontend interface for the rendering system.
#include "renderer_types.inl"
Functions
b8 renderer_system_initialize (u64 *memory_requirement, void *state, const char *application_name)
Initializes the rendering system.
void renderer_system_shutdown (void *state)
Shuts down the rendering system.
void renderer_on_resized (u16 width, u16 height)
Handles window resize events.
b8 renderer_draw_frame (render_packet *packet)
Renders a single frame using the provided packet data.
void renderer_set_view (mat4 view)
Sets the current view matrix for rendering.
void renderer_create_texture (const char *name, i32 width, i32 height, i32 channel_count, const u8 *pixels, b8 has_transparency, struct texture *out_texture)
Creates a texture resource from raw pixel data.
void renderer_destroy_texture (struct texture *texture)
Destroys a texture resource and frees associated GPU memory.
b8 renderer_create_material (struct material *material)
Creates a material resource.
void renderer_destroy_material (struct material *material)
Destroys a material resource and frees associated resources.
b8 renderer_create_geometry (geometry *geometry, u32 vertex_count, const vertex_3d *vertices, u32 index_count, const u32 *indices)
Creates a geometry resource from vertex and index data.
void renderer_destroy_geometry (geometry *geometry)
Destroys a geometry resource and frees associated GPU memory.
Detailed Description
Frontend interface for the rendering system.
This module provides the main entry points for initializing, shutting down, and driving the rendering system. It abstracts away the specific backend (e.g., Vulkan, OpenGL) and offers a simple API to be used by the core engine.
The frontend works with render packets and handles frame updates, resizing, and drawing operations.
Definition in file renderer_frontend.h.
Function Documentation
renderer_create_geometry()
b8 renderer_create_geometry (geometry * geometry, u32 vertex_count, const vertex_3d * vertices, u32 index_count, const u32 * indices)
Creates a geometry resource from vertex and index data.
This function uploads the provided vertex and index data to the GPU and creates a geometry object that can be used in rendering operations.
Parameters
geometry Pointer to the geometry structure to be filled out.
vertex_count Number of vertices in the geometry.
vertices Pointer to an array of vertices defining the geometry.
index_count Number of indices in the geometry.
indices Pointer to an array of indices defining the geometry.
Returns
True if the geometry was created successfully; otherwise False.
Definition at line 209 of file renderer_frontend.c.
References renderer_system_state::backend, and state_ptr.
Referenced by create_default_geometry(), and create_geometry().
renderer_create_material()
b8 renderer_create_material (struct material * material)
Creates a material resource.
This function initializes a material with the provided properties and prepares it for use in rendering operations.
Parameters
material Pointer to the material structure to be filled out.
Returns
True if the material was created successfully; otherwise False.
Definition at line 202 of file renderer_frontend.c.
References renderer_system_state::backend, and state_ptr.
Referenced by create_default_material(), and load_material().
renderer_create_texture()
void renderer_create_texture (const char * name, i32 width, i32 height, i32 channel_count, const u8 * pixels, b8 has_transparency, struct texture * out_texture)
Creates a texture resource from raw pixel data.
This function uploads the provided pixel data to the GPU and creates a texture object that can be used in rendering operations.
Parameters
name Name of the texture (for identification/debugging).
width Width of the texture in pixels.
height Height of the texture in pixels.
channel_count Number of color channels (e.g., 3 for RGB, 4 for RGBA).
pixels Pointer to the raw pixel data.
has_transparency Whether the texture contains transparency (alpha channel).
out_texture Pointer to the texture structure to be filled out.
Definition at line 187 of file renderer_frontend.c.
References renderer_system_state::backend, and state_ptr.
Referenced by create_default_textures(), and load_texture().
renderer_destroy_geometry()
void renderer_destroy_geometry (geometry * geometry)
Destroys a geometry resource and frees associated GPU memory.
Parameters
geometry Pointer to the geometry to be destroyed.
Definition at line 213 of file renderer_frontend.c.
References renderer_system_state::backend, and state_ptr.
Referenced by destroy_geometry().
renderer_destroy_material()
void renderer_destroy_material (struct material * material)
Destroys a material resource and frees associated resources.
Parameters
material Pointer to the material to be destroyed.
Definition at line 205 of file renderer_frontend.c.
References renderer_system_state::backend, and state_ptr.
Referenced by destroy_material().
renderer_destroy_texture()
void renderer_destroy_texture (struct texture * texture)
Destroys a texture resource and frees associated GPU memory.
Parameters
texture Pointer to the texture to be destroyed.
Definition at line 198 of file renderer_frontend.c.
References renderer_system_state::backend, and state_ptr.
Referenced by destroy_default_textures(), destroy_texture(), load_texture(), and texture_system_shutdown().
renderer_draw_frame()
b8 renderer_draw_frame (render_packet * packet)
Renders a single frame using the provided packet data.
Begins the frame, submits draw commands, and ends the frame. Called once per frame.
Parameters
packet A pointer to the render packet containing frame-specific data.
Returns
True if the frame was drawn successfully; otherwise False.
Renders a single frame using the provided packet data.
Begins the frame, executes draw commands (not yet implemented here), and ends the frame. Called once per frame by the engine.
Parameters
packet A pointer to the render packet containing frame-specific data.
Returns
True if the frame was drawn successfully; otherwise False.
Definition at line 154 of file renderer_frontend.c.
References renderer_system_state::backend, False, KERROR, renderer_system_state::projection, renderer_begin_frame(), renderer_end_frame(), state_ptr, True, vec3_zero(), vec4_one(), and renderer_system_state::view.
Referenced by application_run().
renderer_on_resized()
void renderer_on_resized (u16 width, u16 height)
Handles window resize events.
Notifies the renderer that the window dimensions have changed and triggers any necessary internal updates such as recreating the swapchain or adjusting viewport/scissor settings.
Parameters
width New width of the window.
height New height of the window.
Definition at line 136 of file renderer_frontend.c.
References renderer_system_state::backend, deg_to_rad(), renderer_system_state::far_clip, KWARN, mat4_perspective(), renderer_system_state::near_clip, renderer_system_state::projection, and state_ptr.
Referenced by application_on_resized().
renderer_set_view()
void renderer_set_view (mat4 view)
Sets the current view matrix for rendering.
This function updates the view matrix used in the rendering pipeline.
Parameters
view The new view matrix to set.
Definition at line 183 of file renderer_frontend.c.
References state_ptr, and renderer_system_state::view.
Referenced by game_update().
renderer_system_initialize()
b8 renderer_system_initialize (u64 * memory_requirement, void * state, const char * application_name)
Initializes the rendering system.
Sets up the appropriate rendering backend (e.g., Vulkan), creates necessary context, device, swapchain, etc. based on application requirements.
Parameters
application_name Name of the application using the renderer.
plat_state A pointer to the platform-specific state.
Returns
True if initialization was successful; otherwise False.
Definition at line 63 of file renderer_frontend.c.
References renderer_system_state::backend, deg_to_rad(), False, renderer_system_state::far_clip, KFATAL, mat4_inverse(), mat4_perspective(), mat4_translation(), renderer_system_state::near_clip, renderer_system_state::projection, renderer_backend_create(), state_ptr, True, and renderer_system_state::view.
Referenced by application_create().
renderer_system_shutdown()
void renderer_system_shutdown (void * state)
Shuts down the rendering system.
Cleans up all resources allocated during initialization, including devices, command pools, buffers, and synchronization primitives.
Definition at line 92 of file renderer_frontend.c.
References renderer_system_state::backend, and state_ptr.
Referenced by application_run().