Koru Game Engine: engine/src/renderer/renderer_backend.h File Reference
renderer_backend.h File Reference
Renderer backend creation and destruction interface.
#include "renderer_types.inl"
Functions
b8 renderer_backend_create (renderer_backend_type type, struct platform_state *plat_state, renderer_backend *out_renderer_backend)
Creates a rendering backend of the specified type.
void renderer_backend_destroy (renderer_backend *renderer_backend)
Destroys a previously created rendering backend.
Detailed Description
Renderer backend creation and destruction interface.
This module provides functions to instantiate and destroy specific rendering backends such as Vulkan, OpenGL, or DirectX. It works with the renderer_backend structure to provide a unified function table-based API across different graphics APIs.
Definition in file renderer_backend.h.
Function Documentation
renderer_backend_create()
b8 renderer_backend_create (renderer_backend_type type, struct platform_state * plat_state, renderer_backend * out_renderer_backend)
Creates a rendering backend of the specified type.
Initializes function pointers and internal data for the requested backend. This allows the engine to interact with different rendering APIs through a common interface.
Parameters
type The type of renderer backend to create (e.g., Vulkan, OpenGL, DirectX).
plat_state A pointer to the platform-specific state.
out_renderer_backend A pointer to a renderer_backend structure to be populated.
Returns
TRUE if the backend was successfully created; otherwise FALSE.
Creates a rendering backend of the specified type.
This function sets up the function table for the given backend type and initializes its state. Currently only supports Vulkan, but can be extended to support OpenGL, DirectX, etc.
Parameters
type The type of renderer backend to create.
plat_state A pointer to the platform-specific state.
out_renderer_backend A pointer to a renderer_backend structure to populate.
Returns
TRUE if the backend was successfully created; otherwise FALSE.
Definition at line 25 of file renderer_backend.c.
References FALSE, KERROR, TRUE, vulkan_renderer_backend_begin_frame(), vulkan_renderer_backend_end_frame(), vulkan_renderer_backend_initialize(), vulkan_renderer_backend_on_resized(), and vulkan_renderer_backend_shutdown().
Referenced by renderer_initialize().
renderer_backend_destroy()
void renderer_backend_destroy (renderer_backend * renderer_backend)
Destroys a previously created rendering backend.
Cleans up any resources associated with the backend and resets its state.
Parameters
renderer_backend A pointer to the renderer backend instance to destroy.
Destroys a previously created rendering backend.
This does not free memory or clean up internal resources — it simply resets the function pointers to NULL. Any backend-specific cleanup should be done before calling this function.
Parameters
renderer_backend A pointer to the renderer backend instance to destroy.
Definition at line 54 of file renderer_backend.c.