Koru Game Engine: engine/src/renderer/renderer_frontend.c File Reference
renderer_frontend.c File Reference
Frontend implementation for the Koru rendering system.
#include "renderer_frontend.h"
#include "renderer_backend.h"
#include "core/logger.h"
#include "core/kmemory.h"
#include "math/kmath.h"
#include "resources/resource_types.h"
#include "core/kstring.h"
#include "core/event.h"
#include "vendor/stb_image.h"
Data Structures
struct renderer_system_state
Represents the state of the rendering system.
Macros
#define STB_IMAGE_IMPLEMENTATION
#define TEX_DIMENSIONS 256
#define CHANNELS 4
Bits per pixel RGBA.
#define PIXEL_COUNT TEX_DIMENSIONS* TEX_DIMENSIONS
Total number of pixels in the texture.
Typedefs
typedef struct renderer_system_state renderer_system_state
Functions
void create_texture (texture *t)
Initializes a texture structure to default values.
b8 load_texture (const char *texture_name, texture *t)
Loads a texture from file and uploads it to the GPU.
b8 event_on_debug_event (u16 code, void *sender, void *listener_inst, event_context data)
Event handler for debug events to cycle through test textures.
b8 renderer_system_initialize (u64 *memory_requirement, void *state, const char *application_name)
Initializes the rendering system.
void renderer_system_shutdown (void *state)
Shuts down the rendering system.
b8 renderer_begin_frame (f32 delta_time)
Begins a new rendering frame.
b8 renderer_end_frame (f32 delta_time)
Ends the current rendering frame.
void renderer_on_resized (u16 width, u16 height)
Handles window resize events.
b8 renderer_draw_frame (render_packet *packet)
Performs the complete frame rendering process.
void renderer_set_view (mat4 view)
Sets the current view matrix for rendering.
void renderer_create_texture (const char *name, b8 auto_release, i32 width, i32 height, i32 channel_count, const u8 *pixels, b8 has_transparency, struct texture *out_texture)
Creates a texture resource from raw pixel data.
void renderer_destroy_texture (struct texture *texture)
Destroys a texture resource and frees associated GPU memory.
Variables
static renderer_system_state * state_ptr
Detailed Description
Frontend implementation for the Koru rendering system.
This file provides the implementation for the main rendering interface functions, abstracting away the specific backend (e.g., Vulkan, OpenGL) from the rest of the engine. It manages initialization, frame lifecycle, and drawing operations using a render packet.
Definition in file renderer_frontend.c.
Macro Definition Documentation
CHANNELS
#define CHANNELS 4
Bits per pixel RGBA.
Definition at line 20 of file renderer_frontend.c.
PIXEL_COUNT
#define PIXEL_COUNT TEX_DIMENSIONS* TEX_DIMENSIONS
Total number of pixels in the texture.
Definition at line 22 of file renderer_frontend.c.
STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
Definition at line 14 of file renderer_frontend.c.
TEX_DIMENSIONS
#define TEX_DIMENSIONS 256
Definition at line 18 of file renderer_frontend.c.
Typedef Documentation
renderer_system_state
typedef struct renderer_system_state renderer_system_state
Function Documentation
create_texture()
void create_texture (texture * t)
Initializes a texture structure to default values.
This function sets the fields of the provided texture structure to safe default values, ensuring it is in a known state before use.
Parameters
t Pointer to the texture structure to initialize.
Definition at line 90 of file renderer_frontend.c.
References texture::generation, INVALID_ID, and kzero_memory().
Referenced by renderer_system_initialize().
event_on_debug_event()
b8 event_on_debug_event (u16 code, void * sender, void * listener_inst, event_context data)
Event handler for debug events to cycle through test textures.
This function is a temporary event handler that listens for a specific debug event and cycles through a set of predefined textures for testing purposes.
Parameters
code The event code.
sender Pointer to the event sender.
listener_inst Pointer to the listener instance (should be the renderer state).
data Event context data (not used here).
Returns
True if the event was handled; otherwise False.
Definition at line 202 of file renderer_frontend.c.
References load_texture(), state_ptr, renderer_system_state::test_diffuse, and True.
Referenced by renderer_system_initialize(), and renderer_system_shutdown().
load_texture()
b8 load_texture (const char * texture_name, texture * t)
Loads a texture from file and uploads it to the GPU.
This function uses stb_image to load image data from disk, creates a texture resource, and uploads it to the GPU via the renderer backend.
Parameters
texture_name Name of the texture file (without extension).
t Pointer to the texture structure to be filled out.
Returns
True if the texture was loaded and created successfully; otherwise False.
Definition at line 105 of file renderer_frontend.c.
References texture::channel_count, False, texture::generation, texture::height, INVALID_ID, KINFO, KWARN, renderer_create_texture(), renderer_destroy_texture(), stbi_failure_reason(), stbi_image_free(), stbi_load(), stbi_set_flip_vertically_on_load(), string_format(), True, and texture::width.
Referenced by event_on_debug_event().
renderer_begin_frame()
b8 renderer_begin_frame (f32 delta_time)
Begins a new rendering frame.
This typically involves acquiring a swapchain image, setting up command buffers, and preparing for rendering operations.
Parameters
delta_time Time in seconds since the last frame.
Returns
True if the frame was successfully started; otherwise False.
Definition at line 325 of file renderer_frontend.c.
References renderer_system_state::backend, False, and state_ptr.
Referenced by renderer_draw_frame().
renderer_create_texture()
void renderer_create_texture (const char * name, b8 auto_release, i32 width, i32 height, i32 channel_count, const u8 * pixels, b8 has_transparency, struct texture * out_texture)
Creates a texture resource from raw pixel data.
This function uploads the provided pixel data to the GPU and creates a texture object that can be used in rendering operations.
Parameters
name Name of the texture (for identification/debugging).
auto_release Whether the texture should be automatically released when no longer needed.
width Width of the texture in pixels.
height Height of the texture in pixels.
channel_count Number of color channels (e.g., 3 for RGB, 4 for RGBA).
pixels Pointer to the raw pixel data.
has_transparency Whether the texture contains transparency (alpha channel).
out_texture Pointer to the texture structure to be filled out.
Definition at line 411 of file renderer_frontend.c.
References renderer_system_state::backend, and state_ptr.
Referenced by load_texture(), and renderer_system_initialize().
renderer_destroy_texture()
void renderer_destroy_texture (struct texture * texture)
Destroys a texture resource and frees associated GPU memory.
Parameters
texture Pointer to the texture to be destroyed.
Definition at line 423 of file renderer_frontend.c.
References renderer_system_state::backend, and state_ptr.
Referenced by load_texture(), and renderer_system_shutdown().
renderer_draw_frame()
b8 renderer_draw_frame (render_packet * packet)
Performs the complete frame rendering process.
Renders a single frame using the provided packet data.
Begins the frame, executes draw commands (not yet implemented here), and ends the frame. Called once per frame by the engine.
Parameters
packet A pointer to the render packet containing frame-specific data.
Returns
True if the frame was drawn successfully; otherwise False.
TO-DO: Add actual object ID
Definition at line 370 of file renderer_frontend.c.
References renderer_system_state::backend, False, KERROR, mat4_translation(), renderer_system_state::projection, renderer_begin_frame(), renderer_end_frame(), state_ptr, renderer_system_state::test_diffuse, True, vec3_zero(), vec4_one(), and renderer_system_state::view.
Referenced by application_run().
renderer_end_frame()
b8 renderer_end_frame (f32 delta_time)
Ends the current rendering frame.
This usually involves submitting command buffers, presenting the rendered image, and cleaning up per-frame resources.
Parameters
delta_time Time in seconds since the last frame.
Returns
True if the frame was successfully ended; otherwise False.
Definition at line 342 of file renderer_frontend.c.
References renderer_system_state::backend, False, and state_ptr.
Referenced by renderer_draw_frame().
renderer_on_resized()
void renderer_on_resized (u16 width, u16 height)
Handles window resize events.
Notifies the renderer that the window dimensions have changed and triggers any necessary internal updates such as recreating the swapchain or adjusting viewport/scissor settings.
Parameters
width New width of the window.
height New height of the window.
Definition at line 352 of file renderer_frontend.c.
References renderer_system_state::backend, deg_to_rad(), renderer_system_state::far_clip, KWARN, mat4_perspective(), renderer_system_state::near_clip, renderer_system_state::projection, and state_ptr.
Referenced by application_on_resized().
renderer_set_view()
void renderer_set_view (mat4 view)
Sets the current view matrix for rendering.
This function updates the view matrix used in the rendering pipeline.
Parameters
view The new view matrix to set.
Definition at line 407 of file renderer_frontend.c.
References state_ptr, and renderer_system_state::view.
Referenced by game_update().
renderer_system_initialize()
b8 renderer_system_initialize (u64 * memory_requirement, void * state, const char * application_name)
Initializes the rendering system.
Sets up the appropriate rendering backend (e.g., Vulkan), creates necessary context, device, swapchain, etc. based on application requirements.
Parameters
application_name Name of the application using the renderer.
plat_state A pointer to the platform-specific state.
Returns
True if initialization was successful; otherwise False.
Definition at line 219 of file renderer_frontend.c.
References renderer_system_state::backend, CHANNELS, create_texture(), renderer_system_state::default_texture, deg_to_rad(), EVENT_CODE_DEBUG0, event_on_debug_event(), event_register(), False, renderer_system_state::far_clip, texture::generation, INVALID_ID, KFATAL, kset_memory(), KTRACE, mat4_inverse(), mat4_perspective(), mat4_translation(), renderer_system_state::near_clip, PIXEL_COUNT, renderer_system_state::projection, renderer_backend_create(), renderer_create_texture(), state_ptr, renderer_system_state::test_diffuse, TEX_DIMENSIONS, True, and renderer_system_state::view.
Referenced by application_create().
renderer_system_shutdown()
void renderer_system_shutdown (void * state)
Shuts down the rendering system.
Cleans up all resources allocated during initialization, including devices, command pools, buffers, and synchronization primitives.
Definition at line 300 of file renderer_frontend.c.
References renderer_system_state::backend, renderer_system_state::default_texture, EVENT_CODE_DEBUG0, event_on_debug_event(), event_unregister(), renderer_destroy_texture(), state_ptr, and renderer_system_state::test_diffuse.
Referenced by application_run().
Variable Documentation
state_ptr
renderer_system_state* state_ptr static
Definition at line 80 of file renderer_frontend.c.
Referenced by event_on_debug_event(), renderer_begin_frame(), renderer_create_texture(), renderer_destroy_texture(), renderer_draw_frame(), renderer_end_frame(), renderer_on_resized(), renderer_set_view(), renderer_system_initialize(), and renderer_system_shutdown().