Koru Game Engine: engine/src/systems/texture_system.h File Reference
texture_system.h File Reference
Texture management system.
#include "renderer/renderer_types.inl"
Data Structures
struct texture_reference
Reference to a texture in the system.
struct texture_system_config
Configuration for the texture system.
Macros
#define DEFAULT_TEXTURE_NAME "default"
Default texture name used when a requested texture is not found.
Typedefs
typedef struct texture_reference texture_reference
typedef struct texture_system_config texture_system_config
Functions
b8 texture_system_initialize (u64 *memory_requirement, void *state, texture_system_config config)
Initializes the texture system.
void texture_system_shutdown (void *state)
Shuts down the texture system, freeing all resources.
texture * texture_system_acquire (const char *name, b8 auto_release)
Acquires a texture by name.
void texture_system_release (const char *name)
Releases a texture by name.
texture * texture_system_get_default_texture ()
Retrieves the default texture.
Detailed Description
Texture management system.
This module provides functionality to manage texture resources within the engine. It supports loading, acquiring, and releasing textures, as well as automatic cleanup of unused resources.
Usage:
Initialize the texture system with texture_system_initialize(), providing configuration options.
Acquire textures by name using texture_system_acquire(). If the texture is not already loaded, it will be loaded from disk.
Release textures using texture_system_release(). If a texture was marked for auto-release, it will be freed when no longer in use.
Shutdown the texture system with texture_system_shutdown() to free all resources.
Definition in file texture_system.h.
Macro Definition Documentation
DEFAULT_TEXTURE_NAME
#define DEFAULT_TEXTURE_NAME "default"
Default texture name used when a requested texture is not found.
Definition at line 25 of file texture_system.h.
Typedef Documentation
texture_reference
typedef struct texture_reference texture_reference
texture_system_config
typedef struct texture_system_config texture_system_config
Function Documentation
texture_system_acquire()
texture * texture_system_acquire (const char * name, b8 auto_release)
Acquires a texture by name.
If the texture is not already loaded, it will be loaded from disk. If the texture cannot be found, the default texture will be returned.
Parameters
name Name of the texture to acquire.
auto_release If true, the texture will be automatically released when no longer in use.
Returns
Pointer to the acquired texture, or NULL if acquisition failed.
Definition at line 187 of file texture_system.c.
References texture_reference::auto_release, texture_system_state::config, texture_system_state::default_texture, DEFAULT_TEXTURE_NAME, texture_reference::handle, hashtable_get(), hashtable_set(), texture::id, INVALID_ID, KERROR, KFATAL, KTRACE, KWARN, load_texture(), texture_system_config::max_texture_count, texture_reference::reference_count, texture_system_state::registered_texture_table, texture_system_state::registered_textures, state_ptr, and strings_equali().
Referenced by event_on_debug_event(), and load_material().
texture_system_get_default_texture()
texture * texture_system_get_default_texture ()
Retrieves the default texture.
The default texture is used when a requested texture cannot be found.
Returns
Pointer to the default texture.
Definition at line 283 of file texture_system.c.
References texture_system_state::default_texture, KERROR, and state_ptr.
Referenced by create_default_material(), event_on_debug_event(), load_material(), and vulkan_material_shader_apply_material().
texture_system_initialize()
b8 texture_system_initialize (u64 * memory_requirement, void * state, texture_system_config config)
Initializes the texture system.
Parameters
memory_requirement Pointer to store the required memory size for the texture system.
state Pointer to pre-allocated memory for the texture system state.
config Configuration options for the texture system.
Returns
Returns true if initialization was successful, false otherwise.
Definition at line 122 of file texture_system.c.
References texture_reference::auto_release, texture_system_state::config, create_default_textures(), False, texture::generation, texture_reference::handle, hashtable_create(), hashtable_fill(), texture::id, INVALID_ID, KFATAL, texture_system_config::max_texture_count, texture_reference::reference_count, texture_system_state::registered_texture_table, texture_system_state::registered_textures, state_ptr, and True.
Referenced by application_create().
texture_system_release()
void texture_system_release (const char * name)
Releases a texture by name.
If the texture was marked for auto-release, it will be freed when no longer in use.
Parameters
name Name of the texture to release.
Definition at line 243 of file texture_system.c.
References texture_reference::auto_release, DEFAULT_TEXTURE_NAME, destroy_texture(), False, texture_reference::handle, hashtable_get(), hashtable_set(), INVALID_ID, KERROR, KTRACE, KWARN, texture_reference::reference_count, texture_system_state::registered_texture_table, texture_system_state::registered_textures, state_ptr, string_ncopy(), strings_equali(), and TEXTURE_NAME_MAX_LENGTH.
Referenced by destroy_material(), and event_on_debug_event().
texture_system_shutdown()
void texture_system_shutdown (void * state)
Shuts down the texture system, freeing all resources.
Parameters
state Pointer to the texture system state to be shut down.
Definition at line 171 of file texture_system.c.
References texture_system_state::config, destroy_default_textures(), texture::generation, INVALID_ID, texture_system_config::max_texture_count, texture_system_state::registered_textures, renderer_destroy_texture(), and state_ptr.
Referenced by application_run().