Koru Game Engine: engine/src/systems/texture_system.c File Reference
texture_system.c File Reference
Implementation of the texture system for managing textures in the Koru engine.
#include "texture_system.h"
#include "core/logger.h"
#include "core/kstring.h"
#include "core/kmemory.h"
#include "containers/hashtable.h"
#include "renderer/renderer_frontend.h"
#include "vendor/stb_image.h"
Data Structures
struct texture_system_state
Macros
#define STB_IMAGE_IMPLEMENTATION
#define TEX_DIMENSIONS 256
#define CHANNELS 4
Bits per pixel RGBA.
#define PIXEL_COUNT TEX_DIMENSIONS* TEX_DIMENSIONS
Total number of pixels in the texture.
Typedefs
typedef struct texture_system_state texture_system_state
Functions
b8 create_default_textures (texture_system_state *state)
Creates default textures for the texture system.
void destroy_default_textures (texture_system_state *state)
Destroys the default textures created for the texture system.
b8 load_texture (const char *texture_name, texture *t)
Loads a texture from file and initializes the texture structure.
void destroy_texture (texture *t)
Destroys a texture and releases its resources.
b8 texture_system_initialize (u64 *memory_requirement, void *state, texture_system_config config)
Initializes the texture system.
void texture_system_shutdown (void *state)
Shuts down the texture system, freeing all resources.
texture * texture_system_acquire (const char *name, b8 auto_release)
Acquires a texture by name.
void texture_system_release (const char *name)
Releases a texture by name.
texture * texture_system_get_default_texture ()
Retrieves the default texture.
Variables
static texture_system_state * state_ptr = 0
Pointer to the global texture system state.
Detailed Description
Implementation of the texture system for managing textures in the Koru engine.
This module provides functionality to manage texture resources within the engine. It supports loading, acquiring, and releasing textures, as well as automatic cleanup of unused resources.
Usage:
Initialize the texture system with texture_system_initialize(), providing configuration options.
Acquire textures by name using texture_system_acquire(). If the texture is not already loaded, it will be loaded from disk.
Release textures using texture_system_release(). If a texture was marked for auto-release, it will be freed when no longer in use.
Shutdown the texture system with texture_system_shutdown() to free all resources.
Responsibilities:
Initialize the texture system with texture_system_initialize(), providing configuration options.
Acquire textures by name using texture_system_acquire(). If the texture is not already loaded, it will be loaded from disk.
Release textures using texture_system_release(). If a texture was marked for auto-release, it will be freed when no longer in use.
Shutdown the texture system with texture_system_shutdown() to free all resources.
Definition in file texture_system.c.
Macro Definition Documentation
CHANNELS
#define CHANNELS 4
Bits per pixel RGBA.
Definition at line 16 of file texture_system.c.
PIXEL_COUNT
#define PIXEL_COUNT TEX_DIMENSIONS* TEX_DIMENSIONS
Total number of pixels in the texture.
Definition at line 18 of file texture_system.c.
STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
Definition at line 11 of file texture_system.c.
TEX_DIMENSIONS
#define TEX_DIMENSIONS 256
Definition at line 14 of file texture_system.c.
Typedef Documentation
texture_system_state
typedef struct texture_system_state texture_system_state
Function Documentation
create_default_textures()
b8 create_default_textures (texture_system_state * state)
Creates default textures for the texture system.
This function initializes the default textures used by the system, such as a placeholder texture for when no texture is specified.
Parameters
state Pointer to the texture system state.
Returns
True if default textures were created successfully; otherwise False.
Definition at line 292 of file texture_system.c.
References texture::channel_count, CHANNELS, texture_system_state::default_texture, DEFAULT_TEXTURE_NAME, False, texture::generation, texture::has_transparency, texture::height, INVALID_ID, kset_memory(), KTRACE, texture::name, PIXEL_COUNT, renderer_create_texture(), string_ncopy(), TEX_DIMENSIONS, TEXTURE_NAME_MAX_LENGTH, True, and texture::width.
Referenced by texture_system_initialize().
destroy_default_textures()
void destroy_default_textures (texture_system_state * state)
Destroys the default textures created for the texture system.
Parameters
state Pointer to the texture system state.
Definition at line 335 of file texture_system.c.
References texture_system_state::default_texture, and renderer_destroy_texture().
Referenced by texture_system_shutdown().
destroy_texture()
void destroy_texture (texture * t)
Destroys a texture and releases its resources.
Parameters
t Pointer to the texture to be destroyed.
Definition at line 418 of file texture_system.c.
References texture::generation, texture::id, INVALID_ID, kzero_memory(), texture::name, renderer_destroy_texture(), and TEXTURE_NAME_MAX_LENGTH.
Referenced by texture_system_release().
load_texture()
b8 load_texture (const char * texture_name, texture * t)
Loads a texture from file and initializes the texture structure.
Parameters
texture_name The name of the texture file to load.
t Pointer to the texture structure to be filled out.
Returns
True if the texture was loaded successfully; otherwise False.
Definition at line 341 of file texture_system.c.
References texture::channel_count, False, texture::generation, texture::height, INVALID_ID, KWARN, renderer_create_texture(), renderer_destroy_texture(), stbi_failure_reason(), stbi_image_free(), stbi_load(), stbi_set_flip_vertically_on_load(), string_format(), True, and texture::width.
Referenced by texture_system_acquire().
texture_system_acquire()
texture * texture_system_acquire (const char * name, b8 auto_release)
Acquires a texture by name.
If the texture is not already loaded, it will be loaded from disk. If the texture cannot be found, the default texture will be returned.
Parameters
name Name of the texture to acquire.
auto_release If true, the texture will be automatically released when no longer in use.
Returns
Pointer to the acquired texture, or NULL if acquisition failed.
Definition at line 187 of file texture_system.c.
References texture_reference::auto_release, texture_system_state::config, texture_system_state::default_texture, DEFAULT_TEXTURE_NAME, texture_reference::handle, hashtable_get(), hashtable_set(), texture::id, INVALID_ID, KERROR, KFATAL, KTRACE, KWARN, load_texture(), texture_system_config::max_texture_count, texture_reference::reference_count, texture_system_state::registered_texture_table, texture_system_state::registered_textures, state_ptr, and strings_equali().
Referenced by event_on_debug_event(), and load_material().
texture_system_get_default_texture()
texture * texture_system_get_default_texture ()
Retrieves the default texture.
The default texture is used when a requested texture cannot be found.
Returns
Pointer to the default texture.
Definition at line 283 of file texture_system.c.
References texture_system_state::default_texture, KERROR, and state_ptr.
Referenced by create_default_material(), event_on_debug_event(), load_material(), and vulkan_material_shader_apply_material().
texture_system_initialize()
b8 texture_system_initialize (u64 * memory_requirement, void * state, texture_system_config config)
Initializes the texture system.
Parameters
memory_requirement Pointer to store the required memory size for the texture system.
state Pointer to pre-allocated memory for the texture system state.
config Configuration options for the texture system.
Returns
Returns true if initialization was successful, false otherwise.
Definition at line 122 of file texture_system.c.
References texture_reference::auto_release, texture_system_state::config, create_default_textures(), False, texture::generation, texture_reference::handle, hashtable_create(), hashtable_fill(), texture::id, INVALID_ID, KFATAL, texture_system_config::max_texture_count, texture_reference::reference_count, texture_system_state::registered_texture_table, texture_system_state::registered_textures, state_ptr, and True.
Referenced by application_create().
texture_system_release()
void texture_system_release (const char * name)
Releases a texture by name.
If the texture was marked for auto-release, it will be freed when no longer in use.
Parameters
name Name of the texture to release.
Definition at line 243 of file texture_system.c.
References texture_reference::auto_release, DEFAULT_TEXTURE_NAME, destroy_texture(), False, texture_reference::handle, hashtable_get(), hashtable_set(), INVALID_ID, KERROR, KTRACE, KWARN, texture_reference::reference_count, texture_system_state::registered_texture_table, texture_system_state::registered_textures, state_ptr, string_ncopy(), strings_equali(), and TEXTURE_NAME_MAX_LENGTH.
Referenced by destroy_material(), and event_on_debug_event().
texture_system_shutdown()
void texture_system_shutdown (void * state)
Shuts down the texture system, freeing all resources.
Parameters
state Pointer to the texture system state to be shut down.
Definition at line 171 of file texture_system.c.
References texture_system_state::config, destroy_default_textures(), texture::generation, INVALID_ID, texture_system_config::max_texture_count, texture_system_state::registered_textures, renderer_destroy_texture(), and state_ptr.
Referenced by application_run().
Variable Documentation
state_ptr
texture_system_state* state_ptr = 0 static
Pointer to the global texture system state.
Definition at line 120 of file texture_system.c.
Referenced by texture_system_acquire(), texture_system_get_default_texture(), texture_system_initialize(), texture_system_release(), and texture_system_shutdown().