Koru Game Engine: engine/src/renderer/vulkan/shaders/vulkan_object_shader.c File Reference
vulkan_object_shader.c File Reference
Implements a Vulkan shader for rendering 3D objects with support for basic lighting and texturing. This shader handles vertex transformations, fragment shading, and resource binding for object rendering.
#include "core/kmemory.h"
#include "core/logger.h"
#include "math/math_types.h"
#include "math/kmath.h"
#include "renderer/vulkan/vulkan_buffer.h"
#include "renderer/vulkan/vulkan_pipeline.h"
#include "renderer/vulkan/vulkan_shader_utils.h"
Macros
#define BUILTIN_SHADER_NAME_OBJECT "Builtin.ObjectShader"
Name of the built-in object shader.
#define ATTRIBUTE_COUNT 2
Number of shader stages in the object shader.
Functions
b8 vulkan_object_shader_create (vulkan_context *context, texture *default_diffuse, vulkan_object_shader *out_shader)
Creates a Vulkan object shader for rendering 3D objects.
void vulkan_object_shader_destroy (vulkan_context *context, struct vulkan_object_shader *shader)
Destroys a Vulkan object shader and frees associated resources.
void vulkan_object_shader_use (vulkan_context *context, struct vulkan_object_shader *shader)
Binds the Vulkan object shader's pipeline for rendering.
void vulkan_object_shader_update_global_state (vulkan_context *context, struct vulkan_object_shader *shader, f32 delta_time)
Updates the global uniform state for the Vulkan object shader.
void vulkan_object_shader_update_object (vulkan_context *context, struct vulkan_object_shader *shader, geometry_render_data data)
Updates the model matrix for a specific object in the Vulkan object shader.
b8 vulkan_object_shader_acquire_resources (vulkan_context *context, struct vulkan_object_shader *shader, u32 *out_object_id)
Acquires resources for rendering a new object with the Vulkan object shader.
void vulkan_object_shader_release_resources (vulkan_context *context, struct vulkan_object_shader *shader, u32 object_id)
Releases resources associated with a specific object ID in the Vulkan object shader.
Detailed Description
Implements a Vulkan shader for rendering 3D objects with support for basic lighting and texturing. This shader handles vertex transformations, fragment shading, and resource binding for object rendering.
Definition in file vulkan_object_shader.c.
Macro Definition Documentation
ATTRIBUTE_COUNT
#define ATTRIBUTE_COUNT 2
Number of shader stages in the object shader.
Definition at line 26 of file vulkan_object_shader.c.
BUILTIN_SHADER_NAME_OBJECT
#define BUILTIN_SHADER_NAME_OBJECT "Builtin.ObjectShader"
Name of the built-in object shader.
Definition at line 21 of file vulkan_object_shader.c.
Function Documentation
vulkan_object_shader_acquire_resources()
b8 vulkan_object_shader_acquire_resources (vulkan_context * context, struct vulkan_object_shader * shader, u32 * out_object_id)
Acquires resources for rendering a new object with the Vulkan object shader.
This function allocates a new object ID and initializes its descriptor sets for use in rendering. It manages a free list of object states to track resource usage.
Parameters
context The Vulkan context containing device and swapchain information.
shader Pointer to the vulkan_object_shader structure from which to acquire resources.
out_object_id Pointer to store the acquired object ID.
Returns
True if resources were successfully acquired; otherwise False.
Definition at line 401 of file vulkan_object_shader.c.
References context, False, INVALID_ID, KERROR, and True.
Referenced by vulkan_renderer_backend_initialize().
vulkan_object_shader_create()
b8 vulkan_object_shader_create (vulkan_context * context, texture * default_diffuse, vulkan_object_shader * out_shader)
Creates a Vulkan object shader for rendering 3D objects.
This function initializes the shader stages, descriptor sets, uniform buffers, and graphics pipeline needed for rendering objects in a Vulkan context.
Parameters
context The Vulkan context containing device and swapchain information.
out_shader Pointer to the vulkan_object_shader structure to be initialized.
Returns
True if the shader was created successfully; otherwise False.
Binding 0 - uniform buffer
< MAX_MATERIAL_INSTANCE_COUNT
Definition at line 28 of file vulkan_object_shader.c.
References ATTRIBUTE_COUNT, BUILTIN_SHADER_NAME_OBJECT, context, create_shader_module(), False, KERROR, kzero_memory(), True, vulkan_buffer_create(), and vulkan_graphics_pipeline_create().
Referenced by vulkan_renderer_backend_initialize().
vulkan_object_shader_destroy()
void vulkan_object_shader_destroy (vulkan_context * context, struct vulkan_object_shader * shader)
Destroys a Vulkan object shader and frees associated resources.
This function cleans up all resources allocated for the object shader, including shader modules, descriptor sets, uniform buffers, and the graphics pipeline.
Parameters
context The Vulkan context containing device information.
shader Pointer to the vulkan_object_shader structure to be destroyed.
Definition at line 220 of file vulkan_object_shader.c.
References context, KDEBUG, vulkan_buffer_destroy(), and vulkan_pipeline_destroy().
Referenced by vulkan_renderer_backend_shutdown().
vulkan_object_shader_release_resources()
void vulkan_object_shader_release_resources (vulkan_context * context, struct vulkan_object_shader * shader, u32 object_id)
Releases resources associated with a specific object ID in the Vulkan object shader.
This function frees the descriptor sets and resets the state for the given object ID, allowing its resources to be reused for future objects. It manages the free list of object states.
Parameters
context The Vulkan context containing device information.
shader Pointer to the vulkan_object_shader structure from which to release resources.
object_id The object ID whose resources are to be released.
Definition at line 437 of file vulkan_object_shader.c.
References context, INVALID_ID, and KERROR.
vulkan_object_shader_update_global_state()
void vulkan_object_shader_update_global_state (vulkan_context * context, struct vulkan_object_shader * shader, f32 delta_time)
Updates the global uniform state for the Vulkan object shader.
This function updates the global uniform buffer object (UBO) with the current projection and view matrices, and binds the appropriate descriptor set for the current frame.
Parameters
context The Vulkan context containing command buffers and frame information.
shader Pointer to the vulkan_object_shader structure whose global state is to be updated.
Definition at line 262 of file vulkan_object_shader.c.
References context, and vulkan_buffer_load_data().
Referenced by vulkan_renderer_update_global_state().
vulkan_object_shader_update_object()
void vulkan_object_shader_update_object (vulkan_context * context, struct vulkan_object_shader * shader, geometry_render_data data)
Updates the model matrix for a specific object in the Vulkan object shader.
Updates per-object descriptor data (UBO + texture) and binds the descriptor set. Should be called once per object before drawing.
Definition at line 298 of file vulkan_object_shader.c.
References context, texture::generation, texture::internal_data, INVALID_ID, ksin(), kzero_memory(), vec4_create(), and vulkan_buffer_load_data().
Referenced by vulkan_backend_update_object().
vulkan_object_shader_use()
void vulkan_object_shader_use (vulkan_context * context, struct vulkan_object_shader * shader)
Binds the Vulkan object shader's pipeline for rendering.
This function binds the graphics pipeline associated with the object shader to the command buffer for the current frame, preparing it for drawing operations.
Parameters
context The Vulkan context containing command buffers and frame information.
shader Pointer to the vulkan_object_shader structure whose pipeline is to be bound.
Definition at line 257 of file vulkan_object_shader.c.
References context, and vulkan_pipeline_bind().
Referenced by vulkan_backend_update_object(), and vulkan_renderer_update_global_state().