Koru Game Engine: engine/src/renderer/vulkan/vulkan_image.h File Reference
vulkan_image.h File Reference
Image management utilities for the Koru Engine's Vulkan renderer.
#include "vulkan_types.inl"
Functions
void vulkan_image_create (vulkan_context *context, VkImageType image_type, u32 width, u32 height, VkFormat format, VkImageTiling tiling, VkImageUsageFlags usage, VkMemoryPropertyFlags memory_flags, b32 create_view, VkImageAspectFlags view_aspect_flags, vulkan_image *out_image)
Creates and allocates a Vulkan image with specified properties.
void vulkan_image_view_create (vulkan_context *context, VkFormat format, vulkan_image *image, VkImageAspectFlags aspect_flags)
Creates an image view for a given image.
void vulkan_image_destroy (vulkan_context *context, vulkan_image *image)
Destroys a Vulkan image and its associated resources.
Detailed Description
Image management utilities for the Koru Engine's Vulkan renderer.
This module provides functions to:
Create and allocate Vulkan images
Generate image views for use in render passes or shaders
Destroy images and associated resources
These are used throughout the rendering pipeline for color attachments, depth/stencil buffers, and texture resources.
Definition in file vulkan_image.h.
Function Documentation
vulkan_image_create()
void vulkan_image_create (vulkan_context * context, VkImageType image_type, u32 width, u32 height, VkFormat format, VkImageTiling tiling, VkImageUsageFlags usage, VkMemoryPropertyFlags memory_flags, b32 create_view, VkImageAspectFlags view_aspect_flags, vulkan_image * out_image)
Creates and allocates a Vulkan image with specified properties.
Handles:
Image creation (vkCreateImage)
Memory allocation and binding
Optional image view creation
Usage example: creating swapchain images, depth attachments, or textures.
Parameters
context A pointer to the active Vulkan context.
image_type Type of image (1D, 2D, 3D).
width Width of the image in pixels.
height Height of the image in pixels.
format Pixel format (e.g., VK_FORMAT_B8G8R8A8_UNORM).
tiling Tiling mode (linear or optimal).
usage Usage flags indicating how this image will be used.
memory_flags Flags for memory allocation (device/local, host visible, etc.)
create_view Whether to automatically generate an image view.
view_aspect_flags Aspect flags for image view creation (color, depth, etc.).
out_image A pointer to a vulkan_image struct to populate.
Creates and allocates a Vulkan image with specified properties.
Handles:
Image creation (vkCreateImage)
Memory allocation and binding
Optional image view creation (via vulkan_image_view_create)
Parameters
context A pointer to the active Vulkan context.
image_type Type of image (1D, 2D, 3D).
width Width of the image in pixels.
height Height of the image in pixels.
format Pixel format (e.g., VK_FORMAT_B8G8R8A8_UNORM).
tiling Tiling mode: VK_IMAGE_TILING_LINEAR or VK_IMAGE_TILING_OPTIMAL.
usage Usage flags indicating how this image will be used.
memory_flags Flags for memory allocation (device/local, host visible, etc.).
create_view Whether to automatically generate an image view.
view_aspect_flags Aspect flags for image view (color, depth, etc.).
out_image A pointer to a vulkan_image struct to populate.
Definition at line 41 of file vulkan_image.c.
References context, KERROR, and vulkan_image_view_create().
Referenced by create().
vulkan_image_destroy()
void vulkan_image_destroy (vulkan_context * context, vulkan_image * image)
Destroys a Vulkan image and its associated resources.
Cleans up:
Image handle (vkDestroyImage)
Allocated memory (vkFreeMemory)
Image view (if present)
Must be called before destroying the logical device.
Parameters
context A pointer to the active Vulkan context.
image A pointer to the vulkan_image to destroy.
Cleans up:
The image view (if present)
Allocated memory for the image
The image handle itself
Must be called before destroying the logical device.
Parameters
context A pointer to the active Vulkan context.
image A pointer to the vulkan_image to destroy.
Definition at line 148 of file vulkan_image.c.
References context.
Referenced by destroy().
vulkan_image_view_create()
void vulkan_image_view_create (vulkan_context * context, VkFormat format, vulkan_image * image, VkImageAspectFlags aspect_flags)
Creates an image view for a given image.
Image views are necessary when using an image as:
Render target (color/depth attachment)
Texture (sampled image)
Storage image (for compute shaders)
Parameters
context A pointer to the active Vulkan context.
format Format of the image data.
image A pointer to the vulkan_image object to create a view for.
aspect_flags Describes which part of the image is accessible through the view (color, depth, etc.).
Creates an image view for a given image.
Image views define how the image is accessed (e.g., as a color attachment, sampled image, depth buffer, etc.)
Parameters
context A pointer to the active Vulkan context.
format Format of the image data.
image A pointer to the vulkan_image object to create a view for.
aspect_flags Describes which part of the image is accessible through the view.
Definition at line 113 of file vulkan_image.c.
References context.
Referenced by vulkan_image_create().