Koru Game Engine: engine/src/renderer/vulkan/vulkan_buffer.h File Reference
vulkan_buffer.h File Reference
Vulkan buffer management interface for the Koru Engine.
#include "vulkan_types.inl"
Functions
b8 vulkan_buffer_create (vulkan_context *context, u64 size, VkBufferUsageFlagBits usage, u32 memory_property_flags, b8 bind_on_create, vulkan_buffer *out_buffer)
Creates a Vulkan buffer with the specified parameters. The buffer can be optionally bound to memory upon creation.
void vulkan_buffer_destroy (vulkan_context *context, vulkan_buffer *buffer)
Destroys a Vulkan buffer and frees its associated memory. Must be called before destroying the Vulkan device or context.
void * vulkan_buffer_lock_memory (vulkan_context *context, vulkan_buffer *buffer, u64 offset, u64 size, u32 flags)
Locks a region of the buffer's memory for CPU access. Returns a pointer to the mapped memory region.
void vulkan_buffer_unlock_memory (vulkan_context *context, vulkan_buffer *buffer)
Unlocks a previously locked region of the buffer's memory. Must be called after finishing CPU access to the memory.
void vulkan_buffer_bind (vulkan_context *context, vulkan_buffer *buffer, u64 offset)
Binds the buffer to its allocated memory at the specified offset. Must be called before using the buffer in commands.
void vulkan_buffer_load_data (vulkan_context *context, vulkan_buffer *buffer, u64 offset, u64 size, u32 flags, const void *data)
Loads data into the buffer at the specified offset. The buffer must be created with memory properties that allow CPU access.
void vulkan_buffer_copy_to (vulkan_context *context, VkCommandPool pool, VkFence fence, VkQueue queue, VkBuffer source, u64 source_offset, VkBuffer dest, u64 dest_offset, u64 size)
Copies data from one buffer to another using a command buffer. Both buffers must be created with appropriate usage flags to allow copying.
Detailed Description
Vulkan buffer management interface for the Koru Engine.
This module provides functions to:
Create and destroy Vulkan buffers
Lock and unlock buffer memory for CPU access
Load data into buffers
Copy data between buffers
Buffers are used to store vertex data, index data, uniform data, and other GPU resources. Proper management of buffer memory is crucial for performance and correctness in Vulkan applications.
Definition in file vulkan_buffer.h.
Function Documentation
vulkan_buffer_bind()
void vulkan_buffer_bind (vulkan_context * context, vulkan_buffer * buffer, u64 offset)
Binds the buffer to its allocated memory at the specified offset. Must be called before using the buffer in commands.
Parameters
context A pointer to the active Vulkan context.
buffer A pointer to the vulkan_buffer to bind.
offset The byte offset within the memory to bind the buffer to.
Definition at line 140 of file vulkan_buffer.c.
References context.
Referenced by vulkan_buffer_create().
vulkan_buffer_copy_to()
void vulkan_buffer_copy_to (vulkan_context * context, VkCommandPool pool, VkFence fence, VkQueue queue, VkBuffer source, u64 source_offset, VkBuffer dest, u64 dest_offset, u64 size)
Copies data from one buffer to another using a command buffer. Both buffers must be created with appropriate usage flags to allow copying.
Parameters
context A pointer to the active Vulkan context.
pool The command pool to allocate the copy command buffer from.
fence A fence to signal when the copy operation is complete.
queue The queue to submit the copy command buffer to.
source The source buffer to copy data from.
source_offset The byte offset within the source buffer to start copying from.
dest The destination buffer to copy data to.
dest_offset The byte offset within the destination buffer to start copying to.
size The size in bytes of the data to copy.
Definition at line 161 of file vulkan_buffer.c.
References context, vulkan_command_buffer_allocate_and_begin_single_use(), and vulkan_command_buffer_end_single_use().
Referenced by upload_data_range(), and vulkan_buffer_resize().
vulkan_buffer_create()
b8 vulkan_buffer_create (vulkan_context * context, u64 size, VkBufferUsageFlagBits usage, u32 memory_property_flags, b8 bind_on_create, vulkan_buffer * out_buffer)
Creates a Vulkan buffer with the specified parameters. The buffer can be optionally bound to memory upon creation.
Parameters
context A pointer to the active Vulkan context.
size The size of the buffer in bytes.
usage Usage flags indicating how the buffer will be used (e.g., VK_BUFFER_USAGE_VERTEX_BUFFER_BIT).
memory_property_flags Memory property flags indicating how the buffer's memory can be accessed (e.g., VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT).
bind_on_create If True, the buffer will be bound to memory immediately after creation.
out_buffer A pointer to a vulkan_buffer struct to populate with the created buffer's details.
Returns
True if the buffer was created successfully, False otherwise.
Definition at line 17 of file vulkan_buffer.c.
References context, False, KERROR, kzero_memory(), True, and vulkan_buffer_bind().
Referenced by create_buffers(), upload_data_range(), vulkan_object_shader_create(), and vulkan_renderer_create_texture().
vulkan_buffer_destroy()
void vulkan_buffer_destroy (vulkan_context * context, vulkan_buffer * buffer)
Destroys a Vulkan buffer and frees its associated memory. Must be called before destroying the Vulkan device or context.
Parameters
context A pointer to the active Vulkan context.
buffer A pointer to the vulkan_buffer to destroy.
Definition at line 64 of file vulkan_buffer.c.
References context, False, and KDEBUG.
Referenced by upload_data_range(), vulkan_object_shader_destroy(), vulkan_renderer_backend_shutdown(), and vulkan_renderer_create_texture().
vulkan_buffer_load_data()
void vulkan_buffer_load_data (vulkan_context * context, vulkan_buffer * buffer, u64 offset, u64 size, u32 flags, const void * data)
Loads data into the buffer at the specified offset. The buffer must be created with memory properties that allow CPU access.
Parameters
context A pointer to the active Vulkan context.
buffer A pointer to the vulkan_buffer to load data into.
offset The byte offset within the buffer to start loading data.
size The size in bytes of the data to load.
flags Flags for memory operations (e.g., 0 for default behavior).
data A pointer to the source data to copy into the buffer.
Definition at line 154 of file vulkan_buffer.c.
References context, and kcopy_memory().
Referenced by upload_data_range(), vulkan_object_shader_update_global_state(), vulkan_object_shader_update_object(), and vulkan_renderer_create_texture().
vulkan_buffer_lock_memory()
void * vulkan_buffer_lock_memory (vulkan_context * context, vulkan_buffer * buffer, u64 offset, u64 size, u32 flags)
Locks a region of the buffer's memory for CPU access. Returns a pointer to the mapped memory region.
Parameters
context A pointer to the active Vulkan context.
buffer A pointer to the vulkan_buffer to lock.
offset The byte offset within the buffer to start locking.
size The size in bytes of the region to lock.
flags Flags for memory mapping (e.g., 0 for default behavior).
Definition at line 144 of file vulkan_buffer.c.
References context.
vulkan_buffer_unlock_memory()
void vulkan_buffer_unlock_memory (vulkan_context * context, vulkan_buffer * buffer)
Unlocks a previously locked region of the buffer's memory. Must be called after finishing CPU access to the memory.
Parameters
context A pointer to the active Vulkan context.
buffer A pointer to the vulkan_buffer to unlock.
Definition at line 150 of file vulkan_buffer.c.
References context.