Koru Game Engine: engine/src/renderer/vulkan/shaders/vulkan_material_shader.c File Reference
vulkan_material_shader.c File Reference
Implements a Vulkan shader for rendering 3D objects with support for basic lighting and texturing. This shader handles vertex transformations, fragment shading, and resource binding for object rendering.
#include "core/kmemory.h"
#include "core/logger.h"
#include "math/math_types.h"
#include "math/kmath.h"
#include "systems/texture_system.h"
#include "renderer/vulkan/vulkan_buffer.h"
#include "renderer/vulkan/vulkan_pipeline.h"
#include "renderer/vulkan/vulkan_shader_utils.h"
Macros
#define BUILTIN_SHADER_NAME_OBJECT "Builtin.MaterialShader"
Name of the built-in material shader.
#define ATTRIBUTE_COUNT 2
Number of shader stages in the object shader.
Functions
b8 vulkan_material_shader_create (vulkan_context *context, vulkan_material_shader *out_shader)
Creates a Vulkan object shader for rendering 3D objects.
void vulkan_material_shader_destroy (vulkan_context *context, struct vulkan_material_shader *shader)
Destroys a Vulkan object shader and frees associated resources.
void vulkan_material_shader_use (vulkan_context *context, struct vulkan_material_shader *shader)
Binds the Vulkan object shader's pipeline for rendering.
void vulkan_material_shader_update_global_state (vulkan_context *context, struct vulkan_material_shader *shader, f32 delta_time)
Updates the global uniform state for the Vulkan object shader.
void vulkan_material_shader_set_model (vulkan_context *context, struct vulkan_material_shader *shader, mat4 model)
Sets the model matrix for the Vulkan object shader using push constants.
void vulkan_material_shader_apply_material (vulkan_context *context, struct vulkan_material_shader *shader, material *material)
Updates per-object descriptor data (UBO + texture) and binds the descriptor set.
b8 vulkan_material_shader_acquire_resources (vulkan_context *context, struct vulkan_material_shader *shader, material *material)
Acquires resources for rendering a new object with the Vulkan object shader.
void vulkan_material_shader_release_resources (vulkan_context *context, struct vulkan_material_shader *shader, material *material)
Releases resources associated with a specific object ID in the Vulkan object shader.
Detailed Description
Implements a Vulkan shader for rendering 3D objects with support for basic lighting and texturing. This shader handles vertex transformations, fragment shading, and resource binding for object rendering.
Definition in file vulkan_material_shader.c.
Macro Definition Documentation
ATTRIBUTE_COUNT
#define ATTRIBUTE_COUNT 2
Number of shader stages in the object shader.
Definition at line 28 of file vulkan_material_shader.c.
BUILTIN_SHADER_NAME_OBJECT
#define BUILTIN_SHADER_NAME_OBJECT "Builtin.MaterialShader"
Name of the built-in material shader.
Definition at line 23 of file vulkan_material_shader.c.
Function Documentation
vulkan_material_shader_acquire_resources()
b8 vulkan_material_shader_acquire_resources (vulkan_context * context, struct vulkan_material_shader * shader, material * material)
Acquires resources for rendering a new object with the Vulkan object shader.
This function allocates a new object ID and initializes its descriptor sets for use in rendering. It manages a free list of object states to track resource usage.
Parameters
context The Vulkan context containing device and swapchain information.
shader Pointer to the vulkan_material_shader structure from which to acquire resources.
material Pointer to the material associated with the object being rendered.
Returns
True if resources were successfully acquired; otherwise False.
Definition at line 424 of file vulkan_material_shader.c.
References context, False, material::internal_id, INVALID_ID, KERROR, and True.
Referenced by vulkan_renderer_create_material().
vulkan_material_shader_apply_material()
void vulkan_material_shader_apply_material (vulkan_context * context, struct vulkan_material_shader * shader, material * material)
Updates per-object descriptor data (UBO + texture) and binds the descriptor set.
This function updates the uniform buffer object (UBO) and texture bindings for a specific object being rendered, and binds the appropriate descriptor set for the current frame. It should be called once per object before drawing.
Parameters
context The Vulkan context containing command buffers and frame information.
shader Pointer to the vulkan_material_shader structure whose object state is to be updated.
data Structure containing the model matrix and material information for the object.
Definition at line 305 of file vulkan_material_shader.c.
References context, material::diffuse_color, material::diffuse_map, texture::generation, material::generation, texture::id, texture::internal_data, material::internal_id, INVALID_ID, KFATAL, kzero_memory(), texture_map::texture, texture_system_get_default_texture(), TEXTURE_USE_MAP_DIFFUSE, and vulkan_buffer_load_data().
Referenced by vulkan_backend_draw_geometry().
vulkan_material_shader_create()
b8 vulkan_material_shader_create (vulkan_context * context, vulkan_material_shader * out_shader)
Creates a Vulkan object shader for rendering 3D objects.
This function initializes the shader stages, descriptor sets, uniform buffers, and graphics pipeline needed for rendering objects in a Vulkan context.
Parameters
context The Vulkan context containing device and swapchain information.
out_shader Pointer to the vulkan_material_shader structure to be initialized.
Returns
True if the shader was created successfully; otherwise False.
Binding 0 - uniform buffer
< MAX_MATERIAL_INSTANCE_COUNT
Definition at line 30 of file vulkan_material_shader.c.
References ATTRIBUTE_COUNT, BUILTIN_SHADER_NAME_OBJECT, context, create_shader_module(), False, KERROR, kzero_memory(), TEXTURE_USE_MAP_DIFFUSE, True, vulkan_buffer_create(), and vulkan_graphics_pipeline_create().
Referenced by vulkan_renderer_backend_initialize().
vulkan_material_shader_destroy()
void vulkan_material_shader_destroy (vulkan_context * context, struct vulkan_material_shader * shader)
Destroys a Vulkan object shader and frees associated resources.
This function cleans up all resources allocated for the object shader, including shader modules, descriptor sets, uniform buffers, and the graphics pipeline.
Parameters
context The Vulkan context containing device information.
shader Pointer to the vulkan_material_shader structure to be destroyed.
Definition at line 222 of file vulkan_material_shader.c.
References context, KDEBUG, vulkan_buffer_destroy(), and vulkan_pipeline_destroy().
Referenced by vulkan_renderer_backend_shutdown().
vulkan_material_shader_release_resources()
void vulkan_material_shader_release_resources (vulkan_context * context, struct vulkan_material_shader * shader, material * material)
Releases resources associated with a specific object ID in the Vulkan object shader.
This function frees the descriptor sets and resets the state for the given object ID, allowing its resources to be reused for future objects. It manages the free list of object states.
Parameters
context The Vulkan context containing device information.
shader Pointer to the vulkan_material_shader structure from which to release resources.
material Pointer to the material associated with the object being released.
Definition at line 460 of file vulkan_material_shader.c.
References context, material::internal_id, INVALID_ID, and KERROR.
Referenced by vulkan_renderer_destroy_material().
vulkan_material_shader_set_model()
void vulkan_material_shader_set_model (vulkan_context * context, struct vulkan_material_shader * shader, mat4 model)
Sets the model matrix for the Vulkan object shader using push constants.
This function updates the model matrix used for transforming vertices in the vertex shader. It utilizes push constants for efficient updates without needing to modify uniform buffers.
Parameters
context The Vulkan context containing command buffers and frame information.
shader Pointer to the vulkan_material_shader structure whose model matrix is to be set.
model The model matrix to be applied to the shader.
Definition at line 296 of file vulkan_material_shader.c.
References context.
Referenced by vulkan_backend_draw_geometry().
vulkan_material_shader_update_global_state()
void vulkan_material_shader_update_global_state (vulkan_context * context, struct vulkan_material_shader * shader, f32 delta_time)
Updates the global uniform state for the Vulkan object shader.
This function updates the global uniform buffer object (UBO) with the current projection and view matrices, and binds the appropriate descriptor set for the current frame.
Parameters
context The Vulkan context containing command buffers and frame information.
shader Pointer to the vulkan_material_shader structure whose global state is to be updated.
Definition at line 264 of file vulkan_material_shader.c.
References context, and vulkan_buffer_load_data().
Referenced by vulkan_renderer_update_global_state().
vulkan_material_shader_use()
void vulkan_material_shader_use (vulkan_context * context, struct vulkan_material_shader * shader)
Binds the Vulkan object shader's pipeline for rendering.
This function binds the graphics pipeline associated with the object shader to the command buffer for the current frame, preparing it for drawing operations.
Parameters
context The Vulkan context containing command buffers and frame information.
shader Pointer to the vulkan_material_shader structure whose pipeline is to be bound.
Definition at line 259 of file vulkan_material_shader.c.
References context, and vulkan_pipeline_bind().
Referenced by vulkan_backend_draw_geometry(), and vulkan_renderer_update_global_state().