Koru Game Engine: engine/src/renderer/vulkan/vulkan_device.c File Reference
vulkan_device.c File Reference
Implementation of Vulkan device creation and selection logic.
#include "containers/darray.h"
#include "core/logger.h"
#include "core/kstring.h"
#include "core/kmemory.h"
#include "vulkan_device.h"
Data Structures
struct vulkan_physical_device_requirements
‍ Forward declarations
struct vulkan_physical_device_queue_family_info
Stores indices of queue families for a physical device.
Typedefs
typedef struct vulkan_physical_device_requirements vulkan_physical_device_requirements
typedef struct vulkan_physical_device_queue_family_info vulkan_physical_device_queue_family_info
Functions
b8 select_physical_device (vulkan_context *context)
Selects the most suitable physical device from the list of available devices.
b8 physical_device_meets_requirements (VkPhysicalDevice device, VkSurfaceKHR surface, const VkPhysicalDeviceProperties *properties, const VkPhysicalDeviceFeatures *features, const vulkan_physical_device_requirements *requirements, vulkan_physical_device_queue_family_info *out_queue_family_info, vulkan_swapchain_support_info *out_swapchain_support)
Checks whether the given physical device meets all specified requirements.
b8 vulkan_device_create (vulkan_context *context)
Creates and selects a suitable physical/logical Vulkan device.
void vulkan_device_destroy (vulkan_context *context)
Destroys the logical device and cleans up associated resources.
void vulkan_device_query_swapchain_support (VkPhysicalDevice physical_device, VkSurfaceKHR surface, vulkan_swapchain_support_info *out_support_info)
Queries swapchain support details for a given physical device and surface.
b8 vulkan_device_detect_depth_format (vulkan_device *device)
Detects and selects a suitable depth/stencil format for the given device.
Detailed Description
Implementation of Vulkan device creation and selection logic.
This module provides functions to:
Enumerate and select a suitable physical device
Query device capabilities and queue families
Check for required features (e.g., swapchain, anisotropic filtering)
Create a logical device with necessary queues
Definition in file vulkan_device.c.
Typedef Documentation
vulkan_physical_device_queue_family_info
typedef struct vulkan_physical_device_queue_family_info vulkan_physical_device_queue_family_info
vulkan_physical_device_requirements
typedef struct vulkan_physical_device_requirements vulkan_physical_device_requirements
Function Documentation
physical_device_meets_requirements()
b8 physical_device_meets_requirements (VkPhysicalDevice device, VkSurfaceKHR surface, const VkPhysicalDeviceProperties * properties, const VkPhysicalDeviceFeatures * features, const vulkan_physical_device_requirements * requirements, vulkan_physical_device_queue_family_info * out_queue_family_info, vulkan_swapchain_support_info * out_swapchain_support)
Checks whether the given physical device meets all specified requirements.
Evaluates:
Queue family support (graphics, present, compute, transfer)
Surface/swapchain capabilities
Required extensions
Feature support (like samplerAnisotropy)
Parameters
device The physical device to evaluate.
surface The surface to test for presentation support.
properties Device properties (name, type, driver version).
features Device features (supports what?).
requirements Required features and capabilities.
out_queue_family_info Output structure for queue family indices.
out_swapchain_support Output structure for swapchain support data.
Returns
TRUE if device meets all requirements; FALSE otherwise.
Definition at line 504 of file vulkan_device.c.
References vulkan_physical_device_requirements::compute, vulkan_physical_device_queue_family_info::compute_family_index, darray_length, vulkan_physical_device_requirements::device_extension_names, vulkan_physical_device_requirements::discrete_gpu, FALSE, vulkan_physical_device_requirements::graphics, vulkan_physical_device_queue_family_info::graphics_family_index, kallocate(), kfree(), KINFO, KTRACE, MEMORY_TAG_RENDERER, vulkan_physical_device_requirements::present, vulkan_physical_device_queue_family_info::present_family_index, vulkan_physical_device_requirements::sampler_anisotropy, strings_equal(), vulkan_physical_device_requirements::transfer, vulkan_physical_device_queue_family_info::transfer_family_index, TRUE, and vulkan_device_query_swapchain_support().
Referenced by select_physical_device().
select_physical_device()
b8 select_physical_device (vulkan_context * context)
Selects the most suitable physical device from the list of available devices.
Iterates through all available physical devices and checks whether each meets the requirements. If a suitable device is found, it is stored in the context.
Requirements include:
Support for graphics, presentation, and transfer queues
Required extensions (like VK_KHR_swapchain)
Optional features like anisotropic filtering
Optional preference for discrete GPU
Parameters
context A pointer to the Vulkan context where device info will be stored.
Returns
TRUE if a suitable device was found and selected; FALSE otherwise.
Definition at line 390 of file vulkan_device.c.
References vulkan_physical_device_requirements::compute, context, darray_create, darray_push, vulkan_physical_device_requirements::device_extension_names, vulkan_physical_device_requirements::discrete_gpu, FALSE, vulkan_physical_device_requirements::graphics, vulkan_physical_device_queue_family_info::graphics_family_index, KERROR, KFATAL, KINFO, physical_device_meets_requirements(), vulkan_physical_device_requirements::present, vulkan_physical_device_queue_family_info::present_family_index, vulkan_physical_device_requirements::sampler_anisotropy, vulkan_physical_device_requirements::transfer, vulkan_physical_device_queue_family_info::transfer_family_index, and TRUE.
Referenced by vulkan_device_create().
vulkan_device_create()
b8 vulkan_device_create (vulkan_context * context)
Creates and selects a suitable physical/logical Vulkan device.
Queries available physical devices, selects one based on feature and queue support, creates a logical device, and initializes queues (graphics, present, compute, transfer).
Parameters
context A pointer to the Vulkan context. Must be valid and initialized.
Returns
TRUE if a suitable device was found and successfully created; FALSE otherwise.
Definition at line 147 of file vulkan_device.c.
References context, FALSE, KINFO, select_physical_device(), and TRUE.
Referenced by vulkan_renderer_backend_initialize().
vulkan_device_destroy()
void vulkan_device_destroy (vulkan_context * context)
Destroys the logical device and cleans up associated resources.
Shuts down the logical device and any internal structures like queues. Should be called before shutting down the instance.
Parameters
context A pointer to the Vulkan context containing the device to destroy.
Definition at line 255 of file vulkan_device.c.
References context, kfree(), KINFO, kzero_memory(), and MEMORY_TAG_RENDERER.
Referenced by vulkan_renderer_backend_shutdown().
vulkan_device_detect_depth_format()
b8 vulkan_device_detect_depth_format (vulkan_device * device)
Detects and selects a suitable depth/stencil format for the given device.
Tries common depth formats (D32_FLOAT, D24_UNORM_S8_UINT, etc.) and checks if they are supported with optimal tiling.
Parameters
device A pointer to the vulkan_device object.
Returns
TRUE if a valid depth format was found; FALSE otherwise.
Definition at line 365 of file vulkan_device.c.
References FALSE, and TRUE.
Referenced by create().
vulkan_device_query_swapchain_support()
void vulkan_device_query_swapchain_support (VkPhysicalDevice physical_device, VkSurfaceKHR surface, vulkan_swapchain_support_info * out_support_info)
Queries swapchain support details for a given physical device and surface.
Populates a vulkan_swapchain_support_info struct with:
Capabilities (min/max image counts, dimensions, etc.)
Formats supported
Present modes available
This information is used later when creating a swapchain.
Parameters
physical_device The physical device to query.
surface The surface to check compatibility with.
out_support_info A pointer to a structure to fill with swapchain support info.
Definition at line 319 of file vulkan_device.c.
References kallocate(), and MEMORY_TAG_RENDERER.
Referenced by create(), and physical_device_meets_requirements().