Koru Game Engine: engine/src/renderer/vulkan/vulkan_renderpass.c File Reference
vulkan_renderpass.c File Reference
Implementation of Vulkan render pass creation, begin, and end functions.
#include "core/kmemory.h"
#include "vulkan_renderpass.h"
Functions
void vulkan_renderpass_create (vulkan_context *context, vulkan_renderpass *out_renderpass, f32 x, f32 y, f32 w, f32 h, f32 r, f32 g, f32 b, f32 a, f32 depth, u32 stencil)
Creates a new render pass using the provided configuration.
void vulkan_renderpass_destroy (vulkan_context *context, vulkan_renderpass *renderpass)
Destroys a render pass and cleans up its resources.
void vulkan_renderpass_begin (vulkan_command_buffer *command_buffer, vulkan_renderpass *renderpass, VkFramebuffer frame_buffer)
Begins a render pass using the given command buffer and framebuffer.
void vulkan_renderpass_end (vulkan_command_buffer *command_buffer, vulkan_renderpass *renderpass)
Ends the current render pass.
Detailed Description
Implementation of Vulkan render pass creation, begin, and end functions.
This module provides utilities to:
Create a render pass with color and depth attachments
Begin rendering into a framebuffer
End the render pass after drawing is complete
It works closely with:
vulkan_swapchain
vulkan_framebuffer
vulkan_command_buffer
Definition in file vulkan_renderpass.c.
Function Documentation
vulkan_renderpass_begin()
void vulkan_renderpass_begin (vulkan_command_buffer * command_buffer, vulkan_renderpass * renderpass, VkFramebuffer frame_buffer)
Begins a render pass using the given command buffer and framebuffer.
Begins a render pass using the given command buffer.
Records the beginning of the render pass into the command buffer. Sets up:
Render area (viewport)
Clear values (color, depth, stencil)
Framebuffer binding
After this call, the command buffer is in IN_RENDER_PASS state.
Parameters
command_buffer A pointer to the active command buffer.
renderpass A pointer to the vulkan_renderpass to begin.
frame_buffer The framebuffer to render into.
Definition at line 180 of file vulkan_renderpass.c.
References kzero_memory().
Referenced by vulkan_renderer_backend_begin_frame().
vulkan_renderpass_create()
void vulkan_renderpass_create (vulkan_context * context, vulkan_renderpass * out_renderpass, f32 x, f32 y, f32 w, f32 h, f32 r, f32 g, f32 b, f32 a, f32 depth, u32 stencil)
Creates a new render pass using the provided configuration.
Sets up:
One subpass (currently hard-coded)
Two attachment descriptions: one for color, one for depth/stencil
LoadOp/Clear values
Image layout transitions
Parameters
context A pointer to the active Vulkan context.
out_renderpass A pointer to the vulkan_renderpass struct to populate.
x X position of the viewport.
y Y position of the viewport.
w Width of the viewport.
h Height of the viewport.
r Red clear value (0–1).
g Green clear value (0–1).
b Blue clear value (0–1).
a Alpha clear value (0–1).
depth Depth clear value (0–1).
stencil Stencil clear value.
Definition at line 41 of file vulkan_renderpass.c.
References context.
Referenced by vulkan_renderer_backend_initialize().
vulkan_renderpass_destroy()
void vulkan_renderpass_destroy (vulkan_context * context, vulkan_renderpass * renderpass)
Destroys a render pass and cleans up its resources.
Must be called before destroying the logical device.
Parameters
context A pointer to the active Vulkan context.
renderpass A pointer to the vulkan_renderpass being destroyed.
Definition at line 158 of file vulkan_renderpass.c.
References context.
Referenced by vulkan_renderer_backend_shutdown().
vulkan_renderpass_end()
void vulkan_renderpass_end (vulkan_command_buffer * command_buffer, vulkan_renderpass * renderpass)
Ends the current render pass.
Records the end of the render pass into the command buffer. Updates the command buffer state back to RECORDING.
Parameters
command_buffer A pointer to the active command buffer.
renderpass A pointer to the vulkan_renderpass being ended.
Definition at line 225 of file vulkan_renderpass.c.
Referenced by vulkan_renderer_backend_end_frame().