Koru Game Engine: engine/src/renderer/vulkan/vulkan_swapchain.h File Reference
vulkan_swapchain.h File Reference
Vulkan swapchain management interface for the Koru Engine.
#include "vulkan_types.inl"
Functions
void vulkan_swapchain_create (vulkan_context *context, u32 width, u32 height, vulkan_swapchain *out_swapchain)
Creates a new Vulkan swapchain.
void vulkan_swapchain_recreate (vulkan_context *context, u32 width, u32 height, vulkan_swapchain *swapchain)
Recreates an existing swapchain, typically after a window resize event.
void vulkan_swapchain_destroy (vulkan_context *context, vulkan_swapchain *swapchain)
Destroys a Vulkan swapchain and releases all associated resources.
b8 vulkan_swapchain_acquire_next_image_index (vulkan_context *context, vulkan_swapchain *swapchain, u64 timeout_ns, VkSemaphore image_available_semaphore, VkFence fence, u32 *out_image_index)
Acquires the next available image index from the swapchain.
void vulkan_swapchain_present (vulkan_context *context, vulkan_swapchain *swapchain, VkQueue graphics_queue, VkQueue present_queue, VkSemaphore render_complete_semaphore, u32 present_image_index)
Presents the rendered image at the given index to the screen.
Detailed Description
Vulkan swapchain management interface for the Koru Engine.
This module provides functions to:
Create and destroy a Vulkan swapchain
Recreate it when the window is resized
Acquire image indices for rendering
Present rendered images to the screen
The swapchain acts as a queue of framebuffers that can be rendered to and presented, enabling smooth animation and synchronization between CPU/GPU operations.
Definition in file vulkan_swapchain.h.
Function Documentation
vulkan_swapchain_acquire_next_image_index()
b8 vulkan_swapchain_acquire_next_image_index (vulkan_context * context, vulkan_swapchain * swapchain, u64 timeout_ns, VkSemaphore image_available_semaphore, VkFence fence, u32 * out_image_index)
Acquires the next available image index from the swapchain.
This function waits until a swapchain image is ready to be rendered to. Returns an index that can be used to select the appropriate image from the swapchain.
Parameters
context A pointer to the active Vulkan context.
swapchain A pointer to the swapchain to query.
timeout_ns Maximum time to wait for an image before timing out.
image_available_semaphore Semaphore signaled when the image is ready for use.
fence Optional fence to wait on before using the image.
out_image_index Output variable to store the index of the acquired image.
Returns
TRUE if successful; FALSE otherwise.
Acquires the next available image index from the swapchain.
Waits for an image to become available, then returns its index. If the swapchain is outdated, triggers recreation logic.
Parameters
context A pointer to the active Vulkan context.
swapchain A pointer to the vulkan_swapchain being used.
timeout_ns Maximum time to wait for an image.
image_available_semaphore Semaphore signaled when image is ready.
fence Optional fence to wait on before using the image.
out_image_index Output variable to store the acquired image index.
Returns
TRUE if successful; FALSE if the swapchain needs recreation.
Definition at line 105 of file vulkan_swapchain.c.
References context, FALSE, KFATAL, TRUE, and vulkan_swapchain_recreate().
vulkan_swapchain_create()
void vulkan_swapchain_create (vulkan_context * context, u32 width, u32 height, vulkan_swapchain * out_swapchain)
Creates a new Vulkan swapchain.
Initializes the swapchain based on surface capabilities, format, and present mode. Must be called after logical device creation and before rendering begins.
Parameters
context A pointer to the active Vulkan context.
width The desired width of the swapchain images.
height The desired height of the swapchain images.
out_swapchain A pointer to a vulkan_swapchain structure to populate.
Creates a new Vulkan swapchain.
Sets up:
Surface format selection (preferred B8G8R8A8_UNORM)
Present mode (prefers MAILBOX_KHR if available)
Image count and extent clamped to supported values
Image views for each swapchain image
Depth attachment for rendering
Parameters
context A pointer to the active Vulkan context.
width The width of the new swapchain.
height The height of the new swapchain.
out_swapchain A pointer to the vulkan_swapchain structure to populate.
Definition at line 48 of file vulkan_swapchain.c.
References context, and create().
vulkan_swapchain_destroy()
void vulkan_swapchain_destroy (vulkan_context * context, vulkan_swapchain * swapchain)
Destroys a Vulkan swapchain and releases all associated resources.
Cleans up:
Swapchain handle
Image views
Framebuffers
Render passes
Should be called before destroying the logical device.
Parameters
context A pointer to the active Vulkan context.
swapchain A pointer to the swapchain to destroy.
Destroys a Vulkan swapchain and releases all associated resources.
Frees all image views and destroys the internal VkSwapchainKHR object.
Parameters
context A pointer to the active Vulkan context.
swapchain A pointer to the vulkan_swapchain to destroy.
Definition at line 85 of file vulkan_swapchain.c.
References context, and destroy().
vulkan_swapchain_present()
void vulkan_swapchain_present (vulkan_context * context, vulkan_swapchain * swapchain, VkQueue graphics_queue, VkQueue present_queue, VkSemaphore render_complete_semaphore, u32 present_image_index)
Presents the rendered image at the given index to the screen.
Submits the final rendered image to the presentation queue. Must be called after command buffer submission completes.
Parameters
context A pointer to the active Vulkan context.
swapchain A pointer to the swapchain being used.
graphics_queue Graphics queue handle used for rendering.
present_queue Presentation queue handle used for display.
render_complete_semaphore Semaphore signaled when rendering is complete.
present_image_index Index of the image to present.
Submits the final frame to the presentation queue using the provided semaphore. Handles errors like out-of-date swapchains by triggering recreation.
Parameters
context A pointer to the active Vulkan context.
swapchain A pointer to the vulkan_swapchain being used.
graphics_queue Graphics queue handle used for rendering.
present_queue Presentation queue handle used for display.
render_complete_semaphore Semaphore signaled when rendering is complete.
present_image_index Index of the image to present.
Definition at line 146 of file vulkan_swapchain.c.
References context, KFATAL, and vulkan_swapchain_recreate().
vulkan_swapchain_recreate()
void vulkan_swapchain_recreate (vulkan_context * context, u32 width, u32 height, vulkan_swapchain * swapchain)
Recreates an existing swapchain, typically after a window resize event.
Destroys the old swapchain and creates a new one with updated dimensions. Used during window resize handling to maintain valid render targets.
Parameters
context A pointer to the active Vulkan context.
width New width of the swapchain images.
height New height of the swapchain images.
swapchain A pointer to the existing swapchain to recreate.
Recreates an existing swapchain, typically after a window resize event.
Destroys the current swapchain and recreates it with updated dimensions.
Parameters
context A pointer to the active Vulkan context.
width New width of the swapchain.
height New height of the swapchain.
swapchain A pointer to the existing vulkan_swapchain to update.
Definition at line 67 of file vulkan_swapchain.c.
References context, create(), and destroy().
Referenced by vulkan_swapchain_acquire_next_image_index(), and vulkan_swapchain_present().