Koru Game Engine: engine/src/renderer/vulkan/vulkan_framebuffer.h File Reference
vulkan_framebuffer.h File Reference
Framebuffer management interface for the Koru Engine's Vulkan renderer.
#include "vulkan_types.inl"
Functions
void vulkan_framebuffer_create (vulkan_context *context, vulkan_renderpass *renderpass, u32 width, u32 height, u32 attachment_count, VkImageView *attachments, vulkan_framebuffer *out_framebuffer)
Creates a new Vulkan framebuffer using the provided attachments and render pass.
void vulkan_framebuffer_destroy (vulkan_context *context, vulkan_framebuffer *framebuffer)
Destroys a Vulkan framebuffer and releases its resources.
Detailed Description
Framebuffer management interface for the Koru Engine's Vulkan renderer.
This module provides functions to:
Create framebuffers that bind image views to a render pass
Destroy them safely during shutdown
Framebuffers are tightly coupled to the swapchain and must be recreated when:
The window resizes
The swapchain is re-created (e.g., due to vsync toggle or resolution change)
Definition in file vulkan_framebuffer.h.
Function Documentation
vulkan_framebuffer_create()
void vulkan_framebuffer_create (vulkan_context * context, vulkan_renderpass * renderpass, u32 width, u32 height, u32 attachment_count, VkImageView * attachments, vulkan_framebuffer * out_framebuffer)
Creates a new Vulkan framebuffer using the provided attachments and render pass.
Wraps vkCreateFramebuffer(...) and stores the attachments internally. Used when creating or recreating framebuffers after swapchain changes.
Parameters
context A pointer to the active Vulkan context.
renderpass A pointer to the render pass this framebuffer will use.
width Width of the framebuffer in pixels.
height Height of the framebuffer in pixels.
attachment_count Number of image views being bound.
attachments An array of VkImageView objects to attach.
out_framebuffer A pointer to a vulkan_framebuffer structure to populate.
Definition at line 17 of file vulkan_framebuffer.c.
References context, kallocate(), and MEMORY_TAG_RENDERER.
Referenced by regenerate_framebuffers().
vulkan_framebuffer_destroy()
void vulkan_framebuffer_destroy (vulkan_context * context, vulkan_framebuffer * framebuffer)
Destroys a Vulkan framebuffer and releases its resources.
Also frees any internal attachment memory if needed. Must be called before destroying the logical device or render pass.
Parameters
context A pointer to the active Vulkan context.
framebuffer A pointer to the vulkan_framebuffer to destroy.
Definition at line 51 of file vulkan_framebuffer.c.
References context, kfree(), and MEMORY_TAG_RENDERER.
Referenced by recreate_swapchain(), and vulkan_renderer_backend_shutdown().