Koru Game Engine: engine/src/renderer/vulkan/vulkan_command_buffer.h File Reference
vulkan_command_buffer.h File Reference
Vulkan command buffer management interface for the Koru Engine.
#include "vulkan_types.inl"
Functions
void vulkan_command_buffer_allocate (vulkan_context *context, VkCommandPool pool, b8 is_primary, vulkan_command_buffer *out_command_buffer)
Allocates a new command buffer from the given command pool.
void vulkan_command_buffer_free (vulkan_context *context, VkCommandPool pool, vulkan_command_buffer *command_buffer)
Frees the command buffer back to the pool.
void vulkan_command_buffer_begin (vulkan_command_buffer *command_buffer, b8 is_single_use, b8 is_renderpass_continue, b8 is_simultaneous_use)
Begins recording commands into the command buffer.
void vulkan_command_buffer_end (vulkan_command_buffer *command_buffer)
Ends the recording phase of a command buffer.
void vulkan_command_buffer_update_submitted (vulkan_command_buffer *command_buffer)
Updates the state of the command buffer to SUBMITTED.
void vulkan_command_buffer_reset (vulkan_command_buffer *command_buffer)
Resets the command buffer state to READY.
void vulkan_command_buffer_allocate_and_begin_single_use (vulkan_context *context, VkCommandPool pool, vulkan_command_buffer *out_command_buffer)
Allocates and begins recording a single-use command buffer.
void vulkan_command_buffer_end_single_use (vulkan_context *context, VkCommandPool pool, vulkan_command_buffer *command_buffer, VkQueue queue)
Ends and submits a single-use command buffer.
Detailed Description
Vulkan command buffer management interface for the Koru Engine.
This module provides functions to:
Allocate and free command buffers from a pool
Begin and end command recording
Submit buffers to the GPU
Manage state transitions during the command buffer lifecycle
Command buffers store GPU commands like drawing, memory transfers, and render pass operations. They must be allocated from a command pool, recorded into, and submitted to a queue for execution.
Definition in file vulkan_command_buffer.h.
Function Documentation
vulkan_command_buffer_allocate()
void vulkan_command_buffer_allocate (vulkan_context * context, VkCommandPool pool, b8 is_primary, vulkan_command_buffer * out_command_buffer)
Allocates a new command buffer from the given command pool.
Initializes the command buffer and sets its state to READY.
Parameters
context A pointer to the active Vulkan context.
pool The command pool to allocate from.
is_primary True if primary command buffer, False for secondary.
out_command_buffer A pointer to a vulkan_command_buffer to populate.
Definition at line 18 of file vulkan_command_buffer.c.
References context, and kzero_memory().
Referenced by create_command_buffers(), and vulkan_command_buffer_allocate_and_begin_single_use().
vulkan_command_buffer_allocate_and_begin_single_use()
void vulkan_command_buffer_allocate_and_begin_single_use (vulkan_context * context, VkCommandPool pool, vulkan_command_buffer * out_command_buffer)
Allocates and begins recording a single-use command buffer.
Combines allocate and begin steps for convenience. Typically used for quick GPU tasks like texture uploads.
Parameters
context A pointer to the active Vulkan context.
pool The command pool to allocate from.
out_command_buffer A pointer to the vulkan_command_buffer to initialize.
Definition at line 89 of file vulkan_command_buffer.c.
References context, False, True, vulkan_command_buffer_allocate(), and vulkan_command_buffer_begin().
vulkan_command_buffer_begin()
void vulkan_command_buffer_begin (vulkan_command_buffer * command_buffer, b8 is_single_use, b8 is_renderpass_continue, b8 is_simultaneous_use)
Begins recording commands into the command buffer.
Sets up flags like one-time use or simultaneous access.
Parameters
command_buffer A pointer to the command buffer being recorded.
is_single_use True if this buffer will only be used once.
is_renderpass_continue True if this is a secondary buffer continuing a render pass.
is_simultaneous_use True if the buffer can be re-recorded while in flight.
Definition at line 54 of file vulkan_command_buffer.c.
Referenced by vulkan_command_buffer_allocate_and_begin_single_use(), and vulkan_renderer_backend_begin_frame().
vulkan_command_buffer_end()
void vulkan_command_buffer_end (vulkan_command_buffer * command_buffer)
Ends the recording phase of a command buffer.
After calling this, the command buffer is ready for submission.
Parameters
command_buffer A pointer to the command buffer being ended.
Definition at line 76 of file vulkan_command_buffer.c.
Referenced by vulkan_command_buffer_end_single_use(), and vulkan_renderer_backend_end_frame().
vulkan_command_buffer_end_single_use()
void vulkan_command_buffer_end_single_use (vulkan_context * context, VkCommandPool pool, vulkan_command_buffer * command_buffer, VkQueue queue)
Ends and submits a single-use command buffer.
Submits the buffer to the provided queue and waits for completion. Then frees the buffer back to the pool.
Parameters
context A pointer to the active Vulkan context.
pool The command pool that owns the buffer.
command_buffer A pointer to the command buffer to submit.
queue The queue to submit the buffer to.
Definition at line 97 of file vulkan_command_buffer.c.
References context, vulkan_command_buffer_end(), and vulkan_command_buffer_free().
vulkan_command_buffer_free()
void vulkan_command_buffer_free (vulkan_context * context, VkCommandPool pool, vulkan_command_buffer * command_buffer)
Frees the command buffer back to the pool.
Must be called before destroying the pool or logical device.
Parameters
context A pointer to the active Vulkan context.
pool The command pool that owns the buffer.
command_buffer A pointer to the vulkan_command_buffer to free.
Definition at line 40 of file vulkan_command_buffer.c.
References context.
Referenced by create_command_buffers(), recreate_swapchain(), vulkan_command_buffer_end_single_use(), and vulkan_renderer_backend_shutdown().
vulkan_command_buffer_reset()
void vulkan_command_buffer_reset (vulkan_command_buffer * command_buffer)
Resets the command buffer state to READY.
Allows reuse of the command buffer after it has been submitted.
Parameters
command_buffer A pointer to the command buffer to reset.
Definition at line 85 of file vulkan_command_buffer.c.
Referenced by vulkan_renderer_backend_begin_frame().
vulkan_command_buffer_update_submitted()
void vulkan_command_buffer_update_submitted (vulkan_command_buffer * command_buffer)
Updates the state of the command buffer to SUBMITTED.
Called after submitting the buffer to a queue.
Parameters
command_buffer A pointer to the command buffer to mark as submitted.
Definition at line 81 of file vulkan_command_buffer.c.
Referenced by vulkan_renderer_backend_end_frame().