Koru Game Engine: engine/src/renderer/vulkan/vulkan_utils.c File Reference
vulkan_utils.c File Reference
Implementation of utility functions for working with VkResult return types.
#include "core/logger.h"
#include "vulkan_utils.h"
Functions
const char * vulkan_result_string (VkResult result, b8 get_extended)
Converts a VkResult into a human-readable string.
b8 vulkan_result_is_success (VkResult result)
Checks whether a VkResult represents a successful operation.
Detailed Description
Implementation of utility functions for working with VkResult return types.
Provides:
vulkan_result_string(...) for readable debug output
vulkan_result_is_success(...) for checking if a result should be treated as success
These utilities help ensure consistent error handling across all Vulkan API calls.
Definition in file vulkan_utils.c.
Function Documentation
vulkan_result_is_success()
b8 vulkan_result_is_success (VkResult result)
Checks whether a VkResult represents a successful operation.
Based on the Vulkan spec, some results are treated as "success" even if not VK_SUCCESS, such as VK_NOT_READY or VK_SUBOPTIMAL_KHR.
Parameters
result The VkResult to evaluate.
Returns
TRUE if the result indicates success (operation completed), FALSE otherwise (error occurred).
Definition at line 98 of file vulkan_utils.c.
References FALSE, and TRUE.
Referenced by vulkan_renderer_backend_begin_frame().
vulkan_result_string()
const char * vulkan_result_string (VkResult result, b8 get_extended)
Converts a VkResult into a human-readable string.
Returns either:
A short code (e.g., "VK_SUCCESS")
Or an extended message (e.g., "Command successfully completed")
Useful for logging and debugging Vulkan API calls.
Parameters
result The VkResult value to convert.
get_extended TRUE to get a descriptive message; FALSE to get only the enum name.
Returns
const char* A static string representation of the result.
Definition at line 15 of file vulkan_utils.c.
Referenced by vulkan_renderer_backend_begin_frame(), and vulkan_renderer_backend_end_frame().