Koru Game Engine: engine/src/renderer/vulkan/vulkan_backend.h File Reference
vulkan_backend.h File Reference
Public interface for the Vulkan renderer backend implementation.
#include "renderer/renderer_backend.h"
#include "resources/resource_types.h"
#include "vulkan_types.inl"
Functions
VKAPI_ATTR VkBool32 VKAPI_CALL vk_debug_callback (VkDebugUtilsMessageSeverityFlagBitsEXT message_severity, VkDebugUtilsMessageTypeFlagsEXT message_types, const VkDebugUtilsMessengerCallbackDataEXT *callback_data, void *user_data)
Debug messenger callback for Vulkan validation layers.
b8 create_buffers (vulkan_context *context)
Creates the necessary Vulkan buffers for rendering objects.
i32 find_memory_index (u32 type_filter, u32 property_flags)
Finds a suitable memory type index that satisfies the given constraints.
void create_command_buffers (renderer_backend *backend)
Creates and allocates command buffers for each frame-in-flight.
void regenerate_framebuffers (renderer_backend *backend, vulkan_swapchain *swapchain, vulkan_renderpass *renderpass)
Regenerates all framebuffers used in rendering after swapchain creation or resize.
b8 recreate_swapchain (renderer_backend *backend)
Recreates the swapchain and associated resources.
void upload_data_range (vulkan_context *context, VkCommandPool pool, VkFence fence, VkQueue queue, vulkan_buffer *buffer, u64 offset, u64 size, void *data)
Uploads data to a specified range of a Vulkan buffer.
b8 vulkan_renderer_backend_initialize (renderer_backend *backend, const char *application_name)
Initializes the Vulkan renderer backend.
void vulkan_renderer_backend_shutdown (renderer_backend *backend)
Shuts down the Vulkan renderer backend.
void vulkan_renderer_backend_on_resized (renderer_backend *backend, u16 width, u16 height)
Handles a window resize event for the Vulkan backend.
b8 vulkan_renderer_backend_begin_frame (renderer_backend *backend, f32 delta_time)
Begins a new rendering frame in the Vulkan backend.
b8 vulkan_renderer_backend_end_frame (renderer_backend *backend, f32 delta_time)
Ends the current rendering frame in the Vulkan backend.
void vulkan_renderer_update_global_state (mat4 projection, mat4 view, vec3 view_position, vec4 ambient_colour, i32 mode)
Updates the global state for rendering in the Vulkan backend.
void vulkan_backend_update_object (geometry_render_data data)
Updates the model matrix for a specific object in the Vulkan backend.
void vulkan_renderer_create_texture (const char *name, b8 auto_release, i32 width, i32 height, i32 channel_count, const u8 *pixels, b8 has_transparency, texture *out_texture)
void vulkan_renderer_destroy_texture (texture *texture)
Detailed Description
Public interface for the Vulkan renderer backend implementation.
This module implements the function table required by the renderer_frontend, providing Vulkan-specific implementations for initialization, shutdown, frame handling, and window resize handling.
Definition in file vulkan_backend.h.
Function Documentation
create_buffers()
b8 create_buffers (vulkan_context * context)
Creates the necessary Vulkan buffers for rendering objects.
*
This function initializes the vertex and index buffers used for rendering 3D objects. It sets up the buffers with appropriate usage flags and memory properties.
The vertex buffer is used to store vertex data, while the index buffer is used for indexed drawing. Both buffers are created with device-local memory for optimal performance.
Parameters
context The Vulkan context containing device and memory information.
Returns
True if buffers were created successfully, false otherwise.
Definition at line 833 of file vulkan_backend.c.
References context, False, KDEBUG, KERROR, True, and vulkan_buffer_create().
Referenced by vulkan_renderer_backend_initialize().
create_command_buffers()
void create_command_buffers (renderer_backend * backend)
Creates and allocates command buffers for each frame-in-flight.
Allocates one command buffer per swapchain image using the graphics command pool. These buffers are used during rendering to record draw commands and submit them to the GPU.
This function also ensures:
All command buffers are zeroed before use
Command buffers are created only once
They are properly indexed and accessible globally via context
Parameters
backend A pointer to the renderer backend interface (unused here, but kept for consistency).
Definition at line 711 of file vulkan_backend.c.
References context, darray_reserve, KDEBUG, kzero_memory(), True, vulkan_command_buffer_allocate(), and vulkan_command_buffer_free().
Referenced by recreate_swapchain(), and vulkan_renderer_backend_initialize().
find_memory_index()
i32 find_memory_index (u32 type_filter, u32 property_flags)
Finds a suitable memory type index that satisfies the given constraints.
This function queries the physical device's memory properties and looks for a memory type that:
Is supported by the filter (type_filter)
Has all required property flags (property_flags)
Used when allocating buffers and images to ensure they are placed in memory that is:
Device-local (fast GPU access)
Host-visible (can be accessed from CPU)
Coherent (CPU/GPU cache behavior is consistent)
If no matching memory type is found, logs a warning and returns -1.
Parameters
type_filter A bitmask indicating valid memory types (from VkMemoryRequirements.memoryTypeBits).
property_flags Required memory property flags (e.g., VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT).
Returns
i32 The index of a suitable memory type, or -1 if none was found.
Definition at line 693 of file vulkan_backend.c.
References context, KDEBUG, and KWARN.
Referenced by vulkan_renderer_backend_initialize().
recreate_swapchain()
b8 recreate_swapchain (renderer_backend * backend)
Recreates the swapchain and associated resources.
This function is called when the window is resized or when the swapchain needs to be recreated for any reason (e.g., device loss). It handles the entire process of destroying the old swapchain and creating a new one, along with all associated resources (framebuffers, command buffers, etc.).
Parameters
backend A pointer to the renderer backend interface.
Returns
True if the swapchain was successfully recreated, false otherwise.
Definition at line 758 of file vulkan_backend.c.
References cached_framebuffer_height, cached_framebuffer_width, context, create_command_buffers(), False, KDEBUG, KINFO, regenerate_framebuffers(), True, vulkan_command_buffer_free(), vulkan_device_detect_depth_format(), vulkan_device_query_swapchain_support(), vulkan_framebuffer_destroy(), and vulkan_swapchain_recreate().
Referenced by vulkan_renderer_backend_begin_frame().
regenerate_framebuffers()
void regenerate_framebuffers (renderer_backend * backend, vulkan_swapchain * swapchain, vulkan_renderpass * renderpass)
Regenerates all framebuffers used in rendering after swapchain creation or resize.
Framebuffers are tightly coupled to the swapchain — every time the swapchain is created, recreated (due to window resize), or invalidated, all associated framebuffers must be regenerated.
This function:
Destroys any existing framebuffers
Creates new ones using the current swapchain images and render pass
Binds depth/stencil attachments as needed
Must be called after:
Swapchain creation
Render pass creation
Depth attachment setup
Parameters
backend A pointer to the renderer backend interface.
swapchain A pointer to the vulkan_swapchain being used for rendering.
renderpass A pointer to the vulkan_renderpass that defines how rendering happens.
Definition at line 739 of file vulkan_backend.c.
References context, and vulkan_framebuffer_create().
Referenced by recreate_swapchain(), and vulkan_renderer_backend_initialize().
upload_data_range()
void upload_data_range (vulkan_context * context, VkCommandPool pool, VkFence fence, VkQueue queue, vulkan_buffer * buffer, u64 offset, u64 size, void * data)
Uploads data to a specified range of a Vulkan buffer.
This function creates a staging buffer, uploads the data to it, and then copies it to the specified Vulkan buffer.
Parameters
context The Vulkan context.
pool The command pool to use for buffer operations.
fence The fence to signal when the operation is complete.
queue The queue to submit the copy command to.
buffer The Vulkan buffer to upload data to.
offset The offset within the buffer to upload data to.
size The size of the data to upload.
data The data to upload.
Definition at line 43 of file vulkan_backend.c.
References context, True, vulkan_buffer_copy_to(), vulkan_buffer_create(), vulkan_buffer_destroy(), and vulkan_buffer_load_data().
Referenced by vulkan_renderer_backend_initialize().
vk_debug_callback()
VKAPI_ATTR VkBool32 VKAPI_CALL vk_debug_callback (VkDebugUtilsMessageSeverityFlagBitsEXT message_severity, VkDebugUtilsMessageTypeFlagsEXT message_types, const VkDebugUtilsMessengerCallbackDataEXT * callback_data, void * user_data)
Debug messenger callback for Vulkan validation layers.
Logs debug messages from the Vulkan validation layers to the engine's logging system.
Parameters
message_severity The severity of the message (error/warning/info/verbose).
message_types The type(s) of message (validation/performance/general).
callback_data Additional data about the message.
user_data Optional user-defined data (not used here).
Returns
Always returns VK_False (no need to abort due to message).
Definition at line 670 of file vulkan_backend.c.
References KERROR, KINFO, KTRACE, and KWARN.
Referenced by vulkan_renderer_backend_initialize().
vulkan_backend_update_object()
void vulkan_backend_update_object (geometry_render_data data)
Updates the model matrix for a specific object in the Vulkan backend.
Parameters
model The model matrix for the object.
Returns
void
Definition at line 628 of file vulkan_backend.c.
References context, vulkan_object_shader_update_object(), and vulkan_object_shader_use().
Referenced by renderer_backend_create().
vulkan_renderer_backend_begin_frame()
b8 vulkan_renderer_backend_begin_frame (renderer_backend * backend, f32 delta_time)
Begins a new rendering frame in the Vulkan backend.
Sets up command buffers, render passes, etc.
Parameters
backend A pointer to the renderer backend structure.
delta_time Time in seconds since the last frame.
Returns
True if successful; otherwise False.
Definition at line 451 of file vulkan_backend.c.
References context, False, KERROR, KINFO, KWARN, recreate_swapchain(), True, vulkan_command_buffer_begin(), vulkan_command_buffer_reset(), vulkan_fence_wait(), vulkan_renderpass_begin(), vulkan_result_is_success(), vulkan_result_string(), and vulkan_swapchain_acquire_next_image_index().
Referenced by renderer_backend_create().
vulkan_renderer_backend_end_frame()
b8 vulkan_renderer_backend_end_frame (renderer_backend * backend, f32 delta_time)
Ends the current rendering frame in the Vulkan backend.
Submits command buffers, presents the image to the screen, and cleans up per-frame resources.
Parameters
backend A pointer to the renderer backend structure.
delta_time Time in seconds since the last frame.
Returns
True if successful; otherwise False.
Definition at line 556 of file vulkan_backend.c.
References context, False, KERROR, True, vulkan_command_buffer_end(), vulkan_command_buffer_update_submitted(), vulkan_fence_reset(), vulkan_fence_wait(), vulkan_renderpass_end(), vulkan_result_string(), and vulkan_swapchain_present().
Referenced by renderer_backend_create().
vulkan_renderer_backend_initialize()
b8 vulkan_renderer_backend_initialize (renderer_backend * backend, const char * application_name)
Initializes the Vulkan renderer backend.
Creates the Vulkan instance and prepares internal resources needed for rendering.
Parameters
backend A pointer to the renderer backend structure.
application_name Name of the application using the renderer.
plat_state A pointer to the platform-specific state.
Returns
True if successful; otherwise False.
Definition at line 83 of file vulkan_backend.c.
References application_get_framebuffer_size(), cached_framebuffer_height, cached_framebuffer_width, context, create_buffers(), create_command_buffers(), darray_create, darray_length, darray_push, darray_reserve, False, find_memory_index(), INDEX_COUNT, KASSERT_MSG, KDEBUG, KERROR, KFATAL, KINFO, kzero_memory(), platform_create_vulkan_surface(), platform_get_required_extension_names(), vertex_3d::position, regenerate_framebuffers(), strings_equal(), vertex_3d::texcoord, True, upload_data_range(), VERTEX_COUNT, vk_debug_callback(), vulkan_device_create(), vulkan_fence_create(), vulkan_object_shader_acquire_resources(), vulkan_object_shader_create(), vulkan_renderpass_create(), vulkan_swapchain_create(), vec2_u::x, vec3_u::x, vec2_u::y, and vec3_u::y.
Referenced by renderer_backend_create().
vulkan_renderer_backend_on_resized()
void vulkan_renderer_backend_on_resized (renderer_backend * backend, u16 width, u16 height)
Handles a window resize event for the Vulkan backend.
May involve recreating the swapchain or adjusting viewport settings.
Parameters
backend A pointer to the renderer backend structure.
width New width of the window.
height New height of the window.
Definition at line 440 of file vulkan_backend.c.
References cached_framebuffer_height, cached_framebuffer_width, context, and KINFO.
Referenced by renderer_backend_create().
vulkan_renderer_backend_shutdown()
void vulkan_renderer_backend_shutdown (renderer_backend * backend)
Shuts down the Vulkan renderer backend.
Cleans up all resources allocated during initialization.
Parameters
backend A pointer to the renderer backend structure.
Definition at line 343 of file vulkan_backend.c.
References context, darray_destroy, KDEBUG, KINFO, vulkan_buffer_destroy(), vulkan_command_buffer_free(), vulkan_device_destroy(), vulkan_fence_destroy(), vulkan_framebuffer_destroy(), vulkan_object_shader_destroy(), vulkan_renderpass_destroy(), and vulkan_swapchain_destroy().
Referenced by renderer_backend_create().
vulkan_renderer_create_texture()
void vulkan_renderer_create_texture (const char * name, b8 auto_release, i32 width, i32 height, i32 channel_count, const u8 * pixels, b8 has_transparency, texture * out_texture)
Definition at line 868 of file vulkan_backend.c.
References texture::channel_count, context, texture::generation, texture::has_transparency, texture::height, texture::internal_data, INVALID_ID, kallocate(), KERROR, MEMORY_TAG_TEXTURE, True, vulkan_buffer_create(), vulkan_buffer_destroy(), vulkan_buffer_load_data(), vulkan_command_buffer_allocate_and_begin_single_use(), vulkan_command_buffer_end_single_use(), vulkan_image_copy_from_buffer(), vulkan_image_create(), vulkan_image_transition_layout(), vulkan_result_is_success(), vulkan_result_string(), and texture::width.
Referenced by renderer_backend_create().
vulkan_renderer_destroy_texture()
void vulkan_renderer_destroy_texture (texture * texture)
Definition at line 983 of file vulkan_backend.c.
References context, texture::internal_data, kfree(), kzero_memory(), MEMORY_TAG_TEXTURE, and vulkan_image_destroy().
Referenced by renderer_backend_create().
vulkan_renderer_update_global_state()
void vulkan_renderer_update_global_state (mat4 projection, mat4 view, vec3 view_position, vec4 ambient_colour, i32 mode)
Updates the global state for rendering in the Vulkan backend.
This function is called each frame to update the global uniform object used for rendering, such as projection and view matrices.
Parameters
projection The projection matrix for the current frame.
view The view matrix for the current frame.
view_position The camera's position in world space.
ambient_colour The ambient light colour in RGBA format.
mode Rendering mode (e.g., wireframe, solid).
Returns
void
Definition at line 543 of file vulkan_backend.c.
References context, vulkan_object_shader_update_global_state(), and vulkan_object_shader_use().
Referenced by renderer_backend_create().