Koru Game Engine: engine/src/renderer/vulkan/vulkan_shader_utils.c File Reference
vulkan_shader_utils.c File Reference
Implements utility functions for loading and creating Vulkan shader modules.
#include "vulkan_shader_utils.h"
#include "core/kstring.h"
#include "core/logger.h"
#include "core/kmemory.h"
#include "platform/filesystem.h"
Functions
b8 create_shader_module (vulkan_context *context, const char *name, const char *type_str, VkShaderStageFlagBits shader_stage_flag, u32 stage_index, vulkan_shader_stage *shader_stages)
Creates a Vulkan shader module from a SPIR-V binary file.
Detailed Description
Implements utility functions for loading and creating Vulkan shader modules.
This module provides functions to load SPIR-V shader binaries from files, create Vulkan shader modules, and set up pipeline shader stage info structures.
Definition in file vulkan_shader_utils.c.
Function Documentation
create_shader_module()
b8 create_shader_module (vulkan_context * context, const char * name, const char * type_str, VkShaderStageFlagBits shader_stage_flag, u32 stage_index, vulkan_shader_stage * shader_stages)
Creates a Vulkan shader module from a SPIR-V binary file.
This function loads the specified SPIR-V file, creates a VkShaderModule, and populates the corresponding vulkan_shader_stage structure with creation info and stage info for pipeline use.
Parameters
context A pointer to the active Vulkan context.
name The base name of the shader (without extension).
type_str The shader type string (e.g., "vert", "frag").
shader_stage_flag The VkShaderStageFlagBits indicating the shader stage.
stage_index The index in the shader_stages array to populate.
shader_stages An array of vulkan_shader_stage to hold created stages.
Returns
True if the shader module was created successfully, False otherwise.
Definition at line 17 of file vulkan_shader_utils.c.
References context, False, FILE_MODE_READ, filesystem_close(), filesystem_open(), filesystem_read_all_bytes(), KERROR, kfree(), kzero_memory(), MEMORY_TAG_STRING, string_format(), and True.
Referenced by vulkan_material_shader_create().