Koru Game Engine: engine/src/renderer/vulkan/vulkan_swapchain.c File Reference
vulkan_swapchain.c File Reference
Implementation of Vulkan swapchain creation, recreation, and destruction.
#include "core/kmemory.h"
#include "core/logger.h"
#include "vulkan_device.h"
#include "vulkan_image.h"
#include "vulkan_swapchain.h"
Functions
void create (vulkan_context *context, u32 width, u32 height, vulkan_swapchain *swapchain)
‍Forward Declarations
void destroy (vulkan_context *context, vulkan_swapchain *swapchain)
Internal function to destroy a Vulkan swapchain.
void vulkan_swapchain_create (vulkan_context *context, u32 width, u32 height, vulkan_swapchain *out_swapchain)
Creates and initializes a Vulkan swapchain for rendering.
void vulkan_swapchain_recreate (vulkan_context *context, u32 width, u32 height, vulkan_swapchain *swapchain)
Recreates the swapchain after resize or resolution change.
void vulkan_swapchain_destroy (vulkan_context *context, vulkan_swapchain *swapchain)
Destroys the given swapchain and associated resources.
b8 vulkan_swapchain_acquire_next_image_index (vulkan_context *context, vulkan_swapchain *swapchain, u64 timeout_ns, VkSemaphore image_available_semaphore, VkFence fence, u32 *out_image_index)
Acquires the index of the next available image from the swapchain.
void vulkan_swapchain_present (vulkan_context *context, vulkan_swapchain *swapchain, VkQueue graphics_queue, VkQueue present_queue, VkSemaphore render_complete_semaphore, u32 present_image_index)
Presents the rendered image at the given index to the screen.
Detailed Description
Implementation of Vulkan swapchain creation, recreation, and destruction.
This module handles:
Swapchain creation using device and surface capabilities
Recreation when window resizes or becomes outdated
Proper cleanup of images and image views
Integration with render pass and depth buffer systems
It works closely with vulkan_device, vulkan_image, and vulkan_renderpass modules.
Definition in file vulkan_swapchain.c.
Function Documentation
create()
void create (vulkan_context * context, u32 width, u32 height, vulkan_swapchain * swapchain)
‍Forward Declarations
Internal implementation of creating a new swapchain.
Internal function to create a new Vulkan swapchain.
This helper creates the actual VkSwapchainKHR object based on surface capabilities, selected format, and present mode. Called during initial creation or recreation.
Parameters
context A pointer to the active Vulkan context.
width The desired width of the swapchain images.
height The desired height of the swapchain images.
swapchain A pointer to the vulkan_swapchain structure to populate.
Performs the actual creation logic including:
Choosing the best image format and present mode
Setting up image sharing between queues
Creating image views
Initializing depth/stencil buffer
Parameters
context A pointer to the active Vulkan context.
width The width of the new swapchain.
height The height of the new swapchain.
swapchain A pointer to the vulkan_swapchain structure to populate.
Definition at line 199 of file vulkan_swapchain.c.
References context, FALSE, kallocate(), KCLAMP, KFATAL, KINFO, MEMORY_TAG_RENDERER, TRUE, vulkan_device_detect_depth_format(), vulkan_device_query_swapchain_support(), and vulkan_image_create().
Referenced by vulkan_swapchain_create(), and vulkan_swapchain_recreate().
destroy()
void destroy (vulkan_context * context, vulkan_swapchain * swapchain)
Internal function to destroy a Vulkan swapchain.
Internal implementation of destroying a swapchain.
Cleans up image views and the swapchain handle itself. Called during swapchain destruction or recreation.
Parameters
context A pointer to the active Vulkan context.
swapchain A pointer to the vulkan_swapchain to destroy.
Destroys the depth attachment, image views, and the swapchain handle.
Parameters
context A pointer to the active Vulkan context.
swapchain A pointer to the vulkan_swapchain to destroy.
Definition at line 349 of file vulkan_swapchain.c.
References context, and vulkan_image_destroy().
Referenced by vulkan_swapchain_destroy(), and vulkan_swapchain_recreate().
vulkan_swapchain_acquire_next_image_index()
b8 vulkan_swapchain_acquire_next_image_index (vulkan_context * context, vulkan_swapchain * swapchain, u64 timeout_ns, VkSemaphore image_available_semaphore, VkFence fence, u32 * out_image_index)
Acquires the index of the next available image from the swapchain.
Acquires the next available image index from the swapchain.
Waits for an image to become available, then returns its index. If the swapchain is outdated, triggers recreation logic.
Parameters
context A pointer to the active Vulkan context.
swapchain A pointer to the vulkan_swapchain being used.
timeout_ns Maximum time to wait for an image.
image_available_semaphore Semaphore signaled when image is ready.
fence Optional fence to wait on before using the image.
out_image_index Output variable to store the acquired image index.
Returns
TRUE if successful; FALSE if the swapchain needs recreation.
Definition at line 118 of file vulkan_swapchain.c.
References context, FALSE, KFATAL, TRUE, and vulkan_swapchain_recreate().
vulkan_swapchain_create()
void vulkan_swapchain_create (vulkan_context * context, u32 width, u32 height, vulkan_swapchain * out_swapchain)
Creates and initializes a Vulkan swapchain for rendering.
Creates a new Vulkan swapchain.
Sets up:
Surface format selection (preferred B8G8R8A8_UNORM)
Present mode (prefers MAILBOX_KHR if available)
Image count and extent clamped to supported values
Image views for each swapchain image
Depth attachment for rendering
Parameters
context A pointer to the active Vulkan context.
width The width of the new swapchain.
height The height of the new swapchain.
out_swapchain A pointer to the vulkan_swapchain structure to populate.
Definition at line 61 of file vulkan_swapchain.c.
References context, and create().
Referenced by vulkan_renderer_backend_initialize().
vulkan_swapchain_destroy()
void vulkan_swapchain_destroy (vulkan_context * context, vulkan_swapchain * swapchain)
Destroys the given swapchain and associated resources.
Destroys a Vulkan swapchain and releases all associated resources.
Frees all image views and destroys the internal VkSwapchainKHR object.
Parameters
context A pointer to the active Vulkan context.
swapchain A pointer to the vulkan_swapchain to destroy.
Definition at line 98 of file vulkan_swapchain.c.
References context, and destroy().
Referenced by vulkan_renderer_backend_shutdown().
vulkan_swapchain_present()
void vulkan_swapchain_present (vulkan_context * context, vulkan_swapchain * swapchain, VkQueue graphics_queue, VkQueue present_queue, VkSemaphore render_complete_semaphore, u32 present_image_index)
Presents the rendered image at the given index to the screen.
Submits the final frame to the presentation queue using the provided semaphore. Handles errors like out-of-date swapchains by triggering recreation.
Parameters
context A pointer to the active Vulkan context.
swapchain A pointer to the vulkan_swapchain being used.
graphics_queue Graphics queue handle used for rendering.
present_queue Presentation queue handle used for display.
render_complete_semaphore Semaphore signaled when rendering is complete.
present_image_index Index of the image to present.
Definition at line 159 of file vulkan_swapchain.c.
References context, KFATAL, and vulkan_swapchain_recreate().
vulkan_swapchain_recreate()
void vulkan_swapchain_recreate (vulkan_context * context, u32 width, u32 height, vulkan_swapchain * swapchain)
Recreates the swapchain after resize or resolution change.
Recreates an existing swapchain, typically after a window resize event.
Destroys the current swapchain and recreates it with updated dimensions.
Parameters
context A pointer to the active Vulkan context.
width New width of the swapchain.
height New height of the swapchain.
swapchain A pointer to the existing vulkan_swapchain to update.
Definition at line 80 of file vulkan_swapchain.c.
References context, create(), and destroy().
Referenced by vulkan_swapchain_acquire_next_image_index(), and vulkan_swapchain_present().