Koru Game Engine: engine/src/renderer/vulkan/vulkan_fence.c File Reference
vulkan_fence.c File Reference
Implementation of Vulkan fence creation, waiting, and destruction.
#include "core/logger.h"
#include "vulkan_fence.h"
Functions
void vulkan_fence_create (vulkan_context *context, b8 create_signaled, vulkan_fence *out_fence)
Creates a new Vulkan fence.
void vulkan_fence_destroy (vulkan_context *context, vulkan_fence *fence)
Destroys a Vulkan fence and releases its resources.
b8 vulkan_fence_wait (vulkan_context *context, vulkan_fence *fence, u64 timeout_ns)
Waits for the given fence to be signaled by the GPU.
void vulkan_fence_reset (vulkan_context *context, vulkan_fence *fence)
Resets the fence so it can be reused.
Detailed Description
Implementation of Vulkan fence creation, waiting, and destruction.
Fences are synchronization primitives that allow the CPU to wait for the GPU to finish tasks. They are central to managing multiple frames-in-flight safely.
Definition in file vulkan_fence.c.
Function Documentation
vulkan_fence_create()
void vulkan_fence_create (vulkan_context * context, b8 create_signaled, vulkan_fence * out_fence)
Creates a new Vulkan fence.
Fences are used to synchronize the CPU with GPU operations. A fence starts in either:
Unsignaled state (default)
Signaled state (create_signaled == True)
Parameters
context A pointer to the active Vulkan context.
create_signaled If True, the fence will be created in a signaled state.
out_fence A pointer to the vulkan_fence struct to populate.
Definition at line 14 of file vulkan_fence.c.
References context.
Referenced by vulkan_renderer_backend_initialize().
vulkan_fence_destroy()
void vulkan_fence_destroy (vulkan_context * context, vulkan_fence * fence)
Destroys a Vulkan fence and releases its resources.
Must be called before destroying the logical device.
Parameters
context A pointer to the active Vulkan context.
fence A pointer to the vulkan_fence to destroy.
Definition at line 33 of file vulkan_fence.c.
References context, and False.
Referenced by vulkan_renderer_backend_shutdown().
vulkan_fence_reset()
void vulkan_fence_reset (vulkan_context * context, vulkan_fence * fence)
Resets the fence so it can be reused.
Only resets the fence if it was previously signaled.
Parameters
context A pointer to the active Vulkan context.
fence A pointer to the vulkan_fence to reset.
Definition at line 80 of file vulkan_fence.c.
References context, and False.
Referenced by vulkan_renderer_backend_end_frame().
vulkan_fence_wait()
b8 vulkan_fence_wait (vulkan_context * context, vulkan_fence * fence, u64 timeout_ns)
Waits for the given fence to be signaled by the GPU.
If the fence is already signaled, returns immediately. Otherwise, waits up to timeout_ns nanoseconds for it to become signaled.
Parameters
context A pointer to the active Vulkan context.
fence A pointer to the vulkan_fence to wait for.
timeout_ns Maximum time to wait in nanoseconds.
Returns
True if the fence was signaled within the timeout; False otherwise.
Definition at line 44 of file vulkan_fence.c.
References context, False, KERROR, KWARN, and True.
Referenced by vulkan_renderer_backend_begin_frame(), and vulkan_renderer_backend_end_frame().