Koru Game Engine: engine/src/renderer/vulkan/vulkan_pipeline.h File Reference
vulkan_pipeline.h File Reference
Vulkan pipeline creation functions.
#include "vulkan_types.inl"
Functions
b8 vulkan_graphics_pipeline_create (vulkan_context *context, vulkan_renderpass *renderpass, u32 attribute_count, VkVertexInputAttributeDescription *attributes, u32 descriptor_set_layout_count, VkDescriptorSetLayout *descriptor_set_layouts, u32 stage_count, VkPipelineShaderStageCreateInfo *stages, VkViewport viewport, VkRect2D scissor, b8 is_wireframe, vulkan_pipeline *out_pipeline)
Creates a Vulkan graphics pipeline with the specified parameters.
void vulkan_pipeline_destroy (vulkan_context *context, vulkan_pipeline *pipeline)
Destroys a Vulkan pipeline and frees its associated resources.
void vulkan_pipeline_bind (vulkan_command_buffer *command_buffer, VkPipelineBindPoint bind_point, vulkan_pipeline *pipeline)
Binds the specified pipeline to the given command buffer.
Detailed Description
Vulkan pipeline creation functions.
This file contains functions for creating graphics pipelines in Vulkan. It includes the main function to create a graphics pipeline with specified parameters.
Definition in file vulkan_pipeline.h.
Function Documentation
vulkan_graphics_pipeline_create()
b8 vulkan_graphics_pipeline_create (vulkan_context * context, vulkan_renderpass * renderpass, u32 attribute_count, VkVertexInputAttributeDescription * attributes, u32 descriptor_set_layout_count, VkDescriptorSetLayout * descriptor_set_layouts, u32 stage_count, VkPipelineShaderStageCreateInfo * stages, VkViewport viewport, VkRect2D scissor, b8 is_wireframe, vulkan_pipeline * out_pipeline)
Creates a Vulkan graphics pipeline with the specified parameters.
This function sets up a graphics pipeline including shader stages, vertex input, viewport, rasterization, multisampling, depth/stencil state, color blending, and dynamic states. It also creates the pipeline layout with provided descriptor set layouts and push constant ranges.
Parameters
context A pointer to the active Vulkan context.
renderpass A pointer to the vulkan_renderpass defining the render pass to use.
attribute_count The number of vertex input attributes.
attributes An array of VkVertexInputAttributeDescription defining vertex attributes.
descriptor_set_layout_count The number of descriptor set layouts.
descriptor_set_layouts An array of VkDescriptorSetLayout for the pipeline layout.
stage_count The number of shader stages.
stages An array of VkPipelineShaderStageCreateInfo defining shader stages.
viewport The VkViewport defining the viewport dimensions.
scissor The VkRect2D defining the scissor rectangle.
is_wireframe True to use wireframe rasterization, False for fill mode.
out_pipeline A pointer to a vulkan_pipeline struct to populate with the created pipeline details.
Returns
True if the pipeline was created successfully, False otherwise.
Definition at line 19 of file vulkan_pipeline.c.
References context, DYNAMIC_STATE_COUNT, False, KDEBUG, KERROR, kzero_memory(), True, vulkan_result_is_success(), and vulkan_result_string().
Referenced by vulkan_material_shader_create().
vulkan_pipeline_bind()
void vulkan_pipeline_bind (vulkan_command_buffer * command_buffer, VkPipelineBindPoint bind_point, vulkan_pipeline * pipeline)
Binds the specified pipeline to the given command buffer.
This function binds the provided vulkan_pipeline to the specified vulkan_command_buffer at the given pipeline bind point (graphics or compute). The command buffer must be in the recording state when this function is called.
Parameters
command_buffer A pointer to the vulkan_command_buffer to bind the pipeline to.
bind_point The VkPipelineBindPoint indicating whether it's a graphics or compute pipeline.
pipeline A pointer to the vulkan_pipeline to bind.
Definition at line 183 of file vulkan_pipeline.c.
Referenced by vulkan_material_shader_use().
vulkan_pipeline_destroy()
void vulkan_pipeline_destroy (vulkan_context * context, vulkan_pipeline * pipeline)
Destroys a Vulkan pipeline and frees its associated resources.
This function destroys the VkPipeline and VkPipelineLayout objects associated with the given vulkan_pipeline. It must be called before destroying the Vulkan device or context to avoid memory leaks.
Parameters
context A pointer to the active Vulkan context.
pipeline A pointer to the vulkan_pipeline to destroy.
Definition at line 166 of file vulkan_pipeline.c.
References context, and KDEBUG.
Referenced by vulkan_material_shader_destroy().