Koru Game Engine: engine/src/renderer/vulkan/vulkan_device.h File Reference
vulkan_device.h File Reference
Vulkan device management interface.
#include "vulkan_types.inl"
Functions
b8 vulkan_device_create (vulkan_context *context)
Creates and selects a suitable physical/logical Vulkan device.
void vulkan_device_destroy (vulkan_context *context)
Destroys the logical device and cleans up associated resources.
void vulkan_device_query_swapchain_support (VkPhysicalDevice physical_device, VkSurfaceKHR surface, vulkan_swapchain_support_info *out_support_info)
Queries swapchain support details for a given physical device and surface.
b8 vulkan_device_detect_depth_format (vulkan_device *device)
Detects and selects a suitable depth/stencil format for the given device.
Detailed Description
Vulkan device management interface.
This module provides functions to:
Query available physical devices
Select and create a logical device
Query swapchain support on a given device and surface
These functions abstract away platform-specific device selection logic, making it easier to integrate with higher-level rendering systems.
Definition in file vulkan_device.h.
Function Documentation
vulkan_device_create()
b8 vulkan_device_create (vulkan_context * context)
Creates and selects a suitable physical/logical Vulkan device.
Queries all available physical devices, selects one based on feature and queue support, creates a logical device, and initializes queues (graphics, present, compute, transfer).
Parameters
context A pointer to the Vulkan context. Must be valid and initialized.
Returns
TRUE if a suitable device was found and successfully created; FALSE otherwise.
Queries available physical devices, selects one based on feature and queue support, creates a logical device, and initializes queues (graphics, present, compute, transfer).
Parameters
context A pointer to the Vulkan context. Must be valid and initialized.
Returns
TRUE if a suitable device was found and successfully created; FALSE otherwise.
Definition at line 147 of file vulkan_device.c.
References context, FALSE, KINFO, select_physical_device(), and TRUE.
Referenced by vulkan_renderer_backend_initialize().
vulkan_device_destroy()
void vulkan_device_destroy (vulkan_context * context)
Destroys the logical device and cleans up associated resources.
Shuts down the logical device and any internal structures like queues. Should be called before shutting down the instance.
Parameters
context A pointer to the Vulkan context containing the device to destroy.
Definition at line 256 of file vulkan_device.c.
References context, kfree(), KINFO, kzero_memory(), and MEMORY_TAG_RENDERER.
Referenced by vulkan_renderer_backend_shutdown().
vulkan_device_detect_depth_format()
b8 vulkan_device_detect_depth_format (vulkan_device * device)
Detects and selects a suitable depth/stencil format for the given device.
Tries common depth formats (D32_FLOAT, D24_UNORM_S8_UINT, etc.) and checks if they are supported with optimal tiling.
Parameters
device A pointer to the vulkan_device object.
Returns
TRUE if a valid depth format was found; FALSE otherwise.
Definition at line 366 of file vulkan_device.c.
References FALSE, and TRUE.
Referenced by create().
vulkan_device_query_swapchain_support()
void vulkan_device_query_swapchain_support (VkPhysicalDevice physical_device, VkSurfaceKHR surface, vulkan_swapchain_support_info * out_support_info)
Queries swapchain support details for a given physical device and surface.
Populates a vulkan_swapchain_support_info struct with:
Capabilities (min/max image counts, dimensions, etc.)
Formats supported
Present modes available
This information is used later when creating a swapchain.
Parameters
physical_device The physical device to query.
surface The surface to check compatibility with.
out_support_info A pointer to a structure to fill with swapchain support info.
Definition at line 320 of file vulkan_device.c.
References kallocate(), and MEMORY_TAG_RENDERER.
Referenced by create(), and physical_device_meets_requirements().