Koru Game Engine: engine/src/renderer/vulkan/vulkan_buffer.c File Reference
vulkan_buffer.c File Reference
#include "core/logger.h"
#include "core/kmemory.h"
#include "vulkan_buffer.h"
#include "vulkan_command_buffer.h"
#include "vulkan_device.h"
#include "vulkan_utils.h"
Functions
void vulkan_buffer_bind (vulkan_context *context, vulkan_buffer *buffer, u64 offset)
b8 vulkan_buffer_create (vulkan_context *context, u64 size, VkBufferUsageFlagBits usage, u32 memory_property_flags, b8 bind_on_create, vulkan_buffer *out_buffer)
void vulkan_buffer_destroy (vulkan_context *context, vulkan_buffer *buffer)
b8 vulkan_buffer_resize (vulkan_context *context, u64 new_size, vulkan_buffer *buffer, VkQueue queue, VkCommandPool pool)
void * vulkan_buffer_lock_memory (vulkan_context *context, vulkan_buffer *buffer, u64 offset, u64 size, u32 flags)
void vulkan_buffer_unlock_memory (vulkan_context *context, vulkan_buffer *buffer)
void vulkan_buffer_load_data (vulkan_context *context, vulkan_buffer *buffer, u64 offset, u64 size, u32 flags, const void *data)
void vulkan_buffer_copy_to (vulkan_context *context, VkCommandPool pool, VkFence fence, VkQueue queue, VkBuffer source, u64 source_offset, VkBuffer dest, u64 dest_offset, u64 size)
Function Documentation
vulkan_buffer_bind()
void vulkan_buffer_bind (vulkan_context * context, vulkan_buffer * buffer, u64 offset)
Definition at line 131 of file vulkan_buffer.c.
References context.
Referenced by vulkan_buffer_create().
vulkan_buffer_copy_to()
void vulkan_buffer_copy_to (vulkan_context * context, VkCommandPool pool, VkFence fence, VkQueue queue, VkBuffer source, u64 source_offset, VkBuffer dest, u64 dest_offset, u64 size)
Definition at line 152 of file vulkan_buffer.c.
References context, vulkan_command_buffer_allocate_and_begin_single_use(), and vulkan_command_buffer_end_single_use().
Referenced by upload_data_range(), and vulkan_buffer_resize().
vulkan_buffer_create()
b8 vulkan_buffer_create (vulkan_context * context, u64 size, VkBufferUsageFlagBits usage, u32 memory_property_flags, b8 bind_on_create, vulkan_buffer * out_buffer)
Definition at line 10 of file vulkan_buffer.c.
References context, False, KERROR, kzero_memory(), True, and vulkan_buffer_bind().
Referenced by create_buffers(), upload_data_range(), and vulkan_object_shader_create().
vulkan_buffer_destroy()
void vulkan_buffer_destroy (vulkan_context * context, vulkan_buffer * buffer)
Definition at line 57 of file vulkan_buffer.c.
References context, False, and KDEBUG.
Referenced by upload_data_range(), vulkan_object_shader_destroy(), and vulkan_renderer_backend_shutdown().
vulkan_buffer_load_data()
void vulkan_buffer_load_data (vulkan_context * context, vulkan_buffer * buffer, u64 offset, u64 size, u32 flags, const void * data)
Definition at line 145 of file vulkan_buffer.c.
References context, and kcopy_memory().
Referenced by upload_data_range(), and vulkan_object_shader_update_global_state().
vulkan_buffer_lock_memory()
void * vulkan_buffer_lock_memory (vulkan_context * context, vulkan_buffer * buffer, u64 offset, u64 size, u32 flags)
Definition at line 135 of file vulkan_buffer.c.
References context.
vulkan_buffer_resize()
b8 vulkan_buffer_resize (vulkan_context * context, u64 new_size, vulkan_buffer * buffer, VkQueue queue, VkCommandPool pool)
Definition at line 72 of file vulkan_buffer.c.
References context, False, KERROR, True, and vulkan_buffer_copy_to().
vulkan_buffer_unlock_memory()
void vulkan_buffer_unlock_memory (vulkan_context * context, vulkan_buffer * buffer)
Definition at line 141 of file vulkan_buffer.c.
References context.