Koru Game Engine: engine/src/renderer/vulkan/vulkan_utils.h File Reference
vulkan_utils.h File Reference
Utility functions for working with VkResult values.
#include "vulkan_types.inl"
Functions
const char * vulkan_result_string (VkResult result, b8 get_extended)
Converts a VkResult into a human-readable string.
b8 vulkan_result_is_success (VkResult result)
Checks whether a VkResult represents a successful operation.
Detailed Description
Utility functions for working with VkResult values.
This module provides:
Human-readable strings for VkResult codes
Helper function to check if a result is considered a success or failure
These are used throughout the engine to:
Log errors during initialization
Handle validation layer warnings
Debug GPU operations like image creation, command submission, etc.
Definition in file vulkan_utils.h.
Function Documentation
vulkan_result_is_success()
b8 vulkan_result_is_success (VkResult result)
Checks whether a VkResult represents a successful operation.
Based on the Vulkan spec, some results are treated as "success" even if not VK_SUCCESS, such as VK_NOT_READY or VK_SUBOPTIMAL_KHR.
Parameters
result The VkResult to evaluate.
Returns
True if the result indicates success (operation completed), False otherwise (error occurred).
Definition at line 98 of file vulkan_utils.c.
References False, and True.
Referenced by vulkan_renderer_backend_begin_frame().
vulkan_result_string()
const char * vulkan_result_string (VkResult result, b8 get_extended)
Converts a VkResult into a human-readable string.
Returns either:
A short code (e.g., "VK_SUCCESS")
Or an extended message (e.g., "Command successfully completed")
Useful for logging and debugging Vulkan API calls.
Parameters
result The VkResult value to convert.
get_extended True to get a descriptive message; False to get only the enum name.
Returns
const char* A static string representation of the result.
Definition at line 15 of file vulkan_utils.c.
Referenced by vulkan_renderer_backend_begin_frame(), and vulkan_renderer_backend_end_frame().